w3c/vc-data-model

index.html
Changed 3x to "represented" in "...MUST be representd as a Boolean type" in sections 4.1.1, 4.1.2, 4.3.2.
Fixes #22 
[Newbie aside: My branch is named 'typos-issues21-22', but discovered 21 must be changed in another file (it's in an inclusion), and so am doing it separately to avoid my head exploding.]
=> 3 typos of "representd", in 4.1.1, 4.1.2, 4.3.2

index.html
Adds some verification check instructions to page. Abstracts some text from the list I originally drafted in #9 about how profiles and keys are discovered to account for different possible ways these may be retrieved, accessed, and trusted.
@dlongley the data model for claim above does declare `id` is a required property, so I described it as such here as well. If the bearer token case you mentioned is to be taken into account, it'll require a change above as well.
=> Add verification check instructions. Relates to #9.

index.html
Closes #6. 
Adds language defining "abstract claims" and explains an example `ageOver` used elsewhere in the text.
=> Adds description of Favoring Abstract Claims

index.html
I expect this PR to be somewhat controversial. Here's the reasoning behind it:
There has been a tendancy in the Web Payments WG to use the WebIDL in a spec to throw errors if the data doesn't EXACTLY match the WebIDL. This means that browser implementations will throw errors if new data is added or existing data is not there. This creates an extensibility problem as the browsers shouldn't be making the decision on whether or not to forward data, the end applications (issuer, holder, and inspector) should make that determination.
The WebIDL is also the source of MANY errors in the spec. While those errors can be cleaned up, I think the group should have a conversation about whether or not to include WebIDL as an expression format. We should talk about which formats we may work on. For …
=> Comment out WebIDL section

index.html
Per my action item from last week's call, I've restructured the spec to contain "basic concepts", "advanced concepts" and "verification" sections. Laying the specification out in this way enables us to neatly answer a number of the questions that @ChristopherA raised in #59.
This restructuring has also led to the ability to simplify the core data model section, which will be done in a separate PR. For the time being, ignore the Core Data Model section, and focus on the "Basic Concepts", "Advanced Concepts", and "Verification" sections in the spec. Don't worry about typos/prose for now, this PR is just to test out the new layout for the spec to see if it resonates with the group.
You can preview this PR here:
https://htmlpreview.github.io/?https://github.com/w3c/vc-data-model/blob/msporny-v …
=> Restructure spec to describe basic concepts and verification

privacy.html
Convert @David-Chadwick's privacy analysis to ReSpec format.
=> Add David Chadwick's privacy analysis document

index.html
=> Add security section on dynamic information.

index.html
Add a section on the privacy implications of the use of bearer claims.
Closes #8.
=> Add "bearer credential" sub-section to privacy analysis section.

comparison.html
Add a comparison between SAML and OpenID Connect done by @David-Chadwick.
=> Add SAML/OIDC comparison by David Chadwick

index.html
This proposes a section on how we deal with Terms of Use when it comes to issuer ToS and holder/subject ToS. This is a work in progress designed to stimulate discussion and shouldn't be pulled in just yet.
/cc @jandrieu @cwebber @christopherA @kimhd @talltree @nage
=> Add section on Terms of Use. Related to #41 and #48.

README.md
Add links to WG home, charter, related repos, public mail archive and name the chairs.
=> Add useful links to WG home and related repos

common.js, index.html
Don't know why this went as long as it did undetected, but we didn't have a formal definition of what constitutes a Verifiable Profile in the spec. This is now fixed.
/cc @dlongley @burnburn @gkellogg @talltree
=> Add section on Verifiable Profiles to Basic Concepts

vocab/context.jsonld, vocab/credentials.html, vocab/credentials.jsonld, vocab/credentials.ttl, vocab/mk_vocab.rb, vocab/template.html, vocab/vocab.csv
Fixes #127.
There's probably some cruft left in here, so identifying extra terms, properties and classes that can be removed would be useful. Ideally, if we had a set of maintained examples we could use to run by the generated context and do some RDFS entailment checking of the result of transforming to RDF would help make sure we haven't missed something.
=> Update vocabulary based on changes to data model document.

index.html
Fixes #118.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/155.html" title="Last updated on Apr 7, 2018, 6:24 PM GMT (7dc8330)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/155/23bd58b...7dc8330.html" title="Last updated on Apr 7, 2018, 6:24 PM GMT (7dc8330)">Diff</a>
=> Add proofPurpose requirement to spec. Fixes #103.

index.html, terms.html
This PR adds a section on the Trust Model to the specification, which uses a modified version of @David-Chadwick's text. Fixes #110.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/131.html" title="Last updated on Apr 18, 2018, 10:15 PM GMT (95d30d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/131/bdb0974...95d30d1.html" title="Last updated on Apr 18, 2018, 10:15 PM GMT (95d30d1)">Diff</a>
=> Add section on Trust Model to the specification.

index.html
Replace "employer" with "certification body" in describing issuing authority (more frequent use case), and add a couple more categories in the Ecosystem/issuer role to represent professional credentialing better.
***
<a href="https://pr-preview.s3.amazonaws.com/stonematt/vc-data-model/pull/166.html" title="Last updated on Apr 30, 2018, 6:02 PM GMT (d07ecac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/166/9ea3a8d...stonematt:d07ecac.html" title="Last updated on Apr 30, 2018, 6:02 PM GMT (d07ecac)">Diff</a>
=> Improve refrences to prof lic/cert bodies in Intro and Ecosystem

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/173.html" title="Last updated on May 15, 2018, 9:47 PM GMT (58ac051)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/173/f3f8e01...58ac051.html" title="Last updated on May 15, 2018, 9:47 PM GMT (58ac051)">Diff</a>
=> Add security section on token binding. Fixes #148.

index.html
This PR adds a new section to the spec that tightens up the language and requirements around type information.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/177.html" title="Last updated on May 31, 2018, 2:03 PM GMT (8469ab0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/177/daed52d...8469ab0.html" title="Last updated on May 31, 2018, 2:03 PM GMT (8469ab0)">Diff</a>
=> Add section on types. Related to #174.

index.html
Attempt to address #182 by providing type expectations for encapsulating objects and associated objects.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/189.html" title="Last updated on Jul 8, 2018, 6:01 PM GMT (1188ba5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/189/ba43ef7...1188ba5.html" title="Last updated on Jul 8, 2018, 6:01 PM GMT (1188ba5)">Diff</a>
=> Attempt to fix #182 by providing type expectations.

index.html
Most W3C specs have a section on conformance. This just adds that section, which has been missing for a while.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/197.html" title="Last updated on Jul 10, 2018, 9:34 PM GMT (72a8ed0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/197/b41e408...72a8ed0.html" title="Last updated on Jul 10, 2018, 9:34 PM GMT (72a8ed0)">Diff</a>
=> Add a section on Conformance

index.html
Add a section on Semantic Interoperability to ensure that JSON-based processors don't have to process extensions as JSON-LD in order to be conformant processors.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/196.html" title="Last updated on Jul 10, 2018, 9:36 PM GMT (0edbe7d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/196/b41e408...0edbe7d.html" title="Last updated on Jul 10, 2018, 9:36 PM GMT (0edbe7d)">Diff</a>
=> Add processing restrictions to enable semantic interop. Fixes #183.

index.html, terms.html
Signed-off-by: Daniel Hardman <daniel.hardman@gmail.com>
VCs are not tamper-resistant; anybody can modify the bytes in a VC file. Rather, they are tamper-evident, meaning we can tell when such a modification happens. See the wikipedia articles about these two terms.
***
<a href="https://pr-preview.s3.amazonaws.com/dhh1128/vc-data-model/pull/218.html" title="Last updated on Aug 20, 2018, 4:35 PM GMT (2e56d54)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/218/e70d984...dhh1128:2e56d54.html" title="Last updated on Aug 20, 2018, 4:35 PM GMT (2e56d54)">Diff</a>
=> Tamper-evident, not tamper-resistant

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-data-model/pull/223.html" title="Last updated on Aug 18, 2018, 6:34 PM GMT (a57cd5d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/223/e70d984...TallTed:a57cd5d.html" title="Last updated on Aug 18, 2018, 6:34 PM GMT (a57cd5d)">Diff</a>
=> pedantic punctuation tweaks in index.html

index.html, terms.html
Signed-off-by: Daniel Hardman <daniel.hardman@gmail.com>
This embodies item #4 from https://docs.google.com/document/d/10e6lcsX0kiXkWX4_79hD1fb4p_AbFGsRm90eJJKFayI/edit -- chiefly, defining presentation and clarifying its relationship to a credential.
***
<a href="https://pr-preview.s3.amazonaws.com/dhh1128/vc-data-model/pull/220.html" title="Last updated on Aug 21, 2018, 5:08 PM GMT (e52e043)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/220/838e1f4...dhh1128:e52e043.html" title="Last updated on Aug 21, 2018, 5:08 PM GMT (e52e043)">Diff</a>
=> Distinguish credentials from presentations

index.html
Signed-off-by: Daniel Hardman <daniel.hardman@gmail.com>
This change addresses feedback from @dlongley, found here: https://docs.google.com/document/d/1xJ-763Y49UICVBv6HrOgbqrVLwXjvcHD1I0MFBoAY6w/edit?disco=AAAACDdQbj8
Basically, the spec was advocating something as best practice that often isn't a good idea (JIT issuance of bearer credentials). This PR adds a sentence explaining the caveats.
***
<a href="https://pr-preview.s3.amazonaws.com/dhh1128/vc-data-model/pull/228.html" title="Last updated on Sep 18, 2018, 3:25 PM GMT (d15376c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/228/d7f5dd3...dhh1128:d15376c.html" title="Last updated on Sep 18, 2018, 3:25 PM GMT (d15376c)">Diff</a>
=> Add caveat about JIT bearer credentials

index.html
It's not just whether the proofPurpose exists that it must be valid,
it's whether the cryptographic suite *expects* a proofPurpose to
exist and have a valid value.
***
<a href="https://pr-preview.s3.amazonaws.com/cwebber/vc-data-model/pull/249.html" title="Last updated on Oct 16, 2018, 1:14 AM GMT (fdfd492)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/249/43f46fb...cwebber:fdfd492.html" title="Last updated on Oct 16, 2018, 1:14 AM GMT (fdfd492)">Diff</a>
=> Better requirement for proofPurpose's presence and validity.

index.html
Additionally, the context at https://w3id.org/credentials/v1 says Credential instead of VerifiableCredential as well, as I discovered today while writing some VC-related code.
***
<a href="https://pr-preview.s3.amazonaws.com/cwebber/vc-data-model/pull/230.html" title="Last updated on Sep 13, 2018, 7:44 PM GMT (886ee4a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/230/a75b347...cwebber:886ee4a.html" title="Last updated on Sep 13, 2018, 7:44 PM GMT (886ee4a)">Diff</a>
=> Consistently use the VerifiableCredential type

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/257.html" title="Last updated on Oct 28, 2018, 2:29 PM GMT (92ea371)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/257/04e1533...92ea371.html" title="Last updated on Oct 28, 2018, 2:29 PM GMT (92ea371)">Diff</a>
=> Add section on Authorization. Fix #204.

index.html, vocab/context.jsonld, vocab/credentials.html, vocab/credentials.jsonld, vocab/credentials.ttl, vocab/template.html, vocab/vocab.csv
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/258.html" title="Last updated on Oct 28, 2018, 2:29 PM GMT (79c29b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/258/04e1533...79c29b4.html" title="Last updated on Oct 28, 2018, 2:29 PM GMT (79c29b4)">Diff</a>
=> Finalize the context URL for the spec to address #206.

index.html, vocab/context.jsonld, vocab/credentials.html, vocab/credentials.jsonld, vocab/credentials.ttl, vocab/vocab.csv
This PR renames `claim` to `credentialSubject` and removes the `@graph` container from claim.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/277.html" title="Last updated on Nov 15, 2018, 1:47 AM GMT (eb36d33)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/277/99b0dc9...eb36d33.html" title="Last updated on Nov 15, 2018, 1:47 AM GMT (eb36d33)">Diff</a>
=> Rename "claim" to "credentialSubject"

index.html
Addresses https://github.com/w3c/vc-data-model/issues/268 and https://github.com/w3c/vc-data-model/issues/207.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/255.html" title="Last updated on Dec 4, 2018, 9:17 PM GMT (9ed1551)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/255/bdce6b9...9ed1551.html" title="Last updated on Dec 4, 2018, 9:17 PM GMT (9ed1551)">Diff</a>
=> Add section on syntactic sugar. See #207 and #268.

index.html
The text describing the information graphs has some "funky" styling that might not be appropriate for the tone of the document? :) Perhaps suggest just using <em> tags instead?
Also, I removed a link from a figure title. Usually terms in headings and in figure and table labels are not linked? At least that seems to be the convention so far.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/326.html" title="Last updated on Dec 18, 2018, 3:18 AM UTC (a643450)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/326/8c132b4...grantnoble:a643450.html" title="Last updated on Dec 18, 2018, 3:18 AM UTC (a643450)">Diff</a>
=> Section 3.2 links and grammar and other suggestions

index.html
Just a colon, which I don't think is necessary because we're not introducing a list or anything.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/329.html" title="Last updated on Dec 18, 2018, 6:15 AM UTC (a81f82f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/329/8c132b4...grantnoble:a81f82f.html" title="Last updated on Dec 18, 2018, 6:15 AM UTC (a81f82f)">Diff</a>
=> Section 5.1 minor update

index.html
Lower case context in "JSON-LD context" as I didn't know if JSON-LD Context was an actual thing that required upper case C. I could be wrong on that.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/338.html" title="Last updated on Dec 19, 2018, 1:23 AM UTC (37ae03d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/338/a6cbe50...grantnoble:37ae03d.html" title="Last updated on Dec 19, 2018, 1:23 AM UTC (37ae03d)">Diff</a>
=> Section 6 and 6.1 grammar and formatting suggestions

index.html
An attempt to restore markup sanity.
~~Includes commit from https://github.com/w3c/vc-data-model/pull/321.  Pull that first.~~ (Removed commit.)
Quite possible this will cause conflicts in all other PRs.  If those are pulled in first I can update this PR.
***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/vc-data-model/pull/322.html" title="Last updated on Dec 20, 2018, 12:52 AM UTC (72de4ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/322/959241b...davidlehn:72de4ae.html" title="Last updated on Dec 20, 2018, 12:52 AM UTC (72de4ae)">Diff</a>
=> Fix markup

index.html
- Use ReSpec "conformance" id to add standard boilerplate.
- Move to top level section vs mistakenly getting under Advanced Concepts.
- Move earlier in doc.
Some other random specs I looked at had the conformance section early.  Is that what we want here?
***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/vc-data-model/pull/343.html" title="Last updated on Dec 20, 2018, 1:22 AM UTC (fe2d71a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/343/1f69427...davidlehn:fe2d71a.html" title="Last updated on Dec 20, 2018, 1:22 AM UTC (fe2d71a)">Diff</a>
=> Update conformance section.

index.html
Not sure if "issuer" should be code or a link. Given it's currently set tagged as code, included the word "property", as in the previous para, to clarify.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/356.html" title="Last updated on Dec 26, 2018, 11:29 PM UTC (663a253)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/356/3af2751...grantnoble:663a253.html" title="Last updated on Dec 26, 2018, 11:29 PM UTC (663a253)">Diff</a>
=> Section 9.3 wording update

index.html
Add a section on zero-knowledge proofs based on multiple conversations and design sessions between Evernym, Sovrin, and Digital Bazaar. The output of those conversations has been documented here, which we believe achieves a generalized ZKP scheme using CL Signatures:
https://docs.google.com/document/d/1D5Tc3-9dKpkl8Bp5Pisr-p-wlLlmSsFGPFkFNftEESg/edit
This PR adds a section to the spec that notes how the scheme above can be encoding using the VC Data Model.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/352.html" title="Last updated on Dec 22, 2018, 7:53 PM UTC (2d40dfc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/352/0935fb9...2d40dfc.html" title="Last updated on Dec 22, 2018, 7:53 PM UTC (2d40dfc)">Diff</a>
=> Add section on Zero-Knowledge Proofs.

VCDMExplainer.md
Removed the empty sections for ToU and Authorizations after that content was added elsewhere
=> Remove empty docuent sections

WD/2019-01-15/index.html
need to use a URI starting with https://www.w3.org as a namespace, so changed the namespace URI for the VC data model spec to "https://www.w3.org/2018/credentials"
=> change namespace URI to www.w3.org-based

index.html
This PR modifies the conformance section to only talk about document conformance as suggested in issue #317.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/397.html" title="Last updated on Jan 26, 2019, 5:32 PM UTC (987ca82)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/397/ce656da...987ca82.html" title="Last updated on Jan 26, 2019, 5:32 PM UTC (987ca82)">Diff</a>
=> Clean up conformance section

CR/2019-03-26/index.html, index.html
Use the more relevant direction example string. Note that raw UTF-8 text often isn't sufficient for proper text presentation.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/454.html" title="Last updated on Mar 19, 2019, 2:41 PM UTC (81e49c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/454/b945f06...81e49c3.html" title="Last updated on Mar 19, 2019, 2:41 PM UTC (81e49c3)">Diff</a>
=> tweak i18n considerations

index.html
Fixes #456.
One line change from
"Revocation should not reveal to the issuer any identifying information about the subject, the holder, the specific verifiable credential, or the verifier."
to
"Revocation by the issuer should not reveal any identifying information about the subject, the holder, the specific credential, or the verifier."
***
<a href="https://pr-preview.s3.amazonaws.com/ken-ebert/vc-data-model/pull/461.html" title="Last updated on Mar 19, 2019, 1:58 PM UTC (fc4ec6b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/461/b3bc88d...ken-ebert:fc4ec6b.html" title="Last updated on Mar 19, 2019, 1:58 PM UTC (fc4ec6b)">Diff</a>
=> fix revocation by issuer #456

contexts/credentials/examples/v1, index.html
> This would need to be accompanied by a change to the context file, noting that the `alumniOf` and `degree.name` are of type `rdf:HTML`
**update** Done.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/469.html" title="Last updated on Mar 19, 2019, 3:37 PM UTC (dfa4163)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/469/b3bc88d...dfa4163.html" title="Last updated on Mar 19, 2019, 3:37 PM UTC (dfa4163)">Diff</a>
=> Exemplify language tagging

index.html
digital signature's don't necessarily represent consent. Removing overreaching assertion in the example comment.
Fixes issue #472
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/476.html" title="Last updated on Mar 26, 2019, 7:46 PM UTC (9318201)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/476/d2d7488...9318201.html" title="Last updated on Mar 26, 2019, 7:46 PM UTC (9318201)">Diff</a>
=> Remove faulty assertion regarding consent

index.html
fixes the part of  #493 that isn't a proposal for new normative requirements.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/499.html" title="Last updated on Mar 27, 2019, 9:53 AM UTC (447f36c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/499/1ad7698...447f36c.html" title="Last updated on Mar 27, 2019, 9:53 AM UTC (447f36c)">Diff</a>
=> Remove must/should from informative text

index.html
Adds a note to the end of section 3.2 that clarifies that a credential may be issued to a holder who is not the subject of the credential. This addresses issue #481 
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/509.html" title="Last updated on Mar 27, 2019, 9:59 PM UTC (c160065)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/509/1ad7698...brentzundel:c160065.html" title="Last updated on Mar 27, 2019, 9:59 PM UTC (c160065)">Diff</a>
=> add note to 3.2 for issue 481

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/512.html" title="Last updated on Mar 28, 2019, 10:55 PM UTC (10c0494)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/512/1ad7698...10c0494.html" title="Last updated on Mar 28, 2019, 10:55 PM UTC (10c0494)">Diff</a>
=> Fixing "the subject of the credential" (issue #464)

index.html
This PR address some points of issues #483 and #491
=> added clarifying note to @context section

index.html, terms.html
This PR unifies the language used in the ecosystem overview (section 1.2) and terminology definitions (section 2) to partially addres issue #481
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/508.html" title="Last updated on Apr 2, 2019, 2:25 AM UTC (ede9787)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/508/1ad7698...brentzundel:ede9787.html" title="Last updated on Apr 2, 2019, 2:25 AM UTC (ede9787)">Diff</a>
=> unification of ecosystem overview and terminology

common.js, index.html
=> Clarify that multiple proof mechanisms are supported.

index.html
This PR is intended to address issue #474 
=> added clarifying note to credentialSchema section

index.html, terms.html
A few instances of "verifiable credential" or "verifiable presentation" instead of just "credential" or "presentation".
Some grammar suggestions too.
And some suggested terminology changes.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/514.html" title="Last updated on Apr 1, 2019, 4:51 AM UTC (cfe63e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/514/1ad7698...grantnoble:cfe63e3.html" title="Last updated on Apr 1, 2019, 4:51 AM UTC (cfe63e3)">Diff</a>
=> Suggested editorial updates to Introduction and Terminology sections

index.html
Again, a lot of "verifiable credential" and "verifiable presentation" instead of just "credential" or "presentation". It's a bit wordier, I know, but is more precise, IMHO.
Reworded some references to the different figures.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/515.html" title="Last updated on Apr 1, 2019, 5:37 AM UTC (6410a5e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/515/1ad7698...grantnoble:6410a5e.html" title="Last updated on Apr 1, 2019, 5:37 AM UTC (6410a5e)">Diff</a>
=> Suggested editorial update to Core Data Model section

index.html
modification of 'e.g.' to 'e.g.,' to adhere to style guidance
=> minor edit

index.html
This PR rearranges the words in one sentence to clarify that it is not recommended to dereference a context URI. May help clear up #558
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/564.html" title="Last updated on Apr 23, 2019, 7:47 PM UTC (f023501)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/564/acec79f...brentzundel:f023501.html" title="Last updated on Apr 23, 2019, 7:47 PM UTC (f023501)">Diff</a>
=> minor rearrangements of words (issue 558)

index.html
Related to issue #491.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/546.html" title="Last updated on Apr 24, 2019, 2:40 AM UTC (0221fbb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/546/8fcd004...0221fbb.html" title="Last updated on Apr 24, 2019, 2:40 AM UTC (0221fbb)">Diff</a>
=> Clarify why processing @context is useful for JSON-based processors.

index.html
This adds language to the definition of a conforming document. Even though this adds normative language, I fully believe this does not change the normative intent of the document as decided by the working group and therefore is not a substantive change as per W3C guidelines.
=> Update conformance language

index.html
it should either 1) be in both numbered options (and not precede the `1)`) or 2) be in neither numbered option (and precede the `1)`)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/570.html" title="Last updated on Apr 24, 2019, 2:39 PM UTC (931fc4d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/570/420639f...931fc4d.html" title="Last updated on Apr 24, 2019, 2:39 PM UTC (931fc4d)">Diff</a>
=> (editorial) deleted redundant word "when"

index.html
The verb must either be in each alternative clause (and follow the "either"), or precede the "either" (and be in none of the alternative clauses).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/572.html" title="Last updated on Apr 24, 2019, 4:27 PM UTC (ab9b85e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/572/420639f...ab9b85e.html" title="Last updated on Apr 24, 2019, 4:27 PM UTC (ab9b85e)">Diff</a>
=> (editorial) phrasing around either

index.html
I *think* this rephrasing and punctuation more clearly communicates the original intent. Assuming I figured out what that was...
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/581.html" title="Last updated on Apr 24, 2019, 10:50 PM UTC (1956397)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/581/6207410...1956397.html" title="Last updated on Apr 24, 2019, 10:50 PM UTC (1956397)">Diff</a>
=> (editorial) clarify VC status check

index.html
minor error, comma in wrong place resulting in invalid JSON for verifiable presentation and error in JSON-LD parser.
***
<a href="https://pr-preview.s3.amazonaws.com/jonnycrunch/vc-data-model/pull/569.html" title="Last updated on Apr 25, 2019, 5:07 PM UTC (0118fe5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/569/acec79f...jonnycrunch:0118fe5.html" title="Last updated on Apr 25, 2019, 5:07 PM UTC (0118fe5)">Diff</a>
=> fixed error in JSON for example 23

index.html
This updates the LD proof examples to use non-legacy property names and include `proofPurpose`, etc.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/619.html" title="Last updated on May 22, 2019, 8:10 PM UTC (7b03c17)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/619/66e81c7...7b03c17.html" title="Last updated on May 22, 2019, 8:10 PM UTC (7b03c17)">Diff</a>
=> Update LD proof examples.

index.html
to address #608
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/631.html" title="Last updated on May 16, 2019, 3:25 PM UTC (9bfd788)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/631/66e81c7...9bfd788.html" title="Last updated on May 16, 2019, 3:25 PM UTC (9bfd788)">Diff</a>
=> clarify when type property is required

index.html
Fixes #635 -- minor jti inconsistency/typo
***
<a href="https://pr-preview.s3.amazonaws.com/awoie/vc-data-model/pull/636.html" title="Last updated on May 21, 2019, 4:08 PM UTC (04197ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/636/66e81c7...awoie:04197ec.html" title="Last updated on May 21, 2019, 4:08 PM UTC (04197ec)">Diff</a>
=> Fixes #635 -- minor jti inconsistency/typo

index.html
This PR addresses issue #639 
It makes the following changes:
- At some some point the term `credential definition` was changed to `verifiable credential definition`. This was incorrect and has been reverted.
- The verifiable credential example proof type was changed to one that may be found in the example context.
- The normative language in this section was quite fuzzy. Language was added to the normative statements to clarify which data model elements are required in order to enable zero-knowledge proof mechanisms.
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/640.html" title="Last updated on May 24, 2019, 7:32 PM UTC (e5933d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/640/66e81c7...brentzundel:e5933d3.html" …
=> Zkp section clarifying language

contexts/credentials/examples/v1, index.html
Add an example demonstrating how multiple subjects can be associated with the `credentialSubject` property.
Related to #518.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/644.html" title="Last updated on Jun 8, 2019, 3:50 PM UTC (ac18b4d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/644/446c421...ac18b4d.html" title="Last updated on Jun 8, 2019, 3:50 PM UTC (ac18b4d)">Diff</a>
=> Add multiple subjects example.

index.html, vocab/credentials.html, vocab/credentials.jsonld, vocab/credentials.ttl, vocab/vocab.csv
Updates links to point to the appropriate location after a rename from `verifiable-claims-data-model` to `vc-data-model`.
Related to #526.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/645.html" title="Last updated on May 26, 2019, 6:41 PM UTC (f5cb934)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/645/446c421...f5cb934.html" title="Last updated on May 26, 2019, 6:41 PM UTC (f5cb934)">Diff</a>
=> Fix TR links to point to new vc-data-model URL.

index.html
Addresses examples of verifiable presentations raised in issue #654.
This pull request does not change the base context.
***
<a href="https://pr-preview.s3.amazonaws.com/ken-ebert/vc-data-model/pull/655.html" title="Last updated on May 29, 2019, 7:59 PM UTC (07e6311)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/655/d18642b...ken-ebert:07e6311.html" title="Last updated on May 29, 2019, 7:59 PM UTC (07e6311)">Diff</a>
=> Add "@context" in verifiable credentials embedded in verifiable presentation examples 

contexts/credentials/v1, index.html
This PR modifies the VC v1 context to property-scope the core types for `credentialSchema` and `refreshService`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/660.html" title="Last updated on Jun 6, 2019, 5:24 PM UTC (407f756)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/660/d18642b...407f756.html" title="Last updated on Jun 6, 2019, 5:24 PM UTC (407f756)">Diff</a>
=> Property-scope schema and refresh types.

contexts/credentials/v1, index.html
Reserve validFrom and validUntil, note expected changes in next version of spec.
Related to #584.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/646.html" title="Last updated on Jun 8, 2019, 5:01 PM UTC (c364611)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/646/d31adef...c364611.html" title="Last updated on Jun 8, 2019, 5:01 PM UTC (c364611)">Diff</a>
=> Add notes for validFrom and validUntil.

common.js, index.html
Attempt to address all remaining i18n considerations after talking w/ i18n folks, JSON-LD folks, and various people with strong opinions. This PR suggests a mechanism that works for JSON, JSON-LD, RDF, and HTML syntaxes/approaches while addressing all known i18n concerns raised to date.
Related to issue #436.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/641.html" title="Last updated on Jun 30, 2019, 6:53 PM UTC (ea43b25)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/641/446c421...ea43b25.html" title="Last updated on Jun 30, 2019, 6:53 PM UTC (ea43b25)">Diff</a>
=> Rewrite Internationalization section.

index.html
Related to #609.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/652.html" title="Last updated on Jun 8, 2019, 5:22 PM UTC (7560a0a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/652/d18642b...7560a0a.html" title="Last updated on Jun 8, 2019, 5:22 PM UTC (7560a0a)">Diff</a>
=> Change proof reference from JWT to JWS.

index.html
Added text clarifying when more than base types are needed for verifiable credentials, verifiable presentations, and embedded objects; and fixed examples of verifiable presentations.
Resolves issue #653 
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/658.html" title="Last updated on Jun 11, 2019, 4:44 PM UTC (12681f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/658/d18642b...brentzundel:12681f9.html" title="Last updated on Jun 11, 2019, 4:44 PM UTC (12681f9)">Diff</a>
=> Clarify type description

common.js
Dependency on JSON-LD 1.1 features have been confirmed by the JSON-LD 1.1 WG as stable features.
=> Update JSON-LD 1.0 references to JSON-LD 1.1.

index.html
*In the summary table,* change the type requirements of the superclasses (`Credential` and `Presentation`) to match the type requirements of the subclasses (`VerifiableCredential` and `VerifiablePresentation`).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/685.html" title="Last updated on Jul 11, 2019, 2:55 PM UTC (e158b5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/685/96dc09e...e158b5c.html" title="Last updated on Jul 11, 2019, 2:55 PM UTC (e158b5c)">Diff</a>
=> fix subclass/superclass typing requirement mismatch

index.html
The sentences before and after the diagram seemed to be saying very much the same thing, so incorporated them into the opening para and deleted the second one.
Some wording changes, and some punctuation.
In "Issuer Authorizes Holder" section, the third para was an almost word for word duplication of the opening para. Deleted the third para.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/695.html" title="Last updated on Jul 15, 2019, 7:44 PM UTC (8a38f4b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/695/96dc09e...grantnoble:8a38f4b.html" title="Last updated on Jul 15, 2019, 7:44 PM UTC (8a38f4b)">Diff</a>
=> Appendix C Subject Holder suggested editorial updates

index.html
This implements the following WG resolution:
RESOLVED: The Working Group has decided to revert the type section related to implicit typing to the text of the March 28 2019 Candidate Recommendation, and in addition we add a sentence which can be wordsmithed later, but the intention is to say "typing is complex so we refer readers to the implementation guide which contains more details.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/702.html" title="Last updated on Jul 17, 2019, 2:57 AM UTC (1b49722)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/702/d92ceaf...1b49722.html" title="Last updated on Jul 17, 2019, 2:57 AM UTC (1b49722)">Diff</a>
=> Implement VCWG Resolution wrt. implicit types. Related to #682.

index.html
This addresses #704 by:
* Adding a statement noting the use of comments and ellipsis in the examples.
* Making it not possible to select the comments in all the examples via the use of CSS magic.
* Ensuring that we're using a11y friendly colors (high contrast) for comments and highlights in the examples.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/708.html" title="Last updated on Aug 6, 2019, 6:04 PM UTC (84250cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/708/6d8c996...84250cd.html" title="Last updated on Aug 6, 2019, 6:04 PM UTC (84250cd)">Diff</a>
=> Prevent copying of comments in examples. Use a11y friendly colors.

index.html
This is designed to replace PR #710, which was approved w/ minor changes last week during the telecon. Merging.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/715.html" title="Last updated on Aug 18, 2019, 7:12 PM UTC (ae3b567)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/715/15f708d...ae3b567.html" title="Last updated on Aug 18, 2019, 7:12 PM UTC (ae3b567)">Diff</a>
=> Add example of expanded issuer property. Related to issue #709.

README.md
This process resulted from a series of meetings involving Brent Zundel, Wayne Chang, Manu Sporny, and Ivan Herman. Additional reviewers very welcome!
=> Add PR review process for 2021

README.md
This PR is here to bring main and v1.1 back in alignment. The specific commit I'm looking to bring into V1.1 is the changes to the readme which are defining the process of how we will go about handling changes in the maintenance WG as agreed to via the CCG and merged already in main.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/784.html" title="Last updated on Jul 29, 2021, 4:47 AM UTC (bca9e00)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/784/6c429cf...bca9e00.html" title="Last updated on Jul 29, 2021, 4:47 AM UTC (bca9e00)">Diff</a>
=> merge main which includes process changes into v1.1

README.md, index.html
tries to partially (diagram changes are also needed) fix #777, by uncoloring and adjusting the text
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/785.html" title="Last updated on Aug 11, 2021, 3:17 PM UTC (bd8092d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/785/b1ea54d...bd8092d.html" title="Last updated on Aug 11, 2021, 3:17 PM UTC (bd8092d)">Diff</a>
=> working on #777

contexts/credentials/examples/v1
This is an addition to the example context file which is consider non-normative so that the examples in example 2 and example 26 produce valid JSON-LD.
This PR closes #769 and closes #750
=> adds properties for AlumniCredential and DisputeCredential for valid JSON-LD examples

common.js
The [old link](https://groups.csail.mit.edu/cis/pubs/lysyanskaya/cl02b.pdf) to the CL signature paper is dead, so I have replaced it with a link to [the paper at researchgate.net](https://www.researchgate.net/publication/220922101_A_Signature_Scheme_with_Efficient_Protocols).
=> Fixed dead link to CL paper

common.js, index.html
closes #746
This updates the text to no longer point to DVCG work items and instead points to the active versions in the CCG where possible. In the case of LD-Signatures and LDS-RS2018 I've updated the text to instead point to the LDP-Registries which includes links of all of the registered LD Proofs that could be used with proofs.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/801.html" title="Last updated on Sep 9, 2021, 1:44 AM UTC (81d4ac2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/801/ea2a3ab...81d4ac2.html" title="Last updated on Sep 9, 2021, 1:44 AM UTC (81d4ac2)">Diff</a>
=> update reference links to CCG and LDP Registries

index.html
I reviewed issue #405 and PR #418 to get a better understanding of what was trying to be conveyed in this example. This is an attempt to update the example to close #754 and provide a bit of additional details about what's being conveyed with the evidence property in a note. It would be good to show this with a LoA type use case like was originally considered in #405 but couldn't think of any clear examples where LoA would be used with the example University Credential which is common throughout the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/802.html" title="Last updated on Aug 30, 2021, 2:27 AM UTC (0a19a1b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/802/ea2a3ab...0a19a1b.html" title="Last updated on Aug 30, 2021, 2:27 …
=> update evidence example and add note for explanation

contexts/credentials/examples/v1, index.html
closes #761 by updating the example context to contain all the appropriate properties and to make sure that the revocation property has been updated to credentialStatus
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/803.html" title="Last updated on Aug 30, 2021, 3:39 AM UTC (180f76c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/803/ea2a3ab...180f76c.html" title="Last updated on Aug 30, 2021, 3:39 AM UTC (180f76c)">Diff</a>
=> update example 45 to use credentialStatus and valid JSON-LD

index.html
closes #768
This updates the text in [section 4.9](https://w3c.github.io/vc-data-model/#status) where `credentialStatus` is defined to align with [section 4.8](https://w3c.github.io/vc-data-model/#expiration) to make it more clear that the `credentialStatus` property is optional without making any normative statement changes. If we want to update this to explicitly say it MAY be used then it would fall under a V1.2 change (which I'll be getting to here soon).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/804.html" title="Last updated on Aug 30, 2021, 3:56 AM UTC (2067db0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/804/ea2a3ab...2067db0.html" title="Last updated on Aug 30, 2021, 3:56 AM UTC (2067db0)">Diff</a>
=> clarify that credentialStatus isn't required without normative changes

index.html
closes #729
Originally it was pointed out that only the `issuer` should be added to this example. However, in order to remain consistent with all examples including all the require properties I added `issuanceDate` as well since it's also a required property.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/805.html" title="Last updated on Sep 1, 2021, 10:08 PM UTC (fecfb89)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/805/ea2a3ab...fecfb89.html" title="Last updated on Sep 1, 2021, 10:08 PM UTC (fecfb89)">Diff</a>
=> add issuer and issuanceDate to examples

index.html
This PR is text for issue #798
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/808.html" title="Last updated on Sep 14, 2021, 10:00 PM UTC (a51d993)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/808/10c3244...a51d993.html" title="Last updated on Sep 14, 2021, 10:00 PM UTC (a51d993)">Diff</a>
=> Credentials and Verifiable Credentials

index.html
This PR is intended to be a first cut attempt to address the concerns raised in #726 in a way that generalizes the normative language in the ZKP section of the spec. I've attempted to keep all aspects of CL-Signatures system within the scope so that it's not going to exclude the usage of that system, while also trying to call out the more generic patterns of ZKP systems that are shared by BBS+-Sigs and CL-Sigs. 
@brentzundel definitely looking to get your eyes across this soon so that we can hopefully get this in within the allotted time of the charter.
Also worth calling out that because I referenced the LDP-REGISTRY here this PR won't reference the Biblio section properly until #801 is merged onto V1.1 and I can rebase those changes in here. I intentionally left the Biblio portion out …
=> update normative statements in ZKP section

index.html
Fix #748. This changes the *MUST* requirement for [credentialStatus](https://www.w3.org/TR/vc-data-model/#status) id and
[refreshService](https://www.w3.org/TR/vc-data-model/#refreshing) id to be URI instead of URL. The purpose of this change is to
improve consistency with the rest of the data model, where `id`s are expected
to be URIs (but not necessarily URLs). This should help implementers who want to ensure conformance with the VC Data Model without feeling compelled to check whether or not certain values are URLs, which may be a difficult determination to make without further specification by extensions. For example, there the VC Test Suite doesn't check URL-ness of refresh service ids: https://github.com/w3c/vc-test-suite/blob/593d5a5fb83f89ba60f32c0443d01fced5b4a3db/test/vc-data-mod …
=> Use URI id for credentialStatus and refreshService

index.html
This closes #782 by changing the normative reference of how date-time strings are expected to represented
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/822.html" title="Last updated on Sep 30, 2021, 12:08 PM UTC (0db4216)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/822/ea2a3ab...0db4216.html" title="Last updated on Sep 30, 2021, 12:08 PM UTC (0db4216)">Diff</a>
=> address inconsistencies in date-time strings

index.html
This PR builds on PR #834 by just applying respec-vc to all other examples that it can be applied to at this time.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/835.html" title="Last updated on Nov 14, 2021, 6:07 PM UTC (90d16e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/835/7790d6c...90d16e3.html" title="Last updated on Nov 14, 2021, 6:07 PM UTC (90d16e3)">Diff</a>
=> Add respec-vc proof/JWT rendering to many other examples.

index.html
This PR adds the [respec-vc](https://github.com/digitalbazaar/respec-vc) extension to the specification and activates it for example #4. You can view the result here:
https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/834.html#example-usage-of-the-id-property
or see the image below:
Click the tabs to view the Credential, Verifiable Credential (with proof), and Verifiable Credential (as JWT).
Once this is merged, I can go through and update any other examples that would benefit from this feature. Once that's done, we can close issue #833 and PR #817.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/834.html" title="Last updated on Nov 21, 2021, 5:38 PM UTC (42392a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/834/df99d22...423 …
=> Add Verifiable Credential digital signature views for multiple examples.

index.html
This PR fixes #209 by adding a section to privacy considerations about the issuers role in providing and not violating privacy protections.
Signed-off-by: Brent Zundel <brent.zundel@gmail.com>
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/830.html" title="Last updated on Nov 22, 2021, 10:32 PM UTC (5b88bf3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/830/f01cdd3...brentzundel:5b88bf3.html" title="Last updated on Nov 22, 2021, 10:32 PM UTC (5b88bf3)">Diff</a>
=> add section in privacy considerations about issuer

index.html
Was a change request on #828 that was "resolved" but not applied.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/840.html" title="Last updated on Nov 22, 2021, 2:37 PM UTC (5fd17ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/840/e77940a...5fd17ee.html" title="Last updated on Nov 22, 2021, 2:37 PM UTC (5fd17ee)">Diff</a>
=> Moving a comma for clarity

index.html
closes issue #837
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/841.html" title="Last updated on Nov 23, 2021, 3:51 AM UTC (5384186)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/841/e77940a...5384186.html" title="Last updated on Nov 23, 2021, 3:51 AM UTC (5384186)">Diff</a>
=> Replace missed color-text that aligns with issue #777 intended changes

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/780.html" title="Last updated on Dec 9, 2021, 3:02 AM UTC (473a81a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/780/6c429cf...473a81a.html" title="Last updated on Dec 9, 2021, 3:02 AM UTC (473a81a)">Diff</a>
=> Clarified subtitle of Data Model

README.md, VCDMExplainer.md, comparison.html, index.html, privacy.html, vocab/credentials/template.html
Various cleanups.  I'd look at the various commits.  Most are basic fixes.
The "Fix sections and indents." commit hits a lot of markup so makes the overall diff a mess.  The intent was to make the markup formatting consistent.  That was a bit of a challenge because the `<hN>` tags had various numbering issues.  I think I fixed them to what they should be.  If that commit should be a different PR, I can do that.
***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/vc-data-model/pull/849.html" title="Last updated on Dec 9, 2021, 12:58 AM UTC (0d3afac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/849/4b9bdd4...davidlehn:0d3afac.html" title="Last updated on Dec 9, 2021, 12:58 AM UTC (0d3afac)">Diff</a>
***
<a …
=> URL, spelling, markup, formatting fixes

index.html
Use the code URL, not the browse UI URL.
Linking to the browse UI is clearly wrong, and was just causing failures when HTML was loaded.  But I have to wonder if jQuery is even used since it wasn't being loaded properly (at least not at this point).
I also think unpkg best practice is to link to a specific version to avoid redirects and ensure use of the same code.
***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/vc-data-model/pull/850.html" title="Last updated on Dec 9, 2021, 1:12 AM UTC (15ff3d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/850/4b9bdd4...davidlehn:15ff3d0.html" title="Last updated on Dec 9, 2021, 1:12 AM UTC (15ff3d0)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/vc-data-model/pull/850.html" title="Last …
=> Fix jQuery URL.

common.js, index.html
This updates the name and link for the [Data Integrity draft specification](https://w3c-ccg.github.io/data-integrity-spec/) that was previously called "Linked Data Proofs", and is mentioned in the [proposed Verifiable Credentials Working Group Charter](https://w3c.github.io/vc-wg-charter/). This may not yet be the final name of that specification.
Fixes https://github.com/w3c/vc-data-model/issues/858.
***
<a href="https://pr-preview.s3.amazonaws.com/peacekeeper/vc-data-model/pull/859.html" title="Last updated on Jan 19, 2022, 8:39 PM UTC (65e46ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/859/74cd6e5...peacekeeper:65e46ac.html" title="Last updated on Jan 19, 2022, 8:39 PM UTC (65e46ac)">Diff</a>
=> Rename "Linked Data Proofs" to "Data Integrity".

index.html
From [feedback on VC Data Model v1.1](https://lists.w3.org/Archives/Public/public-new-work/2022Jan/0002.html)
``` 
* Correction 2, changing "URL" to "URI", moves from a value that can be
fetched to a value that can't necessarily be fetched. The meaning of these
`id` values is undefined both before and after the change, but it moves
from the possibility of defining a general meaning for the fetched
resource, to a need to define the meaning of particular URIs in a table.
That seems like the wrong direction. The WG could cite
https://url.spec.whatwg.org/ if their goal is simply to provide a normative
definition of the "URL" term.
```
The WG also experienced some frustration in attempting to package the proposed corrections in such a way as to make them more accessible for reviewers. We would …
=> address clarification that the URI can be used to retrieve data

index.html
Both of the documents referenced in the note on transitive trust are old. Updated to the latest version
***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/vc-data-model/pull/868.html" title="Last updated on Feb 1, 2022, 6:12 AM UTC (a493a32)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/868/c48544c...shigeya:a493a32.html" title="Last updated on Feb 1, 2022, 6:12 AM UTC (a493a32)">Diff</a>
=> Updating References in the note on transitive trust

index.html
closes #781
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/847.html" title="Last updated on Dec 6, 2021, 2:07 AM UTC (5b7bd95)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/847/6253730...5b7bd95.html" title="Last updated on Dec 6, 2021, 2:07 AM UTC (5b7bd95)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/847.html" title="Last updated on Feb 10, 2022, 1:13 AM UTC (60305a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/847/c48544c...60305a5.html" title="Last updated on Feb 10, 2022, 1:13 AM UTC (60305a5)">Diff</a>
=> add section to differentiate between contexts and credential Schemas

index.html
comma was on the wrong line
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/872.html" title="Last updated on Feb 19, 2022, 11:08 AM UTC (a6abcf2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/872/8f991da...a6abcf2.html" title="Last updated on Feb 19, 2022, 11:08 AM UTC (a6abcf2)">Diff</a>
=> Update example 20

WD/2022-08-11/diagrams/claim-example-2.svg, WD/2022-08-11/diagrams/claim-example.svg, WD/2022-08-11/diagrams/claim-extended.svg, WD/2022-08-11/diagrams/claim.svg, WD/2022-08-11/diagrams/credential-graph.svg, WD/2022-08-11/diagrams/credential.svg, WD/2022-08-11/diagrams/ecosystem.svg, WD/2022-08-11/diagrams/ecosystemdetail.svg, WD/2022-08-11/diagrams/presentation-graph.svg, WD/2022-08-11/diagrams/presentation.svg, WD/2022-08-11/diagrams/privacy-spectrum.svg, WD/2022-08-11/diagrams/subject-ne-holder.svg, WD/2022-08-11/diagrams/zkp-cred-pres.svg, WD/2022-08-11/index.html, index.html, terms.html
This PR implements the following changes:
* The ReSpec configuration has been updated to reflect a v2.0 FPWD publication.
* The statements in the Status of the Document section and the changelog have been updated to note that this is a FPWD.
* A FPWD target publication date of 2022-08-04 is proposed.
* A static copy of the FPWD has been created.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/894.html" title="Last updated on Jul 27, 2022, 1:18 PM UTC (f080981)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/894/17329f4...f080981.html" title="Last updated on Jul 27, 2022, 1:18 PM UTC (f080981)">Diff</a>
=> Prepare the VC Data Model v2.0 FPWD publication

index.html
The example contains Ed25519 signature instead of RSA as mentioned
in the line.
***
<a href="https://pr-preview.s3.amazonaws.com/kushaldas/vc-data-model/pull/876.html" title="Last updated on Aug 14, 2022, 7:46 PM UTC (c9b2ea5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/876/17329f4...kushaldas:c9b2ea5.html" title="Last updated on Aug 14, 2022, 7:46 PM UTC (c9b2ea5)">Diff</a>
=> Fixes example signature name typo

index.html
fixes #891
I moved part of the text that was under the `type` property to the paragraph below that refers to the contents of the whole `credentialStatus` object.
***
<a href="https://pr-preview.s3.amazonaws.com/mirceanis/vc-data-model/pull/892.html" title="Last updated on Aug 14, 2022, 7:46 PM UTC (17d414a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/892/17329f4...mirceanis:17d414a.html" title="Last updated on Aug 14, 2022, 7:46 PM UTC (17d414a)">Diff</a>
=> Fix the `credentialStatus.type` description

common.js, index.html
This PR migrates the data integrity section into a dedicated specification.
DO NOT MERGE this until the Data Integrity specification is migrated into the VCWG.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/900.html" title="Last updated on Aug 14, 2022, 8:23 PM UTC (17c8957)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/900/893fa58...17c8957.html" title="Last updated on Aug 14, 2022, 8:23 PM UTC (17c8957)">Diff</a>
=> Migrate Data Integrity section to dedicated specification.

contexts/credentials/v2
This PR addresses PR #752 and issue #904 by specifying the Verifiable Credential v2 JSON-LD Context. The new context:
1. Removes all cryptography suites (until it becomes clear what the plan for future suites and the core context are) as requested by @OR13.
2. Removes the use of CURIEs and replaces them with full URLs as requested by @dlongley .
3. Adds the `name` and `description` VC properties as requested in PR #752 by @tplooker and @kdenhartog.
4. Temporarily removes issuanceDate/expirationDate/validFrom/validUntil due to lack of consensus on which ones to use.
This is just an initial PR for a draft v2 context. It's expected that it will change as the WG progresses its discussions.
=> Specify the draft Verifiable Credentials v2.0 context.

contexts/credentials/v2
This PR addresses issue #901 by adding DataIntegrityProof to the credentials/v2 JSON-LD Context. Here's the proposal for streamlining Data Integrity cryptosuites that was discussed at W3C TPAC:
https://docs.google.com/presentation/d/16J9TcFc6fX18Cun_Rhj3xqNlnhkCs6MnPkGBlRL3YKg/edit
This PR establishes the entirety of what we'd need to include in the credentials/v2 context to support the proposal above. This addition should cover around 80%-ish of the data integrity proof use cases we have and ensure that we don't have to keep adding date-stamped cryptosuites to the base VC context. It also makes life easier for developers using Data Integrity and VCs (as they don't have to specify separate JSON-LD Cryptosuite contexts).
Here's an open source library that implements a cryptosuite based on …
=> Add DataIntegrityProof to credentials/v2 JSON-LD Context.

index.html
Minor corrections on links. In section 4.3 the note mentions:
_"The type system for the Verifiable Credentials Data Model is the same as for [JSON-LD] and is detailed in Section 5.4: Specifying the Type and Section 8: JSON-LD Grammar."_
It  noted that section numbers in the links are out of sync with the JSON-LD spec. They should respectively point to :
- Section 3.5: Specifying the Type 
- Section 9: JSON-LD Grammar.
***
<a href="https://pr-preview.s3.amazonaws.com/richardbergquist/vc-data-model/pull/955.html" title="Last updated on Oct 24, 2022, 8:59 PM UTC (1ba9bb4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/955/5f62aed...richardbergquist:1ba9bb4.html" title="Last updated on Oct 24, 2022, 8:59 PM UTC (1ba9bb4)">Diff</a>
=> Corrects out of sync link titles in section 4.3 to json-ld spec

diagrams/credential-graph.svg, diagrams/presentation-graph.svg, index.html, schema/verifiable-credential/example-1.json, schema/verifiable-credential/example-11.json, schema/verifiable-credential/example-12.json, schema/verifiable-credential/example-13.json, schema/verifiable-credential/example-18.json, schema/verifiable-credential/example-20.json, schema/verifiable-credential/example-21.json, schema/verifiable-credential/example-23.json, schema/verifiable-credential/example-4.json, schema/verifiable-credential/verifiable-credential-schema.json, schema/verifiable-presentation/example-2.json, schema/verifiable-presentation/example-25.json, schema/verifiable-presentation/example-45.json, schema/verifiable-presentation/verifiable-presentation-schema-test.js
This PR implements a decision made by the VCWG to rename issuanceDate/expirationDate to validFrom/validUntil:
https://github.com/w3c/vc-data-model/issues/913#issuecomment-1293435120
The PR also merges the `issuanceDate` and `expirationDate` sections into one due to unnecessary duplicated content, you can preview the new combined section (which only contains editorial changes) here:
https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/992.html#validity-period
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/992.html" title="Last updated on Dec 18, 2022, 9:46 PM UTC (7522a1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/992/f293b35...7522a1d.html" title="Last updated on Dec 18, 2022, 9:46 PM UTC (7522a1d)">Diff</a>
=> Rename issuanceDate/expirationDate to validFrom/validUntil.

common.js, index.html
This PR addresses issue #912 by adding a normative dependency on the VC Data Integrity specification (as requested by @Sebastian-Elfors-IDNow) and adding a line to the revision history for the specification (as requested by @Sakurann). The normative references from the Proof section were added a while ago. 
This PR should address issue #912 in its entirety.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/993.html" title="Last updated on Dec 11, 2022, 7:47 PM UTC (8330424)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/993/6bae9b7...8330424.html" title="Last updated on Dec 11, 2022, 7:47 PM UTC (8330424)">Diff</a>
=> Add normative dependency on VC Data Integrity.

index.html, terms.html
This PR addresses issue #862 by referencing the WHATWG URL specification instead of the URI/IRI specification from IETF. An explanation as to why we're making this change is included in the PR.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/994.html" title="Last updated on Jan 7, 2023, 5:23 PM UTC (eb0f404)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/994/943d4a6...eb0f404.html" title="Last updated on Jan 7, 2023, 5:23 PM UTC (eb0f404)">Diff</a>
=> Change reference to URI/IRI to use WHATWG URL specification.

contexts/credentials/v2, index.html
This PR is a partial fix to issue #810, which notes that the v1 context failed to include the ability to use `termsOfUse` in a presentation. This PR fixes that and makes it possible to use `termsOfUse` by just including the base v2 context. /cc @kdenhartog
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1004.html" title="Last updated on Jan 15, 2023, 8:18 PM UTC (505a671)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1004/0eaebed...505a671.html" title="Last updated on Jan 15, 2023, 8:18 PM UTC (505a671)">Diff</a>
=> Add termsOfUse to presentations in v2 context.

index.html
Addresses https://github.com/w3c/vc-data-model/issues/978#issue-1448307139
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1000.html" title="Last updated on Jan 16, 2023, 9:47 PM UTC (3ce7e6e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1000/6bae9b7...3ce7e6e.html" title="Last updated on Jan 16, 2023, 9:47 PM UTC (3ce7e6e)">Diff</a>
=> Add media type registration request

contexts/credentials/v2
Addresses: https://github.com/w3c/vc-data-model/issues/953
=> Add `@vocab` to v2 context

index.html
This PR clarifies the appropriate usage of type information during validation and addresses issue #848.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 21, 2023, 5:10 PM UTC)_.
<details>
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvc-data-model%2F2f69ea87f425e9a5a2ef90cc1796dd25eea673d8%2Findex.html%3FisPreview%3Dtrue)
_If you don't have enough information above to solve the error by yourself …
=> Clarify appropriate usage of type information during validation.

vocab/credentials/v2/template.html
The reference to the vocabulary should be
```
https://w3.org/2018/credentials/
```
and not `..../credentials/v2/` as it stands today. That was the URL used for the development phase, and that is now behind us...
=> Change the reference URL in the vocabulary template file

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1026.html" title="Last updated on Feb 3, 2023, 4:56 PM UTC (499a36e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1026/c344fa0...499a36e.html" title="Last updated on Feb 3, 2023, 4:56 PM UTC (499a36e)">Diff</a>
=> Add issue to zkp section

.gitignore
this PR adds `.gitignore` to itself so that local changes to the file don't result in it appearing as a modified file and added to PRs.
Signed-off-by: Brent Zundel <brent.zundel@gmail.com>
=> ignore gitignore file

common.js, index.html
This is a replacement of an unknown draft to a current CCG draft. Separately, I am interested in in bringing CredentialSchema2022 into this working group.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1042.html" title="Last updated on Mar 1, 2023, 11:58 PM UTC (8961924)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1042/fe54b80...8961924.html" title="Last updated on Mar 1, 2023, 11:58 PM UTC (8961924)">Diff</a>
=> Replace JsonSchemaValidator2018 (undefined) with CredentialSchema2022

vocab/credentials/v2/issuer-dependent.html, vocab/credentials/v2/template.html
The latest version of the `@context` file includes a reference, via a `@vocab`, to the `https://www.w3.org/ns/credentials/issuer-dependent` URL. At present, this URL leads to a 404, which is a big no-no. This PR creates a short "namespace document" alongside the VCDM vocabulary at `https://github.com/w3c/vc-data-model/tree/main/vocab/credentials/v2/issuer-dependent.html` (the file can be [previewed here](https://raw.githack.com/w3c/vc-data-model/issuer-dependent-namespace-document/vocab/credentials/v2/issuer-dependent.html)) which provides a simple landing place.
Although not part, physically, of the PR, I also have on my local disc a `.htaccess` file that is ready to be pushed onto `https://www.w3.org/ns/credentials/` and which looks as follows:
```
RewriteEngine On
RewriteBase …
```
=> Setting up a user dependent namespace document

contexts/credentials/v2
"name" pointing at https://schema.org/description doesn't seem right.
=> VC.name term definition

index.html
Remove proposed guidance that lacked consensus per @dlongley on: https://github.com/w3c/vc-data-model/pull/1014
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1033.html" title="Last updated on Mar 6, 2023, 10:30 PM UTC (b0d7938)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1033/034e5d0...b0d7938.html" title="Last updated on Mar 6, 2023, 10:30 PM UTC (b0d7938)">Diff</a>
=> Add guidance for `credential+ld+json` for `external`proof

terms.html
the definition of verifiable credential and verifiable presentation were both embedded in other definitions.  this PR simply moves those definitions to top level terminology
=> Editorial break out of definitions for clarity

index.html
This is intended to be a work in progress PR to help achieve consensus on the right location for describing requirements and best practices around use of media types with VCs.  I believe that this PR should form a basis to close without merging #1014 as the normative language in that PR is probably in the wrong section and does not have consensus.  This PR also may provide guidance around how to proceed with #1034
***
<a href="https://pr-preview.s3.amazonaws.com/mesur-io/vc-data-model/pull/1055.html" title="Last updated on Mar 7, 2023, 2:18 PM UTC (fee2e8c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1055/ab0345e...mesur-io:fee2e8c.html" title="Last updated on Mar 7, 2023, 2:18 PM UTC (fee2e8c)">Diff</a>
=> Add section describing use of media types 

index.html
This PR is meant to be an editorial update to the media types section based on the call today. It is NOT meant to change the meaning of the section. Running this through a PR to make sure I didn't accidentally change some meaning somewhere.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1062.html" title="Last updated on Mar 15, 2023, 4:16 PM UTC (c68adee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1062/8639d7c...c68adee.html" title="Last updated on Mar 15, 2023, 4:16 PM UTC (c68adee)">Diff</a>
=> Editorial fixes to media types section.

index.html
Addresses PR #779 by limiting JSON-LD expressions to compact document form.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1050.html" title="Last updated on Mar 15, 2023, 4:26 PM UTC (e63c069)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1050/8639d7c...e63c069.html" title="Last updated on Mar 15, 2023, 4:26 PM UTC (e63c069)">Diff</a>
=> Restrict JSON-LD expression to compact document form.

index.html
This PR:
- Adds a version of the note initially drafter by Orie in #1026 
- modernizes and generalizes the language in the section in an attempt to make it more applicable to various zero knowledge proof mechanisms.
- adds a note that the examples will either be re-worked or removed.
I believe this PR prepares this section for for one of these possibilities:
1. The WG normatively specifies a method for securing VCs that supports ZKPs, in which case the examples and normative language in this section could be easily updated.
2. The WG does not normatively specify a method for securing VCs that supports ZKPs, in which case the examples and normative language in this section would be removed, and the remaining language could be moved to the implementation guide.
Signed-off-by: Brent Zundel …
=> change ZKP section

index.html
This PR addresses #956 by adding text suggested by the issue creator, with modifications to align it with the rest of the specification.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1051.html" title="Last updated on Apr 3, 2023, 6:51 PM UTC (2dfb826)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1051/dfa4884...2dfb826.html" title="Last updated on Apr 3, 2023, 6:51 PM UTC (2dfb826)">Diff</a>
=> Add warning related to protecting integrity of @context

contexts/credentials/v2
Sorta related - https://github.com/w3c/vc-data-model/issues/959
=> Remove "holder" from "VerifiableCredential"

contexts/credentials/v2, vocab/credentials/v2/vocabulary.yml
Remove the VerifiableCredential from the possible domains of holder. This is the "execution" of https://github.com/w3c/vc-data-model/pull/1076#issuecomment-1496223830.
Beware! This is a PR against the OR13-remove-holder-from-vc PR, not against the main branch!
=> Change the domain statement of "holder"

index.html
This PR updates the credentialStatus example in the spec, which used to use a fictional credential status value, to use the standards-track specification that this group has adopted.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1085.html" title="Last updated on Apr 22, 2023, 3:35 PM UTC (8b80339)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1085/fdbf89e...8b80339.html" title="Last updated on Apr 22, 2023, 3:35 PM UTC (8b80339)">Diff</a>
=> Update the credentialStatus example to a real world one.

index.html
Based on the resolution of the WG to use one base media type (`application/vc+ld+json`), this PR removes the old "JSON" section in the spec, which was always of very questionable value. The prose has been updated to specify that the base media type is `application/vc+ld+json`, and other syntaxes can be used as long as they can map to the base media type.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1088.html" title="Last updated on Apr 22, 2023, 4:30 PM UTC (3ef0175)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1088/5ae6a29...3ef0175.html" title="Last updated on Apr 22, 2023, 4:30 PM UTC (3ef0175)">Diff</a>
=> Remove JSON section in lieu of `application/vc+ld+json`.

common.js, index.html
This PR attempts to address PRs #987, #1035, #1054, #1068, and other potential future PRs of a similar nature by establishing a table of reserved properties.
The group is currently struggling to achieve consensus around extension points, mostly due to workload, that some would argue as being good for subsets of the ecosystem. Similarly, the group is concerned around defending extension points that it has previously standardized, but for which there are not a minimum of two demonstrably interoperable implementations.
In an effort to provide these extension points, but without needing to standardize implementations for each extension point, the current PR establishes a "table of reserved properties". The expectation is that each of these reserved properties would be listed in the …
=> Add table of reserved properties

index.html
Fixes #949 
This PR suggests some editorial changes to reduce confusion around some examples showing the use of `credentialSchema` with ZKPs.
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1096.html" title="Last updated on Apr 24, 2023, 6:15 PM UTC (e12db49)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1096/42ceab2...brentzundel:e12db49.html" title="Last updated on Apr 24, 2023, 6:15 PM UTC (e12db49)">Diff</a>
=> Clarify language around ZKP data format

common.js, index.html
This PR fixes old and outdated references to external specifications.
I went back and forth on whether or not references to VC-JWT and VC-DATA-INTEGRITY should be normative or informative. The argument for normative is: we are providing normative guidance to implementers to use at least one of those mechanisms. The argument for informative is to not have those dependencies in the spec, but then the argument becomes "then how do you accomplish the 'Verifiable' part of the spec?" (folks that remember history will note that informative references worked against us during the v1.0 work, and will likely work against us this time since we are normatively defining those mechanisms).
My suggestion is that we keep these normative until it looks like it might bite us (like, when trying to go to PR …
=> Fix references to old and outdated specifications.

index.html
This adds a first pass at the reserved properties table (as suggested in PR https://github.com/w3c/vc-data-model/pull/1082/files#r1170186655 by @mprorock).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1097.html" title="Last updated on Apr 28, 2023, 3:35 PM UTC (dd7666c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1097/c964156...dd7666c.html" title="Last updated on Apr 28, 2023, 3:35 PM UTC (dd7666c)">Diff</a>
=> Add first pass at reserved properties table

index.html
This PR makes minor normative changes to the proof section.
It renames the section to indicate that the focus is on Securing VCs.
It rewords the introduction to focus on securing rather than proofs.
It clarifies the normative possibilities around the proof property to better reflect the way it is actually used.
fixes #1104
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1106.html" title="Last updated on Apr 28, 2023, 4:48 PM UTC (7c2ab33)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1106/c964156...brentzundel:7c2ab33.html" title="Last updated on Apr 28, 2023, 4:48 PM UTC (7c2ab33)">Diff</a>
=> Clarify proof section

index.html
This PR removes the non-normative base JSON-LD context from the specification. NOTE: This is a non-normative change, it is not dropping JSON-LD, there is nothing drastic happening in this PR. :)
There have been complaints that including the base JSON-LD context in the specification suggests that it is normative, which the group attempted to avoid doing in v1.0 and v1.1 because it wanted the ability to modify the context in the CR/PR phase without triggering the group to go through another CR/PR round.
The group has discussed making the base JSON-LD Context normative, but there doesn't seem to be consensus on that point. Leaving the entire context in the specification feels unnecessary because: 1) it's a big file that takes up many pages in the spec, 2) it's non-normative and most people …
=> Remove non-normative base context from specification.

contexts/credentials/examples/v2, vocab/credentials/v2/examples.html
We need to be able to provide examples in the VC Data Model specification that are well formed VCs, but are constructed in such a way as to highlight certain features of the data  model. We have traditionally maintained an examples context that defined all the terms that were used in the examples in the specification. In this iteration of the specification, it has been requested that we use more real-world examples in the specification. While that is a good goal, there have been objections to the types of examples that we would use. For example, some argue that the examples in the specification are too focused on education use cases, others believe that focusing on government identity use cases is not appropriate, still others feel that supply chain examples might be too complicated when …
=> Add examples v2 context and landing page

index.html
This PR adds a "Getting Started" section that highlights usage of the new default `@vocab` and guides developers on how to use it and then upgrade to defining a vocabulary and JSON-LD Context file.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1111.html" title="Last updated on May 4, 2023, 4:40 PM UTC (78deec7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1111/c964156...78deec7.html" title="Last updated on May 4, 2023, 4:40 PM UTC (78deec7)">Diff</a>
=> Add "Getting Started" section.

index.html
This PR attempts to add some clarity around the relationship between securing mechanisms and media types.
It primarily uses language suggested in Issue #1065. 
It adds that media types defined that allow for transformation into application/vc+ld+json should begin with application/vc+
It states that application/vc+ld+json does not imply any securing mechanism
it states that other media types should not imply any securing mechanism
I removes the note about Issue #1065
fixes #1065
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1107.html" title="Last updated on May 4, 2023, 9:48 PM UTC (1e350e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1107/c964156...brentzundel:1e350e3.html" title="Last updated on May 4, 2023, 9:48 PM UTC …
=> Clarify relationship bx securing mechanisms and media types

index.html
This PR builds upon PR 1097 and adds three new properties (and their reserved URLs) to the reserved properties table: 
* `confirmationMethod` / `confidenceMethod`
* `presentationSchema`
* `renderMethod`
There is now also an example specification that demonstrates how these reserved properties could be leveraged by external specifications: [Verifiable Credential Rendering Methods](https://digitalbazaar.github.io/vc-render-method/)
The specification notes that it [utilizes the reserved property](https://digitalbazaar.github.io/vc-render-method/#the-rendermethod-property) in the VC Data Model, and then [defines a type](https://digitalbazaar.github.io/vc-render-method/#svgrenderingtemplate2023) that can be used with the extension point.
***
<a …
=> Add `renderMethod` as reserved extension point.

common.js, index.html
The PR attempts to fix #890 
It adds a note to the specification that cautions the verifier to pay attention to the `credentialSchema` when presented with selectively disclosed information. 
It describes the notion of a request schema and non-normatively points to Presentation Exchange as an example for what a verifier might use to make one.
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1112.html" title="Last updated on May 4, 2023, 5:03 PM UTC (6c29fb4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1112/c964156...brentzundel:6c29fb4.html" title="Last updated on May 4, 2023, 5:03 PM UTC (6c29fb4)">Diff</a>
=> Add note to describe use of credentialschema with selective disclosure

index.html
This PR marks the `evidence`, `termsOfUse`, and `refreshService` extension points at risk. It does this in two places: 1) the existing section, so implementers know the feature is going away if they can't demonstrate two interoperable implementations, and 2) the reserved properties table such that the reservation will be deleted, but the section will remain in the spec, if there are enough implementations.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1115.html" title="Last updated on May 13, 2023, 6:29 PM UTC (54fb7b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1115/6108bad...54fb7b5.html" title="Last updated on May 13, 2023, 6:29 PM UTC (54fb7b5)">Diff</a>
=> Mark `evidence`, `termsOfUse`, and `refreshService` extension points at risk

index.html
This PR addresses issue #946 by describing what the `id` property is used for, some example values for it, and whether or not it should be optional.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1114.html" title="Last updated on May 13, 2023, 6:49 PM UTC (4af336e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1114/d167254...4af336e.html" title="Last updated on May 13, 2023, 6:49 PM UTC (4af336e)">Diff</a>
=> Add usage guidance related to the `id` property.

index.html
Seems there is no need to comment on proof types which are not supported in the vc specs directory or the core spec, and which unnecessarily jeopardize the work item to formal objections.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1119.html" title="Last updated on May 16, 2023, 2:15 PM UTC (bd5b90a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1119/80cefee...bd5b90a.html" title="Last updated on May 16, 2023, 2:15 PM UTC (bd5b90a)">Diff</a>
=> Remove Blockchain

common.js, index.html
Also updated reference to the FPWD of the Credential Schema 2023 spec
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1137.html" title="Last updated on May 24, 2023, 3:43 PM UTC (0cb2dad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1137/f26b43e...0cb2dad.html" title="Last updated on May 24, 2023, 3:43 PM UTC (0cb2dad)">Diff</a>
=> Add section on schema validity

contexts/credentials/v2
After this PR, you will be able to issue revocable verifiable credentials using data integrity proofs with only 1 context.
Or 2 if you don't like issuer dependent terms.
Today, you need at least 3:
```
"@context": [
"https://www.w3.org/ns/credentials/v2",
"https://www.w3.org/ns/credentials/examples/v2",
"https://w3id.org/vc/status-list/2021/v1"
],
```
=> Make things easier for developers

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1141.html" title="Last updated on Jun 21, 2023, 1:13 PM UTC (6636dff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1141/e6e9fbf...6636dff.html" title="Last updated on Jun 21, 2023, 1:13 PM UTC (6636dff)">Diff</a>
=> Add issue marker for extension point reservation discussion

index.html
per conversation and feedback [on this pr on vc-jwt](https://github.com/w3c/vc-jwt/pull/90) this is probably better suited to be available in the core data model for all securing formats
***
<a href="https://pr-preview.s3.amazonaws.com/mesur-io/vc-data-model/pull/1140.html" title="Last updated on Jun 27, 2023, 4:05 PM UTC (a4ef5eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1140/cff30d3...mesur-io:a4ef5eb.html" title="Last updated on Jun 27, 2023, 4:05 PM UTC (a4ef5eb)">Diff</a>
=> add context integrity capabilities to the core data model

index.html
This PR implements two resolutions made during the last special topic call:
1. https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-13-vcwg-special#resolution1
2. https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-13-vcwg-special#resolution2
Namely:
[Resolution #1](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-13-vcwg-special#resolution1): The v2 context URL will remain normative (https://www.w3.org/ns/credentials/v2), its value will be made normative through the use of a hash digest.
[Resolution #2](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-06-13-vcwg-special#resolution2): Add issue markers saying that the value of the hash digest for the v2 context may change before PR and that’s expected.
One editorial fix the Editor's might make after this PR is to move the …
=> Make the value of the base context normative.

index.html
Fixes #937 
This PR uses language suggested in #937 to clarify that VPs are intended to be short-lived.
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1164.html" title="Last updated on Jun 23, 2023, 9:46 PM UTC (116a7e0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1164/329d6f8...brentzundel:116a7e0.html" title="Last updated on Jun 23, 2023, 9:46 PM UTC (116a7e0)">Diff</a>
=> Add language clarifying VP is short-lived

index.html
This PR attempts to clarify the use cases summary and make it easier for newcomers to parse by editorially unifying language around verifiable credentials and verifiable presentations.
It is intended as a first step toward addressing #1126
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1166.html" title="Last updated on Jun 27, 2023, 2:45 PM UTC (ce55d57)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1166/329d6f8...brentzundel:ce55d57.html" title="Last updated on Jun 27, 2023, 2:45 PM UTC (ce55d57)">Diff</a>
=> Clean up use-cases summary

index.html
This PR is an attempt to address issue #1103 by making the vocabulary URLs and content at those URLs normative. I will note that this PR is experimental, as it's not clear if it addresses all of the concerns raised in #1103.
One thing the PR does not do is refer to each vocabulary by hash (like we do for context files). It doesn't do this because doing so with vocabularies like schema.org is not possible (because the vocabulary is updated on a regular basis and thus the hashes would change on a regular basis). The same is true for the WG's vocabulary files (over time). If we were to refer to them by hash, then the next iteration of the vocabulary would break previous releases. The same is true if we included the vocabulary, verbatim, in the core specification.
So, this PR attempts to make …
=> Make the vocabulary URLs and values normative

index.html
This PR updates 3 example types used in the spec to make them clear they are examples.
It is editorial.
fixes #1125 
fixes #1124 
fixes #1123
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1170.html" title="Last updated on Jun 26, 2023, 8:13 PM UTC (053ed5f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1170/329d6f8...brentzundel:053ed5f.html" title="Last updated on Jun 26, 2023, 8:13 PM UTC (053ed5f)">Diff</a>
=> Update example types

index.html
This PR is purely editorial, it adds issue numbers to at risk extension points `evidence` (#1010) and `termsOfUse` (#870)
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1171.html" title="Last updated on Jun 26, 2023, 8:30 PM UTC (fa1c829)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1171/329d6f8...brentzundel:fa1c829.html" title="Last updated on Jun 26, 2023, 8:30 PM UTC (fa1c829)">Diff</a>
=> add issue numbers to at risk extension points

index.html, schema/verifiable-credential/verifiable-credential-schema.json, schema/verifiable-presentation/example-25.json, schema/verifiable-presentation/verifiable-presentation-schema-test.js
closes #1133, made `validFrom` optional (also fixed JSON schema)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1168.html" title="Last updated on Jul 5, 2023, 4:00 PM UTC (c75a122)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1168/7c44300...c75a122.html" title="Last updated on Jul 5, 2023, 4:00 PM UTC (c75a122)">Diff</a>
=> made validFrom optional, fixes #1133

index.html
This PR attempts to continue addressing PR #1126 by removing `credential` and `presentation` from the `type` example table.
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1179.html" title="Last updated on Jul 3, 2023, 7:15 PM UTC (37269ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1179/54d87d7...brentzundel:37269ec.html" title="Last updated on Jul 3, 2023, 7:15 PM UTC (37269ec)">Diff</a>
=> remove 'credential' and 'presentation' from 'type' examples table

index.html
This PR fixes #1161 by changing the word `credential` to the word `presentation` in the IANA considerations section for the verifiable presentations media type `vp+ld+json`
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1180.html" title="Last updated on Jul 5, 2023, 11:03 PM UTC (216941b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1180/7c44300...brentzundel:216941b.html" title="Last updated on Jul 5, 2023, 11:03 PM UTC (216941b)">Diff</a>
=> fix typo in vp+ld+json IANA considerations

index.html
The goal of this PR is to make more explicit what a VP is.
This PR is based on feedback received on PR #1167 as well as the discussion in issue #996.
This PR fixes #996.
It changes the non-normative description (Section 3.3) of verifiable presentations to remove ambiguity.
It also adds and strengthens normative statements in section 4.10.
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1181.html" title="Last updated on Jul 7, 2023, 2:16 PM UTC (b1119cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1181/7c44300...brentzundel:b1119cb.html" title="Last updated on Jul 7, 2023, 2:16 PM UTC (b1119cb)">Diff</a>
=> Presentations

index.html
Clarifying that "There is no such thing as `vc+json`", addressing #1044 and preventing future confusion like in #1088 after it was merged. As part of that clarification, it references JSON-LD spec directly wrt the processing of `@context`, since if the base media type is `vc+ld+json`, it needs to be a valid JSON-LD.
***
<a href="https://pr-preview.s3.amazonaws.com/Sakurann/vc-data-model/pull/1182.html" title="Last updated on Jul 1, 2023, 9:49 PM UTC (8278dc6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1182/562b9f3...Sakurann:8278dc6.html" title="Last updated on Jul 1, 2023, 9:49 PM UTC (8278dc6)">Diff</a>
=> removing remaining references to JSON

index.html
This PR attempts to address issue #1015 and #1040 by adding guidance on being lenient when processing less precise media types. It does not go as far as providing normative guidance (as there are many correct ways to do content sniffing, and we probably don't want to suggest one way to do it unless we're really, really sure about it being the only correct way).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1189.html" title="Last updated on Jul 14, 2023, 8:02 PM UTC (9799e5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1189/4b1cb24...9799e5c.html" title="Last updated on Jul 14, 2023, 8:02 PM UTC (9799e5c)">Diff</a>
=> Add section on media type precision.

vocab/credentials/v2/vocabulary.yml
fixes the second part of #1134
=> Add vocab terms for status list 2021

common.js, index.html
Fix #950
- Updated reference name to include the short name (`vc-json-schema`)
- Revised language to note processing of multiple schemas should be handled according to each specific type's rules
- Updated example to show multiple schemas (there are now examples with one and more than one schema)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1198.html" title="Last updated on Jul 17, 2023, 6:25 PM UTC (a40c3ce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1198/3a0e423...a40c3ce.html" title="Last updated on Jul 17, 2023, 6:25 PM UTC (a40c3ce)">Diff</a>
=> Add language around multiple schemas; update example

index.html
- acknowledge that VP is a media type in the core data model
- remove outdated text on VC-JWT
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1190.html" title="Last updated on Jul 10, 2023, 8:55 PM UTC (38c8087)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1190/0e19702...38c8087.html" title="Last updated on Jul 10, 2023, 8:55 PM UTC (38c8087)">Diff</a>
=> Adjust media types to reflect updates

index.html
This PR removes the outdated v1.0 IANA registrations for "vc" and "vp" (since that happened a while ago and they now exist in the JWT Claims registry here):
https://www.iana.org/assignments/jwt/jwt.xhtml
We don't need to keep these registration requests around, as they've been processed by IANA, and the request exists here (in perpetuity): https://www.w3.org/TR/vc-data-model/#iana-considerations
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1195.html" title="Last updated on Jul 12, 2023, 2:06 AM UTC (64fa61f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1195/eb58625...64fa61f.html" title="Last updated on Jul 12, 2023, 2:06 AM UTC (64fa61f)">Diff</a>
=> Remove outdated v1.0 JWT claim registrations.

contexts/credentials/v2
Since the v2 context contains terms specific to data integrity proofs.
And I have closed the PR attempting to remove those terms: https://github.com/w3c/vc-data-model/pull/1091
It stands to reason we will need to add terms related to all proof formats to the v2 context, in the spirit of making things easier for developers.
=> Add graph node identifiers for registered claims

diagrams/ecosystemdetail.svg, index.html
This PR addresses #860 by introducing normative guidance for a holder to include self-asserted claims inside of a VP.
It is based on the conversation in #860 where it was suggested that the holder should construct a VC with the self-asserted claims and include that in the VP.
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1186.html" title="Last updated on Jul 19, 2023, 4:55 PM UTC (9559c36)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1186/7c44300...brentzundel:9559c36.html" title="Last updated on Jul 19, 2023, 4:55 PM UTC (9559c36)">Diff</a>
=> Add interoperable way for holder-asserted claims in a VP

index.html
This PR attempts to address issue #1048 by implementing the [last two](https://github.com/w3c/vc-data-model/issues/1048#issue-1588485377) remaining [resolutions from the Feb 2023 F2F meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-02-16-vcwg#resolution1). Here are the currently unimplemented parts of the resolution that this PR attempts to address:
> Serializations in other media types (defined by the VCWG) MUST be able to be transformed into the base media type. 
This is guidance for the VCWG, and thus does not need to be placed into normative text in the core data model. If a specification produced by the VCWG does not provide this language, it will almost certainly be objected to by a subset of the WG.
> Another media type MUST identify if this transformation is …
=> Add section on Ecosystem Compatibility.

contexts/credentials/v2, index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1142.html" title="Last updated on Aug 2, 2023, 5:30 PM UTC (a0b38f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1142/e6e9fbf...a0b38f9.html" title="Last updated on Aug 2, 2023, 5:30 PM UTC (a0b38f9)">Diff</a>
=> Add confidenceMethod to table of reserved terms and v2 `@context`

index.html
At the moment §B declares itself as non-normative, and this is, sort of, "inherited" by subsections unless stated otherwise. Ie, §B.1 and §B.2 may be considered as non-normative, which is not the intention. Better leave §B to normative (the default) and §B.3 explicitly declares itself as non-normative.
Just to avoid misunderstandings...
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1200.html" title="Last updated on Jul 14, 2023, 10:15 AM UTC (b536d68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1200/3a0e423...b536d68.html" title="Last updated on Jul 14, 2023, 10:15 AM UTC (b536d68)">Diff</a>
=> Better not set §B as non-normative (minor editorial)

index.html
This PR attempts to address issue #1201 by documenting how systems process the VCDM using pure JSON processing today.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1202.html" title="Last updated on Aug 9, 2023, 10:18 PM UTC (f007a19)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1202/6c5cebb...f007a19.html" title="Last updated on Aug 9, 2023, 10:18 PM UTC (f007a19)">Diff</a>
=> Add section on JSON Processing.

contexts/credentials/v2, index.html
This PR adds `iat` as a registered claim name to the v2 context.
Beware that `iat` aligns with `proof.created` in data integrity.
`iat` is not be be confused with `nbf` which is now called `validFrom`.
```json
{
"@context": [
"https://w3id.org/traceability/v1", {
"iat": {
"@id": "https://www.iana.org/assignments/jwt#iat",
"@type": "https://www.w3.org/2001/XMLSchema#nonNegativeInteger"
}
}
],
"type": "Organization",
"name": "Bartell Inc 🔥",
"description": "Realigned maximized alliance",
"iat": 123
}
```
....
```
_:c14n0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://schema.org/Organization> .
_:c14n0 <https://schema.org/description> "Realigned maximized alliance" .
_:c14n0 <https://schema.org/name> "Bartell Inc 🔥" .
_:c14n0 <https://www.iana.org/assignments/jwt#iat> …
```
=> Add iat registered claim to v2 context

index.html
This is, content-wise, the same PR as #1225, but starting fresh due to the merge problems. See #1226 (comment).
No need to re-review from scratch, just taking over #1225
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1229.html" title="Last updated on Aug 4, 2023, 3:23 PM UTC (ee7d5c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1229/7e6e996...ee7d5c8.html" title="Last updated on Aug 4, 2023, 3:23 PM UTC (ee7d5c8)">Diff</a>
=> Editorial update index.html: use JsonSchema and not JsonSchema2023 — bis

vocab/credentials/v2/vocabulary.yml
This (under-specified) property has been removed from the VCDM spec, so this PR removes the item from the vocabulary, too.
=> Removing the serviceEndpoint vocabulary item

vocab/credentials/v2/vocabulary.yml
This is, content-wise, the same PR as #1226, but starting fresh due to the merge problems. See https://github.com/w3c/vc-data-model/pull/1226#issuecomment-1665495765.
No need to re-review from scratch, just taking over #1226
=> Added reserved confidenceMethod property to the vocabulary — bis

index.html
This PR is an attempt to address #1009 and #1126 by clarifying the difference between a "credential" (an abstract concept) and a "verifiable credential" (a concrete concept). Adjustments are made to normative statements to not talk about "credentials" or "presentations", but rather only "verifiable credentials" and "verifiable presentations" (which MUST be secured).
I expect other adjustments need to be made throughout the spec, and if this PR goes through, we can make those adjustments more easily given consensus around this text being the basis for removing mentions of "credential" or "presentation", when what we meant was "verifiable credential" or "verifiable presentation". Namely, no normative statement in the specification should talk about "credential" or "presentation" if this PR …
=> Clarify the difference between a "credential" and a "verifiable credential"

index.html
This PR attempts to address issue #1105 by explicitly stating that `proof` types SHOULD come from the VC-SPECS-DIR. The PR avoids saying "MUST" because VC-SPECS-DIR is not meant to be the authoritative registry of everything VCs, but rather a directory of things that individuals wanted to have listed.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1212.html" title="Last updated on Aug 20, 2023, 5:19 PM UTC (3bcf15a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1212/d84cf2e...3bcf15a.html" title="Last updated on Aug 20, 2023, 5:19 PM UTC (3bcf15a)">Diff</a>
=> Refer to VC-SPECS-DIR for proof types.

contexts/credentials/v2
This PR adds registered claim names for sd-jwt to the v2 context.
Like the other PRs, it assumes IANA registries are navigable.
Unlike the other PRs, these terms are not yet present in the JWT registries... so the OAuth WG should be consulted on the best location for implementers to understand these terms.
[Example SD-JWT that would use these definitions](https://jwt.io/#debugger-io?token=eyJhbGciOiJFUzM4NCJ9.eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvbnMvY3JlZGVudGlhbHMvdjIiLCJodHRwczovL3czaWQub3JnL3RyYWNlYWJpbGl0eS92MSJdLCJpZCI6Imh0dHA6Ly9zdXBwbHktY2hhaW4uZXhhbXBsZS9jcmVkZW50aWFscy9kZDBjNmY5YS01ZGY2LTQwYTMtYmIzNC04NjNjZDFmZGE2MDYiLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiRW50cnlOdW1iZXJDcmVkZW50aWFsIl0sInZhbGlkRnJvbSI6IjIwMjMtMDgtMTVUMTU6NTg6NTUuNzMyWiIsInZhbGlkVW50aWwiOiIyMDIzLTA5LTE …
=> Add sd-jwt registered claim names to v2 context

index.html
This PR attempts to address issue #1177 by providing actionable guidance related to base context hash value. The text applies a suggestion by @jyasskin to treat the context URLs as "already resolved" with specific hash values. It also notes that implementations are expected to throw errors when hash values differ from the expected value w/o saying that they MUST throw errors (in cases where hash values change all the time, like schema.org).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1249.html" title="Last updated on Aug 27, 2023, 11:01 PM UTC (aec155a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1249/43ac552...aec155a.html" title="Last updated on Aug 27, 2023, 11:01 PM UTC (aec155a)">Diff</a>
=> Provide actionable guidance related to base context hash value.

index.html
This PR is an attempt to address issue #1231 by applying value range requirements to `validFrom` and `validUntil` as requested by @David-Chadwick, @TallTed, and @dlongley.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1250.html" title="Last updated on Aug 27, 2023, 11:13 PM UTC (d0c9d3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1250/f4a8ea1...d0c9d3d.html" title="Last updated on Aug 27, 2023, 11:13 PM UTC (d0c9d3d)">Diff</a>
=> Apply range requirements to validFrom/validUntil.

index.html
This PR attempts to address issue #1175 by outlining the mitigation strategy for ensuring that the contents in the base context don't impact the various specifications being worked on by this WG from transitioning to Recommendation status in a timely way.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1251.html" title="Last updated on Aug 20, 2023, 9:33 PM UTC (13e8004)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1251/03b0d90...13e8004.html" title="Last updated on Aug 20, 2023, 9:33 PM UTC (13e8004)">Diff</a>
=> Outline plan to mitigate normative context risk when transitioning to Proposed Recommendation

vocab/credentials/v2/vocabulary.svg, vocab/credentials/v2/vocabulary.yml
This is actually a replacement of #1241 : it includes all the changes in there, plus the missing pieces in https://github.com/w3c/vc-data-model/pull/1241#issuecomment-1685780129.
Making PR on top of #1241 would have led to problems because, in the meantime, the main branch has changed too much (e.g., the diagrams have been added), so it was simpler to create a PR on top of `main` rather than `fix/vocab-issues`
=> Vocabulary fixes — replacement of #1241

contexts/credentials/v2, index.html
This PR is an attempt to address issue #1214 by adding a section that defines the `name` and `description` properties.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1252.html" title="Last updated on Aug 29, 2023, 8:09 PM UTC (1974cd2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1252/dbd67ab...1974cd2.html" title="Last updated on Aug 29, 2023, 8:09 PM UTC (1974cd2)">Diff</a>
=> Add section about Names and Descriptions of credentials.

index.html
This PR fixes #1118 
This PR adds language to the media types section about accept headers and content types.
It is most certainly not entirely correct or sufficient, but hopefully can serve as a starting point to bring in the ideas discussed in #1118.
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1257.html" title="Last updated on Aug 28, 2023, 5:19 PM UTC (95058ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1257/3b0e073...brentzundel:95058ef.html" title="Last updated on Aug 28, 2023, 5:19 PM UTC (95058ef)">Diff</a>
=> VCDM Media Types and HTTP

index.html
This PR fixes #1132 
It adds language to the JSON-LD section giving guidance to those who wish to include arrays and lists in the data model.
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/1258.html" title="Last updated on Sep 5, 2023, 3:22 PM UTC (6536d0b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1258/3b0e073...brentzundel:6536d0b.html" title="Last updated on Sep 5, 2023, 3:22 PM UTC (6536d0b)">Diff</a>
=> Guidance around arrays

contexts/credentials/v2
This PR is an attempt to address issue #1150 by ensuring that redefinition doesn't fail in `verifiableCredential` when holding a VC v1.x compliant VC. It also fixes two bugs in the v2 context: 1) ensures that redefinition doesn't fail for `cnf`, and 2) synchronizes the DataIntegrity scoped context terms to now include `cryptosuiteString`.
=> Sync and fix bugs in v2 context.

vocab/credentials/v2/template.html, vocab/credentials/v2/vocabulary.svg, vocab/credentials/v2/vocabulary.yml
This is the counterpart, in the VCDM vocabulary, of https://github.com/w3c/vc-json-schema/pull/211. The diagram, and its alt-text description, has also been adapted.
See the [preview of the generated vocab](https://w3c.github.io/yml2vocab/previews/vcdm/vocabulary.html)
=> Adding the jsonSchema property to the vocabulary

index.html
Addresses https://github.com/w3c/vc-data-model/issues/959
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1199.html" title="Last updated on Sep 1, 2023, 1:49 PM UTC (de684ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1199/3a0e423...de684ba.html" title="Last updated on Sep 1, 2023, 1:49 PM UTC (de684ba)">Diff</a>
=> Add validation section regarding holder

vocab/credentials/v2/vocabulary.yml
***This is a PR against #1272***
The vocabulary definitions for the base classes have been changed to rely on the table in the VCDM specification.
=> Base classes are defined now in the spec

terms.html
=> updated entity to include abstract nouns

index.html, vocab/credentials/v2/vocabulary.yml
This PR attempts to address part of issue #1263 by defining base classes (and their anchors) in the VCDM specification.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Sep 26, 2023, 8:39 PM UTC)_.
<details>
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvc-data-model%2Ff5b8ac9e937acf27a8e63bcef30bfb8d0cc1f434%2Findex.html%3FisPreview%3Dtrue)
```
😭  Sorry, there was an error generating the HTML. Please …
```
=> Add base classes and fragment identifiers for vocabulary.

index.html, vocab/credentials/v2/vocabulary.yml
This PR is an attempt to address #1240 by defining the concept of a Verifiable Credential Graph, noting why the concept exists, and how those not doing full JSON-LD processing need to think about the problem space that the Verifiable Credential Graph addresses.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1280.html" title="Last updated on Sep 26, 2023, 9:18 PM UTC (d543779)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1280/6a3a927...d543779.html" title="Last updated on Sep 26, 2023, 9:18 PM UTC (d543779)">Diff</a>
=> Add definition of Verifiable Credential Graph and why it exists

index.html
This PR is an attempt at addressing #1185 by noting how the normative context is used and to make sure that if that optional processing is performed, if an error occurs, verification MUST fail.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1281.html" title="Last updated on Sep 26, 2023, 9:26 PM UTC (6247ecf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1281/d300869...6247ecf.html" title="Last updated on Sep 26, 2023, 9:26 PM UTC (6247ecf)">Diff</a>
=> Add normative requirements related to context processing

contexts/credentials/v2
This PR syncs the credentials v2 context with the changes in this PR: https://github.com/w3c/vc-data-integrity/pull/202 ... which adds `previousProof`.
=> Sync v2 context with data integrity context.

index.html
This PR needs to be merged to add the vc-jose-cose examples at https://github.com/w3c/vc-jose-cose/pull/162#pullrequestreview-1662677250
***
<a href="https://pr-preview.s3.amazonaws.com/selfissued/vc-data-model/pull/1308.html" title="Last updated on Oct 13, 2023, 6:12 PM UTC (7878d79)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1308/286c2b2...selfissued:7878d79.html" title="Last updated on Oct 13, 2023, 6:12 PM UTC (7878d79)">Diff</a>
=> Remove "proof" clauses from initial examples

common.js, index.html
This PR adds a reference to vc-di-bbs, which is expected to be the only zkp credential system commented on by the WG, and is currently stalled, awaiting new leadership. 
See: 
- https://github.com/w3c/vc-di-bbs/pull/91
- https://github.com/w3c/vc-di-bbs/issues/84
I've retained normative statements surrounding the example, but removed the examples.
Ideally, we get some bbs examples in the spec here soon, although I personally think it would be better to drop the bbs work item, and focus on improving the specification and test suites related to the existing security mechansisms.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1305.html" title="Last updated on Oct 4, 2023, 10:32 PM UTC (0d7bdca)">Preview</a> | <a …
=> Remove CL Signature Example

.gitignore, contexts/credentials/v2, index.html, vocab/credentials/v2/README.md, vocab/credentials/v2/template.html, vocab/credentials/v2/vocabulary.drawio, vocab/credentials/v2/vocabulary.svg, vocab/credentials/v2/vocabulary.yml
This is the [action I took at the F2F](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-14-vcwg#section5-1): adding the resource integrity terms to the VCDM vocabulary. Here is what I did:
- Added anchors to the `digestSRI` and `relatedResource` terms in the specification itself (to be used by the vocabulary)
- Added a section to define the `sriString` datatype
- Added the `digestSRI`, `relatedResource`, `mediaType` to the v2 `@context` file
- Added the `digestSRI` and `relatedResource` properties, as well as the `sriString` datatype, to `vocabulary.yml`
- Added a section on data types in the vocabulary’s `template.html` file for the vocabulary generation
- Expanded the diagram’s alt text to also refer to the new terms
Note that the `mediaType` term has not been added to the …
=> Add `relatedResource` and `digestSRI` to the vocabulary

common.js, index.html
This PR attempts to address issue #1267 by suggesting that implementers consider Oblivious HTTP when fetching external resources. /cc @kdenhartog
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1322.html" title="Last updated on Oct 29, 2023, 11:35 PM UTC (0234a2b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1322/cc5cd92...0234a2b.html" title="Last updated on Oct 29, 2023, 11:35 PM UTC (0234a2b)">Diff</a>
=> Add suggestion to use Oblivious HTTP when fetching resources.

index.html
This PR is an attempt at addressing issue #1261, which requested that cryptographic hashes be added to the vocabulary files. This PR utilizes both frozen static files and hash values to achieve the end result, which are stable vocabulary definitions for systems that perform RDF vocabulary processing (which is a completely optional, non-mandatory thing).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1279.html" title="Last updated on Oct 21, 2023, 6:54 PM UTC (1a88c3c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1279/87a4db3...1a88c3c.html" title="Last updated on Oct 21, 2023, 6:54 PM UTC (1a88c3c)">Diff</a>
=> Add links to static copies of vocabulary files and hashes

index.html, terms.html
Fixes merge conflits in PR #1297.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1334.html" title="Last updated on Nov 4, 2023, 6:09 PM UTC (85f2e30)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1334/9d661d9...85f2e30.html" title="Last updated on Nov 4, 2023, 6:09 PM UTC (85f2e30)">Diff</a>
=> Rebase PR #1297

terms.html
Addresses: https://github.com/w3c/vc-data-model/issues/1047
=> Add comparison to NIST definition

index.html
This PR is an attempt to address issues #1264 and #1266. It provides guidance that document authors shouldn't use JSON-LD keywords that affect document processing inside the `@context` array because it can impact how processors that don't do full JSON-LD processing interpret the document, leading to a degradation in interoperability.
A separate PR will be raised for guidance on how to use the language features to increase interoperability. This PR just says "don't use the `@language` sledgehammer in `@context`".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1271.html" title="Last updated on Nov 14, 2023, 6:45 PM UTC (5c322b1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1271/922dce6...5c322b1.html" title="Last updated on Nov 14, …
=> Warn authors that usage of global JSON-LD keywords might harm interoperability

index.html
This PR attempts to address issue #1300 by creating new conformance classes for "conforming issuer processors" and "conforming verifier processors". I expect we'll need to fine tune the language before this PR can be merged.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1336.html" title="Last updated on Nov 15, 2023, 8:55 PM UTC (7a68810)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1336/998a3dc...7a68810.html" title="Last updated on Nov 15, 2023, 8:55 PM UTC (7a68810)">Diff</a>
=> Add conformance classes for issuers and verifiers.

index.html
This PR seeks to address https://github.com/w3c/vc-data-model/issues/1335 by presenting how authors may provide a default language and direction using standard JSON-LD language affordances.
***
<a href="https://pr-preview.s3.amazonaws.com/BigBlueHat/vc-data-model/pull/1339.html" title="Last updated on Nov 17, 2023, 2:43 PM UTC (b9d9115)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1339/998a3dc...BigBlueHat:b9d9115.html" title="Last updated on Nov 17, 2023, 2:43 PM UTC (b9d9115)">Diff</a>
=> Explain default language expression.

index.html
This PR has been raised to address issue #1341 by clarifying the normative statements around the `credentialSubject` property.
/cc @jyasskin
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1346.html" title="Last updated on Nov 17, 2023, 2:53 PM UTC (5f82324)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1346/998a3dc...5f82324.html" title="Last updated on Nov 17, 2023, 2:53 PM UTC (5f82324)">Diff</a>
=> Clarify credentialSubject requirements to improve testability.

index.html
This PR attempts to address issue #1343 by clarifying the normative statement related to timezone offsets.
/cc @jyasskin
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1344.html" title="Last updated on Nov 12, 2023, 10:42 PM UTC (3cb0665)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1344/998a3dc...3cb0665.html" title="Last updated on Nov 12, 2023, 10:42 PM UTC (3cb0665)">Diff</a>
=> Clarify normative statement related to timezone offsets.

index.html
This PR uses the non-aliased values for `@language`, `@direction`, and `@value` to prevent confusion that these aliased terms may be used anywhere for any purpose--instead highlighting their sole application for providing language metadata for a single string value.
***
<a href="https://pr-preview.s3.amazonaws.com/BigBlueHat/vc-data-model/pull/1340.html" title="Last updated on Nov 20, 2023, 2:37 PM UTC (6c008dc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1340/3fb62f8...BigBlueHat:6c008dc.html" title="Last updated on Nov 20, 2023, 2:37 PM UTC (6c008dc)">Diff</a>
=> Use JSON-LD keywords for languages.

index.html
This PR attempts to address issue #1342 by clarifying the normative language related to the issuer value. 
/cc @jyasskin
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1349.html" title="Last updated on Nov 25, 2023, 11:44 PM UTC (ccb65a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1349/998a3dc...ccb65a7.html" title="Last updated on Nov 25, 2023, 11:44 PM UTC (ccb65a7)">Diff</a>
=> Update normative language related to issuer value.

index.html
This PR attempts to address issue #1290 by applying the result of the VCWG poll to rename the section to "Credential-type-specific Processing". Here are the results of the poll:
It also updates the language in an attempt to eliminate the use of "JSON Processing" and replace it with something that the VCWG, and @awoie -- specifically, will hopefully find more palatable.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1351.html" title="Last updated on Nov 19, 2023, 2:50 PM UTC (01a8f0a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1351/da600f9...01a8f0a.html" title="Last updated on Nov 19, 2023, 2:50 PM UTC (01a8f0a)">Diff</a>
=> Update JSON Processing section to Credential-Type-Specific Processing.

index.html
Rereading made me aware that some important words were omitted. I believe this to be editorial and clarification. Hopefully other readers will concur.
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-data-model/pull/1353.html" title="Last updated on Nov 18, 2023, 12:33 AM UTC (f66a9aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1353/b3cff22...TallTed:f66a9aa.html" title="Last updated on Nov 18, 2023, 12:33 AM UTC (f66a9aa)">Diff</a>
=> Massaging text for default language and direction

index.html
This PR attempts to address issue #1244 (submitted by @kdenhartog) to ensure that the specification comments on privacy considerations related to metadata-based correlation. I took @kdenhartog's original text and modified it to use more accessible prose, and refer to sections and terminology used by the specification.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1355.html" title="Last updated on Nov 25, 2023, 11:51 PM UTC (3f37139)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1355/b3cff22...3f37139.html" title="Last updated on Nov 25, 2023, 11:51 PM UTC (3f37139)">Diff</a>
=> Add section on metadata-based correlation.

index.html
This PR attempts to address issue #1247 by adding a section on Data Theft, and advising all roles to be careful how much data they store and how long they store it. Advice is given to regulators to play an active role in reducing the collection of PII.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1356.html" title="Last updated on Nov 21, 2023, 3:05 PM UTC (ad252fb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1356/b3cff22...ad252fb.html" title="Last updated on Nov 21, 2023, 3:05 PM UTC (ad252fb)">Diff</a>
=> Add section on Data Theft to Privacy Considerations.

common.js, index.html
This PR attempts to address issue #1347 by making modifications to the specification based on @jyasskin's [review](https://github.com/w3c/vc-data-model/issues/1285):
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1357.html" title="Last updated on Nov 30, 2023, 2:41 PM UTC (90fb40d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1357/53450e9...90fb40d.html" title="Last updated on Nov 30, 2023, 2:41 PM UTC (90fb40d)">Diff</a>
=> Address @jyasskin's pre-Candidate Recommendation review comments

vocab/credentials/v2/vocabulary.yml
The changes are handling the discussion in issue #1319
=> Remove unnecessary vocab comments in vocabulary.yml

index.html
This PR attempts to address issue #1337 by adding a verification algorithm to the specification. The PR attempts to do this in a way that defers to the securing specifications on verifying the securing mechanism and defers to the rest of the normative statements in the specification (instead of re-stating them in the algorithm).
/cc @jyasskin (since he raised this issue as a major item of concern in his review)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1338.html" title="Last updated on Dec 7, 2023, 11:18 PM UTC (6041145)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1338/fcf867c...6041145.html" title="Last updated on Dec 7, 2023, 11:18 PM UTC (6041145)">Diff</a>
=> Add verification algorithm to specification.

contexts/credentials/v2, index.html, vocab/credentials/v2/vocabulary.yml
This PR attempts to address issue #1352 by adding a new feature for embedding "enveloped" Verifiable Credentials in Verifiable Presentations. This PR integrates @iherman's PR #1372.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1379.html" title="Last updated on Dec 15, 2023, 5:23 PM UTC (3884d4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1379/40be9e0...3884d4e.html" title="Last updated on Dec 15, 2023, 5:23 PM UTC (3884d4e)">Diff</a>
=> Add support for Enveloped Verifiable Credentials (2nd attempt)

index.html
This PR attempts to address issue #1375 by removing the document conformance checking algorithm section, clarifying the definition of "document conformance", and then using the updated definition to reduce the (arguably) repeated conformance language.
/cc @jyasskin
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1381.html" title="Last updated on Dec 17, 2023, 2:09 AM UTC (a515e6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1381/40be9e0...a515e6f.html" title="Last updated on Dec 17, 2023, 2:09 AM UTC (a515e6f)">Diff</a>
=> Remove document conformance checking algorithm section

index.html
This PR addresses issue #1363 by ensuring that the use of media type parameters will result in a verification failure.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1382.html" title="Last updated on Dec 17, 2023, 2:13 AM UTC (ed30f01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1382/40be9e0...ed30f01.html" title="Last updated on Dec 17, 2023, 2:13 AM UTC (ed30f01)">Diff</a>
=> Remove mentions to media type parameters

index.html
This PR attempts to address issue #1378 by normatively referring to INFRA in the algorithms section as well as using data types defined in INFRA.
/cc @jyasskin
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1383.html" title="Last updated on Dec 17, 2023, 2:27 AM UTC (ec10cca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1383/09fce9b...ec10cca.html" title="Last updated on Dec 17, 2023, 2:27 AM UTC (ec10cca)">Diff</a>
=> Add normative references to INFRA in algorithms

vocab/credentials/v2/template.html, vocab/credentials/v2/vocabulary.drawio, vocab/credentials/v2/vocabulary.svg, vocab/credentials/v2/vocabulary.yml
This PR completes #1379 (which has been merged) in adding the `EnvelopedVerifiableCredential` type to the vocabulary diagram.
Additionally, a minor change is in the vocabulary file itself: instead using a local reference entry to the VCDM spec, it now uses the "official" reference to ensure an up-to-date entry.
Because the preview does not properly handle inputs, etc, I will add a copy of the new SVG diagram into my comment below.
This is an editorial change, and not overly important at that, so I did not mark this PR as pre-CR. For consistency's sake it would be better to merge it, though.
=> Updating the vocab diagram

index.html
This PR attempts to address issue #1365 by clarifying that non-object values are not allowed for Verifiable Credential Graphs.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1390.html" title="Last updated on Dec 21, 2023, 6:13 PM UTC (3356cbd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1390/edcbf7e...3356cbd.html" title="Last updated on Dec 21, 2023, 6:13 PM UTC (3356cbd)">Diff</a>
=> Clarify that non-objects aren't allowed as VC graphs.

contexts/credentials/v2
The current specification notes that whether or not to allow `digestSRI`, `digestMultibase`, or both [will be determined during the Candidate Recommendation phase](https://w3c.github.io/vc-data-model/#integrity-of-related-resources). However, the current context only includes `digestSRI`. This PR adds `digestMultibase` to the base context such that a comparison between the two mechanisms can be made during the CR period.
=> Add missing digestMultibase value in base context.

index.html
This PR is an attempt to partially address the "before-CR" concerns raised in issue #1316. It makes the following changes to the specification:
1. Separates the "Securing Mechanisms" section from the "Proofs" extension point section.
2. Clarifies that the `proof` property is an extension point that is not specific to Data Integrity. It just so happens that Data Integrity utilizes the extension point, but that doesn't preclude non-Data Integrity approaches from using the same extension point.
3. Removes duplicated normative statements between the Securing Mechanisms section and the Conformance section. There was some hand-wavy content around securing mechanisms that we had in v1.1 because securing mechanisms weren't as strongly defined as they are now in v2.0.
4. Cleans up the text from an …
=> Clarify that "proof" is an extension point

index.html
This PR is an attempt to address issue #1386 by clarifying how issuer validation could occur. It establishes an interface between the VCDM and securing specifications for the securing mechanism verification algorithms. It also adds more detail to the issuer validation section in the specification.
NOTE: The algorithms haven't been updated to use the new interface (that will be done in a separate PR). What's important in this PR is that the controller and controller document is being returned by the securing mechanism verification algorithm such that a check between the `issuer` property and the `controller` is possible.
/cc @jyasskin (this PR starts to define the interface between the Securing Mechanisms and the VCDM)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/ …
=> Clarify how issuer validation occurs.

index.html
This PR attempts to address issue #1377 by normatively defining and then using the new Securing Mechanism Verify Proof interface. The new interface has resulted in a significant reduction in complexity and steps in the algorithms.
/cc @jyasskin
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1394.html" title="Last updated on Dec 26, 2023, 4:33 PM UTC (49abccd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1394/8d81752...49abccd.html" title="Last updated on Dec 26, 2023, 4:33 PM UTC (49abccd)">Diff</a>
=> Use new Securing Mechanism Verify Proof interface

index.html
This PR renames the "Controller Document" terminology to "Entity Document" because the language for "controller documents" is getting increasingly confusing to use and reason about in this specification (and others, for reasons elaborated on below). 
ActivityPub also uses the concept of a "Controller Document", but calls them "Actor objects". This is an important consideration because, with the announcement of new implementers for ActivityPub -- that is, Threads (141 million users) and Flipboard (145 million users), it's important that we get the naming here right (such that it's easier to reason about the alignment in the future).
Here's how this language change is intended to play out:
* "Entity Documents" describe an entity (a thing with independent existence). 
* The description of an …
=> Rename "Controller Document" to "Entity Document".

index.html
This PR is an attempt at addressing issue #1398, which requests that the credential status `id` field is made optional.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1401.html" title="Last updated on Dec 26, 2023, 6:39 PM UTC (f1cd5c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1401/6de9b4c...f1cd5c4.html" title="Last updated on Dec 26, 2023, 6:39 PM UTC (f1cd5c4)">Diff</a>
=> Refine status language and make credential status `id` optional.

index.html
This PR is an attempt to address issue https://github.com/w3c/vc-bitstring-status-list/issues/9 by registering a RANGE_ERROR value in the vc-data-model specification, which is used in the vc-bitstring-status-list specification.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1405.html" title="Last updated on Dec 28, 2023, 4:15 PM UTC (0cb48a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1405/b59c955...0cb48a6.html" title="Last updated on Dec 28, 2023, 4:15 PM UTC (0cb48a6)">Diff</a>
=> Add RANGE_ERROR to list of potential errors.

contexts/credentials/v2, index.html
This PR updates the base context to include the latest BitstringStatusList context updates made in PR https://github.com/w3c/vc-bitstring-status-list/pull/109.
=> Update context to include latest BitstringStatusList changes.

index.html
The "`" characters in the I18N examples seem to be unnecessary and yield erroneous JSON-LD...
Also reported in #1417.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1422.html" title="Last updated on Jan 30, 2024, 2:22 PM UTC (54e9c5a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1422/8cc968a...54e9c5a.html" title="Last updated on Jan 30, 2024, 2:22 PM UTC (54e9c5a)">Diff</a>
=> Unnecessary "`" signs in i18n examples

index.html
This PR is an attempt to jointly cover issues #1217 and #1210, by a thorough re-write of [§5.3.1](https://www.w3.org/TR/vc-data-model-2.0/#semantic-interoperability) on Semantic Interoperability.
This is a normative section, ie, special attention should be given to the usage of the _MUST_, _SHOULD_, etc, keywords. My general approach was to reduce the _MUST_ to the strict minimum, but reviewers might differ.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1420.html" title="Last updated on Feb 10, 2024, 8:35 PM UTC (3f5c4d6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1420/8cc968a...3f5c4d6.html" title="Last updated on Feb 10, 2024, 8:35 PM UTC (3f5c4d6)">Diff</a>
=> Updated section on semantic interoperability (issues #1217 and #1210)

VCDMExplainer.md, contexts/credentials/v2, vocab/credentials/credentials.html, vocab/credentials/credentials.jsonld, vocab/credentials/credentials.ttl, vocab/credentials/template.html, vocab/credentials/vocab.csv
- It looks like `JsonSchema` and `JsonSchemaCredentials` ids are typos and should use the same id prefix as everything else.
- `VCDMExplainer.md` is old, but might as well use the correct URLs.
- The `vocab/credentials/*` files are older, and now not used at that endpoint in favor of `.../v2/` files (I think).  Seems worth fixing those files too in case people look at them.  Or perhaps they should be removed?
- The `sec` prefix update appears to be a typo.  Also in old files and appears unused.
=> Fix URL prefixes.

index.html
This PR attempts to address issue #981 by updating the refresh service example to use the one deployed by TruAge (defined by the[ CCG specification](https://w3c-ccg.github.io/vc-refresh-2021/#verifiablecredentialrefreshservice2021-protocol)).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1435.html" title="Last updated on Feb 18, 2024, 7:28 PM UTC (1dff5c2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1435/d42fd22...1dff5c2.html" title="Last updated on Feb 18, 2024, 7:28 PM UTC (1dff5c2)">Diff</a>
=> Update refresh service example to use example from CCG spec.

vocab/credentials/v2/template.html, vocab/credentials/v2/vocabulary.yml
yml2vocab has now the ability of adding information on designated `@context` files that contain individual terms to the output. This change is adapted to this vocabulary.
No changes on the vocabulary content itself.
As usual, the automatic preview is useless for this case, see https://w3c.github.io/yml2vocab/previews/vcdm/ for the new versions of the generated files.
=> Update vocabulary and template files

index.html
In [§B.2](Implementations that depend on RDF vocabulary processing) the SHA3-512 values did not display correctly; the values were not rendered as a `<code>`. This PR removes the `<wbr>` tag which seems to have created problems in the respec->html conversion.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1443.html" title="Last updated on Feb 22, 2024, 8:51 AM UTC (e56dfaa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1443/d42fd22...e56dfaa.html" title="Last updated on Feb 22, 2024, 8:51 AM UTC (e56dfaa)">Diff</a>
=> Proper rendering of sha-512 values

index.html
fixes #1402
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-data-model/pull/1438.html" title="Last updated on Feb 14, 2024, 9:08 PM UTC (08db69b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1438/d42fd22...TallTed:08db69b.html" title="Last updated on Feb 14, 2024, 9:08 PM UTC (08db69b)">Diff</a>
=> clarify inputBytes, inputDocument, inputMediaType

diagrams/ecosystemdetail.drawio, diagrams/ecosystemdetail.svg, diagrams/vc-graph.drawio, index.html
This is to handle #1331.
The usual preview is useless in this case; to review, you should look at the SVG file directly, see [svg link](https://raw.githack.com/w3c/vc-data-model/validation-on-diagram/diagrams/ecosystemdetail.svg).
- I completely re-did the diagram from scratch, because I do not know where the old source is (and I did not want to mess around with the SVG file itself). Also, the old diagram did not work with dark mode; hopefully this does (I tested it with Brave with Dark Mode switched on, and it looks o.k. there. @dlongley, you should have a look). This is also the reason why the diagram is less "colorful".
- Also, I removed the big title ("Life of a single Verifiable Credential") and I put this into the caption instead.
I am not sure what the 'semantics' of dotted lines …
=> Added the "Validate" action to the life cycle details diagram (issue 1331)

index.html
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 28, 2024, 4:07 PM UTC)_.
<details>
:link: [Related URL]([object Object])
```
Navigation timeout of 29493 ms exceeded
```
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/vc-data-model%231448.)._ …
=> Add note about `@direction` on JSON-LD literals

index.html
removed "more formally defined"
***
<a href="https://pr-preview.s3.amazonaws.com/David-Chadwick/vc-data-model/pull/1447.html" title="Last updated on Mar 3, 2024, 7:57 PM UTC (7ab710d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1447/3a0007b...David-Chadwick:7ab710d.html" title="Last updated on Mar 3, 2024, 7:57 PM UTC (7ab710d)">Diff</a>
=> extension point clarification

index.html
This PR is an attempt to address issue #1192 by adding text warning that the use of English in descriptions is illustrative.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1449.html" title="Last updated on Mar 3, 2024, 9:18 PM UTC (77190d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1449/64cf5b1...77190d3.html" title="Last updated on Mar 3, 2024, 9:18 PM UTC (77190d3)">Diff</a>
=> Add warning about English descriptions being illustrative.

index.html
This PR is an attempt to address issue #1291 by specifying that a credential can have more than one status entry.
/cc @bruno-zimmermann-bit
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1450.html" title="Last updated on Mar 9, 2024, 4:04 PM UTC (6ee3131)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1450/64cf5b1...6ee3131.html" title="Last updated on Mar 9, 2024, 4:04 PM UTC (6ee3131)">Diff</a>
=> Clarify that credential status can have multiple entries.

index.html
This PR is an attempt to address issue #1388 by documenting that a verifier is expected to perform input validation based on the requirements of a specific type of credential and might ignore claims that it does not understand.
/cc @jyasskin
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1451.html" title="Last updated on Mar 9, 2024, 4:09 PM UTC (5cf1016)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1451/64cf5b1...5cf1016.html" title="Last updated on Mar 9, 2024, 4:09 PM UTC (5cf1016)">Diff</a>
=> Add language related to validation expectations.

index.html
This PR is an attempt to address issue #1274 by removing the note on verification methods (since we now have a spec that defines those) and refactors the validation section to use more modern language.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1452.html" title="Last updated on Mar 9, 2024, 4:23 PM UTC (286ce7c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1452/64cf5b1...286ce7c.html" title="Last updated on Mar 9, 2024, 4:23 PM UTC (286ce7c)">Diff</a>
=> Remove note on verification methods; refactor proof validation section.

index.html, vocab/credentials/v2/vocabulary.drawio, vocab/credentials/v2/vocabulary.svg, vocab/credentials/v2/vocabulary.yml
This PR is an attempt to address issue #1431 by adding a way of expressing an enveloped verifiable presentation.
/cc @christophera
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1453.html" title="Last updated on Mar 9, 2024, 4:40 PM UTC (2cf9040)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1453/64cf5b1...2cf9040.html" title="Last updated on Mar 9, 2024, 4:40 PM UTC (2cf9040)">Diff</a>
=> Add section on enveloped verifiable presentations.

index.html
This is to handle #1442. It makes it clearer that all references are on JSON-LD.
Two notes for the future:
- If this PR is accepted and merged, a similar change should be done for the [DI spec's corresponding tables](https://www.w3.org/TR/vc-data-integrity/#contexts-and-vocabularies) for consistency (including the typesetting style for the hash values).
- _When going to Proposed REC_, the URL for the JSON-LD versions _must_ be changed in the text to use the final URL on W3C Date Space.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1454.html" title="Last updated on Mar 13, 2024, 7:21 AM UTC (3912181)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1454/64cf5b1...3912181.html" title="Last updated on Mar 13, 2024, 7:21 AM UTC …
=> Updating the text on vocabulary hashes

diagrams/claim-example-2.drawio, diagrams/claim-example-2.svg, diagrams/claim-example.drawio, diagrams/claim-example.svg, diagrams/claim-extended.drawio, diagrams/claim-extended.svg, diagrams/claim.drawio, diagrams/claim.svg, diagrams/ecosystem.drawio, diagrams/ecosystem.svg, diagrams/presentation.drawio, diagrams/presentation.svg, diagrams/privacy-spectrum.svg, diagrams/vc.drawio, diagrams/vc.svg, diagrams/zkp-cred-pres.drawio, diagrams/zkp-cred-pres.svg, index.html
I have re-created the older diagrams with two goals in mind:
- Have some consistency in the "visual language" of the older and newer diagrams (@davidlehn, this was one of your remarks in an older PR)
- All diagrams are now (I hope) dark-mode ready
What dark-mode readiness means:
- Diagrams have a transparent background
- The interior of the various figures (ellipses, rectangles, etc.) are "no-fill", i.e., they are all transparent
- Be careful about colors, because dark mode may mean transforming them into other colors
I have made _no_ change on the diagrams' content. Please, if you review this PR, do _not_ ask here to make a content change on the diagrams; raise a separate issue and I will be happy to take care of it in a separate PR.
All diagrams, except one, are edited using the drawio …
=> (Editorial) Created a new version for several diagrams 

index.html
Although the [WG discussion](https://github.com/w3c/vc-data-model/issues/1455#issuecomment-1994834278) on #1455 did not formally conclude (due to a lack of meeting time), I have the feeling that we were heading for a consensus to remove the sha3 hashes from the vocabulary table. This PR just does that.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1459.html" title="Last updated on Mar 23, 2024, 10:10 PM UTC (c94a4b8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1459/9db6fe3...c94a4b8.html" title="Last updated on Mar 23, 2024, 10:10 PM UTC (c94a4b8)">Diff</a>
=> Removing sha3 reference from the vocabulary table.

index.html
I fixed some of tags are not matching.
It closes #1460
***
<a href="https://pr-preview.s3.amazonaws.com/lukasjhan/vc-data-model/pull/1461.html" title="Last updated on Mar 21, 2024, 12:35 AM UTC (5853699)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1461/fc22559...lukasjhan:5853699.html" title="Last updated on Mar 21, 2024, 12:35 AM UTC (5853699)">Diff</a>
=> fix: unmatch tags

index.html
This PR is an attempt to address issue #1254 by moving the "Complex Markup" section into the "Security Considerations" section and warning about code injection attacks.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1463.html" title="Last updated on Apr 2, 2024, 1:33 PM UTC (ca5efaa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1463/a80301d...ca5efaa.html" title="Last updated on Apr 2, 2024, 1:33 PM UTC (ca5efaa)">Diff</a>
=> Move section on code injection to security considerations.

index.html
"Long-Lived Identifier-Based Correlation" (or "Long-Lived Correlation Based on Identifiers") is very different from "Long-Lived-Identifier-Based Correlation" (or "Correlation Based on Long-Lived Identifiers").
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-data-model/pull/1473.html" title="Last updated on Apr 8, 2024, 11:06 PM UTC (9260dda)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1473/1ab385f...TallTed:9260dda.html" title="Last updated on Apr 8, 2024, 11:06 PM UTC (9260dda)">Diff</a>
=> add lost hyphen

index.html
I didn't change the section title, but the "Trust Model" is no longer based on "Trust", but on "Expectations". I think this is more in line with our discussions, and on what the technology handles.
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-data-model/pull/1474.html" title="Last updated on Apr 16, 2024, 2:41 PM UTC (9c83d89)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1474/1ab385f...TallTed:9c83d89.html" title="Last updated on Apr 16, 2024, 2:41 PM UTC (9c83d89)">Diff</a>
=> Massage "Trust Model" into "Expectations"

index.html
This PR is an attempt to address issue #1348 by fixing a large number of editorial concerns that @jyasskin raised. 
Specifically:
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1464.html" title="Last updated on May 5, 2024, 3:01 PM UTC (150bfbb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1464/1153f74...150bfbb.html" title="Last updated on May 5, 2024, 3:01 PM UTC (150bfbb)">Diff</a>
=> Address Jeffrey Yasskin's review comments that are Editorial

index.html
This PR is an attempt to partially address issue #1348 by reworking the content integrity section in the specification based on feedback from @jyasskin. 
NOTE: It contains content that was objected to by @selfissued in PR #1464 and is, thus, not mergeable in its current state. This PR will be used to drive the discussion and come to consensus on what can be merged by consensus of the group.
Specifically:
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1484.html" title="Last updated on May 27, 2024, 6:57 PM UTC (cc8b0e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1484/b11eec7...cc8b0e3.html" title="Last updated on May 27, 2024, 6:57 PM UTC (cc8b0e3)">Diff</a>
=> Rework content integrity section based on @jyasskin's feedback.

index.html
This PR is an attempt to address issue #1489 by allowing either `digestSRI` and/or `digestMultibase` to be used.
At this point, some WG Members have raised objections for [Option A](https://github.com/w3c/vc-data-model/issues/1489#issuecomment-2134164168) and [Option B](https://github.com/w3c/vc-data-model/issues/1489#issuecomment-2134164168). 
This PR implements [Option C](https://github.com/w3c/vc-data-model/issues/1489#issuecomment-2134164168).
If some subset of the WG objects to Option C, then we will need to determine which option will draw the least number of Formal Objections, pick one, and move on. Another option is to remove the feature from the specification entirely.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1492.html" title="Last updated on Jun 9, …
=> Support two different digest formats for resource integrity.

index.html
This PR removes an issue marker noting that the WG is debating mandatory resource integrity entries for JSON-LD Context files. 
It is highly unlikely that the WG will come to consensus on making the use of `resourceIntegrity` for expressing digest values for JSON-LD Contexts mandatory because 1) there are other mechanisms to do so, 2) it creates complexities for selective disclosure, 3) it's unnecessary when using alternative integrity mechanisms (like static application contexts, known good hashes, hashlinks, etc.).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1493.html" title="Last updated on Jun 1, 2024, 7:30 PM UTC (6667695)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1493/5abaeed...6667695.html" title="Last updated on Jun …
=> Remove issue marker for mandatory use of `resourceIntegrity` for contexts.

index.html
This PR removes an issue marker that requested feedback from implementers on whether or not the WG should elaborate on what we mean by "determining". The WG has not received feedback from implementers stating that we need to define what "determining" means and we have multiple interoperable implementations that perform verification. Therefore, this PR removes the issue marker.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1494.html" title="Last updated on Jun 1, 2024, 7:48 PM UTC (b3bf905)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1494/5abaeed...b3bf905.html" title="Last updated on Jun 1, 2024, 7:48 PM UTC (b3bf905)">Diff</a>
=> Remove issue marker for "determining" language.

index.html
This PR upgrades the specification to auto-generate the cryptographic digests for context and vocabulary files so that we no longer have to worry about the cryptographic digests getting out of sync with updates to the various documents. The digests have been updated to align with openssl digest output to make it easier for developers to verify the digests using common tooling available to them.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1499.html" title="Last updated on Jun 2, 2024, 6:55 PM UTC (6959f9f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1499/a3cdff1...6959f9f.html" title="Last updated on Jun 2, 2024, 6:55 PM UTC (6959f9f)">Diff</a>
=> Auto-generate context and vocabulary digests.

index.html
This PR is an attempt to address issue #1462 by setting the media types to something that would be uncontroversial from an IANA Media Types perspective. This PR changes the media type for a VC to "application/vc", and the media type for a VP to "application/vp".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1478.html" title="Last updated on Jun 14, 2024, 2:44 PM UTC (5d9b9b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1478/952ff1b...5d9b9b5.html" title="Last updated on Jun 14, 2024, 2:44 PM UTC (5d9b9b5)">Diff</a>
=> Update media types to `application/vc` and `application/vp`

index.html
This PR is an attempt to address issue #1481 by adding a reference to the JAdES standard in the Ecosystem Compatability section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1501.html" title="Last updated on Jun 9, 2024, 2:55 PM UTC (9a4ab65)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1501/171590d...9a4ab65.html" title="Last updated on Jun 9, 2024, 2:55 PM UTC (9a4ab65)">Diff</a>
=> Add reference to JAdES standard in Ecosystem Compatability.

index.html
This PR is an attempt to address issue #1502 by adding a few more privacy considerations related to legal processes and coercion.
/cc @zoracon
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1504.html" title="Last updated on Jun 26, 2024, 11:16 PM UTC (7072c8c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1504/0a82f17...7072c8c.html" title="Last updated on Jun 26, 2024, 11:16 PM UTC (7072c8c)">Diff</a>
=> Add privacy considerations related to legal processes and coercion

contexts/credentials/v2
This PR is an attempt to address issue #1503 by ensuring that the `_sd` property's JSON values remain as JSON.
I did check the `_sd_alg` and `...` properties and both are always string values (so didn't use the `@json` type for those).
=> Added `@json` type to `_sd` property in v2 context.

contexts/credentials/v2
- Use correct URL host as defined and used elsewhere.
- This change was previously made and reverted by mistake.
- Original fix: https://github.com/w3c/vc-data-model/pull/1427
- A bad merge commit reverted part of one line: https://github.com/w3c/vc-data-model/pull/1428
- Fix another indent style issue.
=> Fix `jsonSchema` context URL.

index.html
The old link target doesn't actually contain an interface for securing mechanisms.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/vc-data-model/pull/1516.html" title="Last updated on Jul 1, 2024, 4:30 PM UTC (a7d89e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1516/5dd94d3...jyasskin:a7d89e7.html" title="Last updated on Jul 1, 2024, 4:30 PM UTC (a7d89e7)">Diff</a>
=> Fix link to section containing the securing mechanism interface.

contexts/credentials/v2
The v2 context has been written and updated by hand over time and some of the ordering and formatting was not following a strict pattern.  This attempts to clean it up to be easier to read.  The format here is somewhat arbitrary, and other formats are possible, but this seems easy to work with.  This organization was done by hand.
- Opinionated but consistent organization and sorting.
- Semantically equivalent to data in previous style.
- Order is recursive and roughly follows a pattern:
- JSON-LD keywords
- blank line
- id/type terms
- blank line
- jose/jwt property terms
- sorted
- blank line
- other property terms
- sorted
- blank line
- type terms
- sorted
- for TypeCredential/Type pairs, put TypeCredential first
- blank line between each
- Drop down and indent values to try and be …
=> Organize v2 context.

contexts/credentials/v2
This PR is an attempt to address issue #1506 by adding `renderMethod` to the list of reserved terms in the v2 context. Not having done this to date has been an oversight. I also made a pass through all other reserved terms and ensured that they have entries in the v2 context.
=> Add `renderMethod` to reserved terms in context.

index.html
This PR is an attempt to address issue #1518 by unifying the input value to cryptosuite verification algorithms.
/cc @jyasskin @PatStLouis @filip @silverpill @flechtner
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1523.html" title="Last updated on Jul 8, 2024, 3:26 PM UTC (5651b77)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1523/8e9ae4e...5651b77.html" title="Last updated on Jul 8, 2024, 3:26 PM UTC (5651b77)">Diff</a>
=> Unify input value to verification algorithm.

index.html
This PR is a partial attempt to address issue #1514 by warning about the usage of `@vocab`, including guidance on when it might be acceptable to use it.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1524.html" title="Last updated on Jul 15, 2024, 2:29 PM UTC (c4d3da3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1524/8e9ae4e...c4d3da3.html" title="Last updated on Jul 15, 2024, 2:29 PM UTC (c4d3da3)">Diff</a>
=> Add warnings related to `@vocab` usage

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1528.html" title="Last updated on Jul 9, 2024, 8:36 PM UTC (a7069a9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1528/2e71d8e...a7069a9.html" title="Last updated on Jul 9, 2024, 8:36 PM UTC (a7069a9)">Diff</a>
=> make incorrect plurals singular

index.html
This PR is an attempt to partially address issue #1437 by removing the at risk issue marker for the `evidence` property.
There are [three registered specifications](https://w3c.github.io/vc-specs-dir/#evidence) in the VC Specifications Directory that use the extension point. Additionally, the IMS Global Open Badges v3.0 specification, which was just ratified (requires multiple implementations) as a Final specification on May 27th, uses the extension point.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1496.html" title="Last updated on Jun 1, 2024, 9:54 PM UTC (740fa35)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1496/d336391...740fa35.html" title="Last updated on Jun 1, 2024, 9:54 PM UTC (740fa35)">Diff</a>
=> Remove at risk marker for `evidence` property

index.html
This PR is an attempt to partially address issue #1437 by removing the at risk issue marker for the `refreshService` property.
There are [two registered specifications](https://w3c.github.io/vc-specs-dir/#refresh-service) in the VC Specifications Directory that use the extension point. The 1EdTech VC Refresh v1.0 specification uses the extension point. The Conexxus Age Verification v1.0 standard uses the extension point, which has been implemented by (at least) Spruce (California DMV), TruAge, and Digital Bazaar.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1497.html" title="Last updated on Jul 17, 2024, 8:24 PM UTC (45f87c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1497/b29c107...45f87c3.html" title="Last updated on Jul 17, …
=> Remove at risk marker for `refreshService` property.

contexts/credentials/v2, index.html
This PR is a partial attempt to address issue #1514 by removing `@vocab` from the base context because we no longer have WG support for this specific usage of the feature. 
Other forthcoming PRs will provide new guidance on when and how to use `@vocab` safely.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1520.html" title="Last updated on Jul 17, 2024, 8:47 PM UTC (e6868e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1520/97f7b90...e6868e8.html" title="Last updated on Jul 17, 2024, 8:47 PM UTC (e6868e8)">Diff</a>
=> Remove `@vocab` from the base context.

index.html
This PR is an attempt to address issue #1517 by clarifying the language around input types to verification algorithms.
/cc @jyasskin @PatStLouis @filip @silverpill @flechtner
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1522.html" title="Last updated on Jul 21, 2024, 7:55 PM UTC (c90b313)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1522/ccbe460...c90b313.html" title="Last updated on Jul 21, 2024, 7:55 PM UTC (c90b313)">Diff</a>
=> Clarify input type of verification algorithms.

index.html
`refreshServicce` and `credentialSchema` were missing.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1530.html" title="Last updated on Jul 17, 2024, 9:01 PM UTC (9e907fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1530/97f7b90...9e907fc.html" title="Last updated on Jul 17, 2024, 9:01 PM UTC (9e907fc)">Diff</a>
=> Add required type fields table.

index.html
This PR is a partial fix for an issue raised in https://github.com/w3c/vc-data-integrity/issues/272 by noting that specification authors may require that JSON-LD Contexts are integrity protected by using the `relatedResource` feature.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1537.html" title="Last updated on Aug 5, 2024, 7:50 PM UTC (88dd37b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1537/85de74e...88dd37b.html" title="Last updated on Aug 5, 2024, 7:50 PM UTC (88dd37b)">Diff</a>
=> Note that integrity protecting JSON-LD Contexts are allowed.

index.html
Makes this definition closer to termsOfUse and other similar properties.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1544.html" title="Last updated on Aug 14, 2024, 6:34 PM UTC (f9ab0d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1544/4c6005d...f9ab0d7.html" title="Last updated on Aug 14, 2024, 6:34 PM UTC (f9ab0d7)">Diff</a>
=> Add normative MUST to evidence property.

index.html
A media type does not itself serialize, but rather identifies or
signals a serialization.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1545.html" title="Last updated on Aug 16, 2024, 4:02 PM UTC (95a6087)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1545/4c6005d...95a6087.html" title="Last updated on Aug 16, 2024, 4:02 PM UTC (95a6087)">Diff</a>
=> Tweak media type conformance line.

.gitignore, README.md, index.html, terms.html
Proof reads for Section 8
Also included @TallTed's changes from #1549
Section 9 coming next
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1554.html" title="Last updated on Sep 15, 2024, 9:38 PM UTC (5c37836)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1554/363a923...5c37836.html" title="Last updated on Sep 15, 2024, 9:38 PM UTC (5c37836)">Diff</a>
=> Proof reading for Section 8 - Privacy

index.html
This PR is an attempt to address issue #1559 by removing integer error codes in the ProblemDetails objects.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1562.html" title="Last updated on Sep 15, 2024, 11:02 PM UTC (a794cc5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1562/ae63dda...a794cc5.html" title="Last updated on Sep 15, 2024, 11:02 PM UTC (a794cc5)">Diff</a>
=> Remove ProblemDetail integer error codes.

index.html
This P.R. addresses issue #1555 
Just checking, I should only be changing the base index.html right? 
Also, as I was going through this I noticed the spec still has 32 uses of the word usage. I believe in the examples.
For example: "Usage of the credentialSubject property"
Should we also be changing these to Use?
***
<a href="https://pr-preview.s3.amazonaws.com/wip-abramson/vc-data-model/pull/1561.html" title="Last updated on Oct 3, 2024, 4:04 PM UTC (d656c37)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1561/062e4b3...wip-abramson:d656c37.html" title="Last updated on Oct 3, 2024, 4:04 PM UTC (d656c37)">Diff</a>
=> Change usage to use throughout spec text

index.html
This PR is an attempt to address https://github.com/w3c/vc-data-integrity/issues/272 by requiring digest verification for related resources.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1567.html" title="Last updated on Oct 14, 2024, 8:41 PM UTC (a565f43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1567/062e4b3...a565f43.html" title="Last updated on Oct 14, 2024, 8:41 PM UTC (a565f43)">Diff</a>
=> Require digest verification for related resources.

index.html
With #1476 the link is updated to the use cases document. 
It would be added to the use cases document by this PR https://github.com/w3c/vc-use-cases/pull/154 but it is now in the overview document. https://github.com/w3c/vc-overview
It would be nice to update this link to the vc overview document.
***
<a href="https://pr-preview.s3.amazonaws.com/ricklambrechts/w3c-vc-data-model/pull/1573.html" title="Last updated on Nov 26, 2024, 7:53 PM UTC (25f84dc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1573/3fbda62...ricklambrechts:25f84dc.html" title="Last updated on Nov 26, 2024, 7:53 PM UTC (25f84dc)">Diff</a>
=> Update lifecycle example link to vc overview

index.html
This example currently seems to be based on VCDM 1.1.
***
<a href="https://pr-preview.s3.amazonaws.com/peacekeeper/vc-data-model/pull/1566.html" title="Last updated on Sep 24, 2024, 3:06 PM UTC (7d241fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1566/fde26dd...peacekeeper:7d241fa.html" title="Last updated on Sep 24, 2024, 3:06 PM UTC (7d241fa)">Diff</a>
=> Update "refreshService" example to VCDM2.0

index.html
The original statement was found to be untestable. This new text provides explanatory text instead.
NOTE: the goal of this change is to avoid this text being "at risk" while keeping the intention of the text.
@jandrieu I believe this was originally your text, so please let us know if you're OK with this change.
Thanks!
🎩
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1580.html" title="Last updated on Jan 14, 2025, 2:22 PM UTC (79ddaf1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1580/a78384a...79ddaf1.html" title="Last updated on Jan 14, 2025, 2:22 PM UTC (79ddaf1)">Diff</a>
=> Reword self-asserted VC in VP text to remove MUST.

schema/verifiable-credential/verifiable-credential-schema.json
A couple of fix to the json schema resource of the VC. Addresses #1577
- remove required `id` property on the credentialStatus object:
this field is optional in the spec (BitstringStatusList)
- remove required `created` property on the proof object:
this is field is optional in the spec (DataIntegrity)
- remove `proofChain` property:
AFAIK this isn't defined anywhere and should be represented by the proof attribute
=> Fix JsonSchema of the Verifiable Credential

schema/verifiable-credential/verifiable-credential-schema.json
While working on a downstream use-case, I noticed that the existing schema checks only that the context *contains* "https://www.w3.org/ns/credentials/v2", while the [v2 spec explicitly says the following regarding context](https://www.w3.org/TR/vc-data-model-2.0/#contexts):
> The value of the @context [property](https://www.w3.org/TR/vc-data-model-2.0/#dfn-property) MUST be an [ordered set](https://infra.spec.whatwg.org/#ordered-set) where the first item is a [URL](https://www.w3.org/TR/vc-data-model-2.0/#dfn-url) with the value https://www.w3.org/ns/credentials/v2.
With that in mind, I think the use of `prefixItems` to ensure that the first item is the expected URL is more accurate.
While there, I also noted that:
> An ordered set is a [list](https://infra.spec.whatwg.org/#list) with the …
=> First item of VC context is a URL with the value https://www.w3.org/ns/credentials/v2

index.html
See discussion in https://github.com/w3c/vc-data-integrity/pull/327 : the handling/reporting of errors should be consistent with the DI and CID specifications.
(See also https://github.com/w3c/cid/pull/140).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1587.html" title="Last updated on Jan 20, 2025, 7:23 AM UTC (167fce0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1587/a18b601...167fce0.html" title="Last updated on Jan 20, 2025, 7:23 AM UTC (167fce0)">Diff</a>
=> Removed the "MUST" for error conditions to be in sync with CID and DI

index.html
Now that CID is published...
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1589.html" title="Last updated on Feb 23, 2025, 1:32 PM UTC (cb5e3ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1589/d007bff...cb5e3ae.html" title="Last updated on Feb 23, 2025, 1:32 PM UTC (cb5e3ae)">Diff</a>
=> Exchanged references to Controller Documents to CIDs

.github/workflows/echidna.yml
[GitHub will no longer support the Ubuntu 20.04 runner image starting from April 1, 2025](https://github.com/actions/runner-images/issues/11101). That PR updates the actions to use ubuntu-latest instead
=> GitHub actions: replace ubuntu-20.04 with ubuntu-latest
