w3c/vc-data-model

- index.html
This PR is meant to add a section on revocation to address issue #34.
> Add section on the Revocation Model.

- index.html
Please review. Addresses issue https://github.com/opencreds/vc-data-model/issues/10.
> Add section on storage providers and data mining.

- index.html
> Expanded section on correlatable usage patterns

- index.html
Please review. This PR addresses issue https://github.com/opencreds/vc-data-model/issues/7.
> Add content to Principle of Minimum Disclosure section.

- index.html
Submitting patch request from David Chadwick on bundling dependent claims. We still need to discuss mitigation strategies.
/cc @David-Chadwick @dlongley @talltree @nage
> Add section on bundling dependent claims.

- index.html
> Add section on frequency of claim issuance.

- index.html
Add a summary for the security considerations section.
> Add security considerations section summary.

- index.html
> Update signature-based correlation section with more bad news.

- index.html
Adds a section on the privacy implications related to the aggregation of claims. Closes #11.
> Add privacy section on aggregation of claims.

- index.html
> Add wrong party sharing to privacy section.

- index.html
Add a section around preferring single use claims when possible. Closes #15.
> Add privacy section on single use claims.

- index.html
In both the JSON and JSON-LD examples.
Also changing indentation of the "signature" block.
> Fix missing closing bracket in verifiable profile

- index.html
> Add security section on unsigned credentials.

- vocab/README.md
- vocab/context.jsonld
- vocab/credentials.html
- vocab/credentials.jsonld
- vocab/credentials.ttl
- vocab/mk_vocab.rb
- vocab/template.html
- vocab/vocab.csv
This simply adds the vocabulary updates described in the F2F at TPAC. Ill file issues on issues raised at TPAC.
Fixes #33.
> Initial commit of vocabulary files.

- common.js
- index.html
Adds support for credential status retrieval, a non-normative Credential Status Method Registry, and a Credential Status List 2017 Method:
https://w3c-ccg.github.io/vc-status-registry/
https://w3c-ccg.github.io/vc-csl2017/
> Replace revocation with status checking.

- index.html
- terms.html
This PR clarifies that credentials and profiles can be multi-subject. Fixes #55.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/121.html" title="Last updated on Apr 2, 2018, 9:14 PM GMT (a09e8b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/121/ea8d840...a09e8b0.html" title="Last updated on Apr 2, 2018, 9:14 PM GMT (a09e8b0)">Diff</a>
> Clarify that credentials and profiles can be multi-subject.

- index.html
Add data retention limit example to address issue raised by @rigow.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/132.html" title="Last updated on Mar 20, 2018, 1:51 PM GMT (e316c18)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/132/805722f...e316c18.html" title="Last updated on Mar 20, 2018, 1:51 PM GMT (e316c18)">Diff</a>
> Add data retention limit example. Fixes #124.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/150.html" title="Last updated on Apr 3, 2018, 8:02 AM GMT (ed60ead)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/150/23bd58b...ed60ead.html" title="Last updated on Apr 3, 2018, 8:02 AM GMT (ed60ead)">Diff</a>
> Add section on device theft and impersonation. Fixes #115.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/151.html" title="Last updated on Apr 16, 2018, 8:46 PM GMT (c2344e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/151/23bd58b...c2344e2.html" title="Last updated on Apr 16, 2018, 8:46 PM GMT (c2344e2)">Diff</a>
> Add a non-normative example of how to embed images. Fixes #97.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/152.html" title="Last updated on Apr 16, 2018, 8:48 PM GMT (a2a8f1a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/152/23bd58b...a2a8f1a.html" title="Last updated on Apr 16, 2018, 8:48 PM GMT (a2a8f1a)">Diff</a>
> Add section for Disputes. Fixes #111.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/154.html" title="Last updated on Apr 16, 2018, 9:11 PM GMT (fec717c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/154/8d1e527...fec717c.html" title="Last updated on Apr 16, 2018, 9:11 PM GMT (fec717c)">Diff</a>
> Change termsOfUse examples based on feedback from @rianella. Fixes #41.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/159.html" title="Last updated on Apr 18, 2018, 9:53 PM GMT (9722e47)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/159/80dadfb...9722e47.html" title="Last updated on Apr 18, 2018, 9:53 PM GMT (9722e47)">Diff</a>
> Add a section on extensibility to the specification.

- README.md
add link to the test case repo in github
> Add link to DM Test Cases

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/172.html" title="Last updated on May 15, 2018, 9:40 PM GMT (0b46b02)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/172/f3f8e01...0b46b02.html" title="Last updated on May 15, 2018, 9:40 PM GMT (0b46b02)">Diff</a>
> Removed MUST and SHOULDs from requirements. Fixes #168.

- index.html
This is an update of #145, which is superceded by this and therefore can be deleted
***
<a href="https://pr-preview.s3.amazonaws.com/David-Chadwick/vc-data-model/pull/176.html" title="Last updated on May 16, 2018, 7:07 PM GMT (f1c77e4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/176/9ea3a8d...David-Chadwick:f1c77e4.html" title="Last updated on May 16, 2018, 7:07 PM GMT (f1c77e4)">Diff</a>
> Improved Credential Status Scheme

- index.html
Fix #149 by changing the purpose of the id property. Specifically, the presentation id was the DID before, and now it is the id of the presentation.
> Fix #149 by changing the purpose of the id property.

- index.html
Migrate to issuanceDate and expirationDate per request by @lovesh, @talltree, @ChristopherA, @lautarodragan, @kennylavender, @geoffturk, and @stonematt. Please review this PR.
> Migrate to issuanceDate and expirationDate. Fixes #184.

- index.html
See if this addresses both of your concerns @lovesh and @dlongley.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/185.html" title="Last updated on Jun 13, 2018, 12:03 AM GMT (a8804e6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/185/ba43ef7...a8804e6.html" title="Last updated on Jun 13, 2018, 12:03 AM GMT (a8804e6)">Diff</a>
> Minor changes to disputed credential data model. Fixes #180.

- index.html
fixes most of issue #201
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/219.html" title="Last updated on Aug 16, 2018, 9:59 PM GMT (a1b9f78)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/219/d7f5dd3...a1b9f78.html" title="Last updated on Aug 16, 2018, 9:59 PM GMT (a1b9f78)">Diff</a>
> Editorial response to issue #201

- README.md
Remove Pearson reference from co-chair Matt Stone and delist Richard Varn as co-chair
> Remove Pearson reference and Varn

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/246.html" title="Last updated on Oct 9, 2018, 2:59 PM GMT (5fd9419)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/246/43f46fb...5fd9419.html" title="Last updated on Oct 9, 2018, 2:59 PM GMT (5fd9419)">Diff</a>
> Add section on Accessibility considerations.

- index.html
Short accessibility impact statement, non-normative, for horizontal review. Has not been vetted by the rest of APA.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/238.html" title="Last updated on Sep 30, 2018, 3:01 PM GMT (fe54b68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/238/d2e6d98...fe54b68.html" title="Last updated on Sep 30, 2018, 3:01 PM GMT (fe54b68)">Diff</a>
> draft accessibility impact statement

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/256.html" title="Last updated on Oct 28, 2018, 2:28 PM GMT (aecb3e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/256/04e1533...aecb3e3.html" title="Last updated on Oct 28, 2018, 2:28 PM GMT (aecb3e3)">Diff</a>
> Add a section on identifiers to address issue #250.

- vocab/examples.jsonld
> Add examples JSON-LD Context file. Fix #245.

- index.html
Part of resolution for Issue #237
> Add privacy paragraph to introduction

- terms.html
Update definition of presentation to call out presenting to a verifier specifically. Fixes issue #240
> Update presentation definition

- index.html
fixes issue #243
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/273.html" title="Last updated on Nov 11, 2018, 4:10 PM GMT (b6a5efd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/273/e5d3380...b6a5efd.html" title="Last updated on Nov 11, 2018, 4:10 PM GMT (b6a5efd)">Diff</a>
> Update Subject paragraph to refer to claim

- index.html
Replaces #227.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/259.html" title="Last updated on Nov 12, 2018, 5:48 PM GMT (ea58b6b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/259/4bcfb99...ea58b6b.html" title="Last updated on Nov 12, 2018, 5:48 PM GMT (ea58b6b)">Diff</a>
> Rebased #227 - David Chadwick's fixes for disputed credentials

- index.html
Mostly grammatical, punctuation, and formatting changes. I began capitalizing the first word in a bullet point but don't know if you have a specific style rule for this or not.
As I always say in my reviews, my suggestions are exactly that. Suggestions. You can accept, all, some, or none of my suggestions. I'm not particulartly precious about them. :smile:
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/285.html" title="Last updated on Nov 16, 2018, 10:13 PM GMT (25fa8d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/285/99b0dc9...grantnoble:25fa8d8.html" title="Last updated on Nov 16, 2018, 10:13 PM GMT (25fa8d8)">Diff</a>
> Grammar/typo/formatting updates for Section 1

- index.html
This PR refers to the threat models detailed in the use cases document and addresses #251.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/278.html" title="Last updated on Nov 15, 2018, 2:31 AM GMT (8c03145)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/278/99b0dc9...8c03145.html" title="Last updated on Nov 15, 2018, 2:31 AM GMT (8c03145)">Diff</a>
> Refer to the threat model in the Use Cases document. Fix #251.

- terms.html
Again, mostly grammar and formatting changes. Added some links. No typos that I can recall. As I said for my previous PR, just suggestions. Accept them all, or just some, or none. All good! 😄
> Grammar and formatting updates to terms.html (section 2 for VC data model)

- index.html
More suggestions for Core Data Model section. I added a fair number anchor tags to link terms.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/287.html" title="Last updated on Nov 21, 2018, 5:26 AM GMT (72765be)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/287/99b0dc9...grantnoble:72765be.html" title="Last updated on Nov 21, 2018, 5:26 AM GMT (72765be)">Diff</a>
> Grammar and formatting suggestions for section 3, Core Data Model

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/288.html" title="Last updated on Nov 22, 2018, 3:34 AM GMT (376fcdd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/288/a318451...grantnoble:376fcdd.html" title="Last updated on Nov 22, 2018, 3:34 AM GMT (376fcdd)">Diff</a>
> Grantnoble section4 grammar typos suggestions

- index.html
This is an attempt to address #241 and some of the ZKP requirements in the specification.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/280.html" title="Last updated on Dec 4, 2018, 3:40 PM GMT (c0f0b67)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/280/99b0dc9...c0f0b67.html" title="Last updated on Dec 4, 2018, 3:40 PM GMT (c0f0b67)">Diff</a>
> Add section on Data Schemas. Related to #241.

- index.html
Again, mostly grammar and formatting suggestions, but please pay special attention to the Object/Type table in section 5.3 Types. I made some significant changes to the format of this table so I hope it's ok.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/297.html" title="Last updated on Nov 30, 2018, 8:25 AM GMT (5e8948c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/297/8b58476...grantnoble:5e8948c.html" title="Last updated on Nov 30, 2018, 8:25 AM GMT (5e8948c)">Diff</a>
> Grammar and formatting suggestions for Section 5, Basic Concepts

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/300.html" title="Last updated on Dec 3, 2018, 9:47 PM GMT (92f318d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/300/8b58476...grantnoble:92f318d.html" title="Last updated on Dec 3, 2018, 9:47 PM GMT (92f318d)">Diff</a>
> Grammar and formatting suggestions for section 7 Syntaxes

- index.html
This PR replaces PR #302.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/308.html" title="Last updated on Dec 12, 2018, 8:09 AM GMT (d74c670)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/308/6198a5e...d74c670.html" title="Last updated on Dec 12, 2018, 8:09 AM GMT (d74c670)">Diff</a>
> Section 9 grammar and formatting suggestions

- index.html
Replaces PR #305.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/309.html" title="Last updated on Dec 12, 2018, 8:18 AM GMT (92b67a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/309/d8b88e8...92b67a3.html" title="Last updated on Dec 12, 2018, 8:18 AM GMT (92b67a3)">Diff</a>
> Section 10 grammar and formatting suggestions

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/323.html" title="Last updated on Dec 18, 2018, 1:02 AM UTC (66b6d7b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/323/8c132b4...grantnoble:66b6d7b.html" title="Last updated on Dec 18, 2018, 1:02 AM UTC (66b6d7b)">Diff</a>
> Section 1.3 add links and grammar suggestions

- terms.html
plus arranged the terms in alphabetic order
> Section 2 Terminology links and grammar suggestions

- index.html
and a line length fix
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/325.html" title="Last updated on Dec 18, 2018, 3:18 AM UTC (0975523)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/325/8c132b4...grantnoble:0975523.html" title="Last updated on Dec 18, 2018, 3:18 AM UTC (0975523)">Diff</a>
> Section 3.1 one link added

- index.html
I noted in terms.html, the data-lt for subject also included subject's so updated these links accordingly.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/327.html" title="Last updated on Dec 18, 2018, 3:53 AM UTC (1e9ef0b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/327/8c132b4...grantnoble:1e9ef0b.html" title="Last updated on Dec 18, 2018, 3:53 AM UTC (1e9ef0b)">Diff</a>
> Section 3.3 links added and tidied up

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/328.html" title="Last updated on Dec 18, 2018, 4:07 AM UTC (9d44a9e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/328/8c132b4...grantnoble:9d44a9e.html" title="Last updated on Dec 18, 2018, 4:07 AM UTC (9d44a9e)">Diff</a>
> Section 4 links and grammar suggestions

- index.html
mostly DID links
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/330.html" title="Last updated on Dec 18, 2018, 6:26 AM UTC (950c241)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/330/8c132b4...grantnoble:950c241.html" title="Last updated on Dec 18, 2018, 6:26 AM UTC (950c241)">Diff</a>
> Section 5.2 links and grammar suggestions

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/331.html" title="Last updated on Dec 18, 2018, 6:47 AM UTC (bca864f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/331/8c132b4...grantnoble:bca864f.html" title="Last updated on Dec 18, 2018, 6:47 AM UTC (bca864f)">Diff</a>
> Section 5.3 links and formatting suggestions

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/332.html" title="Last updated on Dec 18, 2018, 6:56 AM UTC (b31f480)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/332/8c132b4...grantnoble:b31f480.html" title="Last updated on Dec 18, 2018, 6:56 AM UTC (b31f480)">Diff</a>
> Section 5.4 link suggestions

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/333.html" title="Last updated on Dec 18, 2018, 7:08 AM UTC (cdeaf1f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/333/8c132b4...grantnoble:cdeaf1f.html" title="Last updated on Dec 18, 2018, 7:08 AM UTC (cdeaf1f)">Diff</a>
> Section 5.5 updated heading level for consistency

- index.html
with the next section
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/334.html" title="Last updated on Dec 18, 2018, 7:12 AM UTC (83e8b71)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/334/8c132b4...grantnoble:83e8b71.html" title="Last updated on Dec 18, 2018, 7:12 AM UTC (83e8b71)">Diff</a>
> Section 5.6 "If specified" for consistency

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/335.html" title="Last updated on Dec 18, 2018, 7:20 AM UTC (d3639ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/335/8c132b4...grantnoble:d3639ae.html" title="Last updated on Dec 18, 2018, 7:20 AM UTC (d3639ae)">Diff</a>
> Section 5.7 link suggestions

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/320.html" title="Last updated on Dec 17, 2018, 11:09 AM UTC (246aef6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/320/8c132b4...grantnoble:246aef6.html" title="Last updated on Dec 17, 2018, 11:09 AM UTC (246aef6)">Diff</a>
> Section 1.2 added links and grammar suggestions

- index.html
Again, not totally sure about this
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/339.html" title="Last updated on Dec 19, 2018, 1:35 AM UTC (5f86890)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/339/a6cbe50...grantnoble:5f86890.html" title="Last updated on Dec 19, 2018, 1:35 AM UTC (5f86890)">Diff</a>
> Section 6.1.1 upper case Context to lower case

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/340.html" title="Last updated on Dec 19, 2018, 2:04 AM UTC (4c68ca2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/340/a6cbe50...grantnoble:4c68ca2.html" title="Last updated on Dec 19, 2018, 2:04 AM UTC (4c68ca2)">Diff</a>
> Section 6.2 mostly grammar and formatting suggestions

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/341.html" title="Last updated on Dec 19, 2018, 2:16 AM UTC (ca6a3e0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/341/a6cbe50...grantnoble:ca6a3e0.html" title="Last updated on Dec 19, 2018, 2:16 AM UTC (ca6a3e0)">Diff</a>
> Section 6.3 formatting and grammar suggestions

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/342.html" title="Last updated on Dec 19, 2018, 2:53 AM UTC (29ead7e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/342/a6cbe50...grantnoble:29ead7e.html" title="Last updated on Dec 19, 2018, 2:53 AM UTC (29ead7e)">Diff</a>
> Section 6.4 term linking, formatting and grammar suggestions

- index.html
Making the sentence consistent with the previous one
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/344.html" title="Last updated on Dec 20, 2018, 6:08 AM UTC (00d11e6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/344/454437b...grantnoble:00d11e6.html" title="Last updated on Dec 20, 2018, 6:08 AM UTC (00d11e6)">Diff</a>
> Section 7.5 Terms of Use minor wording change

- index.html
A little less wordy, I think.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/345.html" title="Last updated on Dec 20, 2018, 6:19 AM UTC (ed751ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/345/454437b...grantnoble:ed751ff.html" title="Last updated on Dec 20, 2018, 6:19 AM UTC (ed751ff)">Diff</a>
> Section 7.6 Evidence minor wording change

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/346.html" title="Last updated on Dec 20, 2018, 6:38 AM UTC (eb605bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/346/454437b...grantnoble:eb605bd.html" title="Last updated on Dec 20, 2018, 6:38 AM UTC (eb605bd)">Diff</a>
> Section 7.7.1 links added and some wording changes

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/347.html" title="Last updated on Dec 20, 2018, 6:48 AM UTC (efd2690)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/347/454437b...grantnoble:efd2690.html" title="Last updated on Dec 20, 2018, 6:48 AM UTC (efd2690)">Diff</a>
> Section 7.7.2 links and wording changes

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/349.html" title="Last updated on Dec 20, 2018, 7:28 AM UTC (e313f49)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/349/454437b...grantnoble:e313f49.html" title="Last updated on Dec 20, 2018, 7:28 AM UTC (e313f49)">Diff</a>
> Section 7.7.4 Linking, and rewording

- index.html
and included link to the example in the Appendix
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/348.html" title="Last updated on Dec 20, 2018, 7:08 AM UTC (2bcdf50)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/348/454437b...grantnoble:2bcdf50.html" title="Last updated on Dec 20, 2018, 7:08 AM UTC (2bcdf50)">Diff</a>
> Section 7.7.3 Links and wording changes

- index.html
Provided examples for JWT
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/361.html" title="Last updated on Jan 2, 2019, 5:51 PM UTC (52d0664)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/361/3af2751...52d0664.html" title="Last updated on Jan 2, 2019, 5:51 PM UTC (52d0664)">Diff</a>
> Provided examples for JWT

- index.html
just one...
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/353.html" title="Last updated on Dec 26, 2018, 9:57 PM UTC (118f2d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/353/3af2751...grantnoble:118f2d3.html" title="Last updated on Dec 26, 2018, 9:57 PM UTC (118f2d3)">Diff</a>
> Section 8.2 link fix

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/354.html" title="Last updated on Dec 26, 2018, 10:51 PM UTC (fa8ae4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/354/3af2751...grantnoble:fa8ae4e.html" title="Last updated on Dec 26, 2018, 10:51 PM UTC (fa8ae4e)">Diff</a>
> Section 8.3 links, grammar, and line length fixes

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/355.html" title="Last updated on Dec 26, 2018, 10:59 PM UTC (c14b431)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/355/3af2751...grantnoble:c14b431.html" title="Last updated on Dec 26, 2018, 10:59 PM UTC (c14b431)">Diff</a>
> Section 9.2 punctuation fix

- index.html
added the word "property" just to clarify things a bit
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/357.html" title="Last updated on Dec 27, 2018, 12:20 AM UTC (83843b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/357/3af2751...grantnoble:83843b2.html" title="Last updated on Dec 27, 2018, 12:20 AM UTC (83843b2)">Diff</a>
> Section 9.5 wording suggestion

- index.html
instead of quotes around "data first" perhaps em tags?
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/358.html" title="Last updated on Dec 27, 2018, 12:32 AM UTC (72a944d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/358/3af2751...grantnoble:72a944d.html" title="Last updated on Dec 27, 2018, 12:32 AM UTC (72a944d)">Diff</a>
> Section 10.1 formatting suggestions

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/359.html" title="Last updated on Dec 27, 2018, 12:49 AM UTC (68c2f6a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/359/3af2751...grantnoble:68c2f6a.html" title="Last updated on Dec 27, 2018, 12:49 AM UTC (68c2f6a)">Diff</a>
> Section 11 Capitalization suggestion

- index.html
Rewording of this one section reference to be consistent with all other section references in the doc.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/366.html" title="Last updated on Jan 14, 2019, 5:57 AM UTC (6d76ebb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/366/3059153...grantnoble:6d76ebb.html" title="Last updated on Jan 14, 2019, 5:57 AM UTC (6d76ebb)">Diff</a>
> Reword section reference for consistency

- index.html
Apart from missing "a", reworded the para about merging claims to express graphs of information to make it, I think, clearer.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/369.html" title="Last updated on Jan 15, 2019, 5:59 AM UTC (22b59b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/369/3059153...grantnoble:22b59b9.html" title="Last updated on Jan 15, 2019, 5:59 AM UTC (22b59b9)">Diff</a>
> Section 3.1 grammar and wording update

- VCDMExplainer.md
cleaned up other explainer language to match the data model.
> added zkp to explainer, also

- index.html
Missing another "a" (how did I miss that the first time(s)) as well as rewording some of the paras. Also referencing the figures directly.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/370.html" title="Last updated on Jan 16, 2019, 10:14 PM UTC (0417d9d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/370/94d2483...grantnoble:0417d9d.html" title="Last updated on Jan 16, 2019, 10:14 PM UTC (0417d9d)">Diff</a>
> Section 3.2 grammar and wording update

- index.html
Updated wording in this section to match that of the previous section about credentials.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/372.html" title="Last updated on Jan 16, 2019, 10:16 PM UTC (eaf0f43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/372/94d2483...grantnoble:eaf0f43.html" title="Last updated on Jan 16, 2019, 10:16 PM UTC (eaf0f43)">Diff</a>
> Section 3.3 grammar and wording update

- index.html
Mostly linking for property and type terms, plus some grammar updates
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/373.html" title="Last updated on Jan 16, 2019, 10:19 PM UTC (ff4183f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/373/94d2483...grantnoble:ff4183f.html" title="Last updated on Jan 16, 2019, 10:19 PM UTC (ff4183f)">Diff</a>
> Section 6 term linking and some grammar

- VCDMExplainer.md
reordered tricky design decisions; provided input for JWT
> Explainer input with respect to JWT

- VCDMExplainer.md
Line lengths, grammar, some formatting, and a couple of typos.
> VCDM Explainer Review

- index.html
Mostly linking, line spacing, and some grammar changes.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/385.html" title="Last updated on Jan 22, 2019, 1:09 AM UTC (76b256b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/385/4926b51...grantnoble:76b256b.html" title="Last updated on Jan 22, 2019, 1:09 AM UTC (76b256b)">Diff</a>
> Section 8 Review and update

- index.html
Linking, line length, grammar updates
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/387.html" title="Last updated on Jan 22, 2019, 6:28 AM UTC (aadb796)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/387/4926b51...grantnoble:aadb796.html" title="Last updated on Jan 22, 2019, 6:28 AM UTC (aadb796)">Diff</a>
> Section 9.10 to 9.12 updates

- index.html
Linking, reformatting with bulleted list, line length
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/388.html" title="Last updated on Jan 22, 2019, 6:47 AM UTC (b4a6f5e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/388/4926b51...grantnoble:b4a6f5e.html" title="Last updated on Jan 22, 2019, 6:47 AM UTC (b4a6f5e)">Diff</a>
> Appendix A Advance Examples update

- VCDMExplainer.md
Clarify Features at Risk with current state of affairs.
> Update features at risk section

- index.html
Update revocation language to be more explicit about what might be revoked and where the instructions would be expressed.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/416.html" title="Last updated on Feb 3, 2019, 8:43 PM UTC (d01d94d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/416/ac6c5c9...d01d94d.html" title="Last updated on Feb 3, 2019, 8:43 PM UTC (d01d94d)">Diff</a>
> Update revocation to reference credentialStatus

- index.html
fixes issue #406
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/417.html" title="Last updated on Feb 10, 2019, 3:40 PM UTC (fbfaf0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/417/ac6c5c9...fbfaf0c.html" title="Last updated on Feb 10, 2019, 3:40 PM UTC (fbfaf0c)">Diff</a>
> Update authorization language

- index.html
fixes issue #405
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/418.html" title="Last updated on Feb 10, 2019, 4:17 PM UTC (71c440e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/418/ac6c5c9...71c440e.html" title="Last updated on Feb 10, 2019, 4:17 PM UTC (71c440e)">Diff</a>
> Update Evidence language

- index.html
refine the original requirement list to reflect the intersection of the use case document and the data model specification.
section remains non-normative.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/415.html" title="Last updated on Feb 19, 2019, 3:45 PM UTC (583b7ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/415/ac6c5c9...583b7ae.html" title="Last updated on Feb 19, 2019, 3:45 PM UTC (583b7ae)">Diff</a>
> Update non-normative requirements

- index.html
Continuation of https://github.com/w3c/vc-data-model/pull/313
***
<a href="https://pr-preview.s3.amazonaws.com/digitalbazaar/vc-data-model/pull/420.html" title="Last updated on Feb 11, 2019, 5:03 PM UTC (abffc0b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/420/95d7a68...digitalbazaar:abffc0b.html" title="Last updated on Feb 11, 2019, 5:03 PM UTC (abffc0b)">Diff</a>
> Lifecycle Additions

- index.html
Added clarifying language to the proof section according to the conversation in #419
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/423.html" title="Last updated on Feb 19, 2019, 4:13 AM UTC (0aee801)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/423/f6bda93...brentzundel:0aee801.html" title="Last updated on Feb 19, 2019, 4:13 AM UTC (0aee801)">Diff</a>
> Clarified proof section

- index.html
From Section 8 Syntaxes onwards
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/425.html" title="Last updated on Feb 21, 2019, 2:03 AM UTC (0df0a74)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/425/f6bda93...grantnoble:0df0a74.html" title="Last updated on Feb 21, 2019, 2:03 AM UTC (0df0a74)">Diff</a>
> More linking, grammar, and line length suggestions

- terms.html
Mostly line length, but some linking and grammar, and a typo or two.
> Terminology review suggestions

- index.html
Suggested review edits up to and including Section 7.10 Syntactic Sugar. Second review to follow.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/424.html" title="Last updated on Feb 21, 2019, 10:39 PM UTC (10541c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/424/43286e2...grantnoble:10541c0.html" title="Last updated on Feb 21, 2019, 10:39 PM UTC (10541c0)">Diff</a>
> Linking, grammar, punctuation, and line length suggestions

- index.html
Most of these edit suggestions are for consistency with the rest of the doc. As for changing the list from ordered to unordered, it's my opinion that ordered lists should be used for steps in a processes, not regular lists of things.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/431.html" title="Last updated on Feb 24, 2019, 3:39 AM UTC (7d1a34e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/431/5f09c57...grantnoble:7d1a34e.html" title="Last updated on Feb 24, 2019, 3:39 AM UTC (7d1a34e)">Diff</a>
> Linking, unordered list, capitalization and line length edits

- index.html
Minor revisions in ZKP section text.
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/434.html" title="Last updated on Mar 11, 2019, 10:27 PM UTC (0ec2ff0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/434/5f09c57...brentzundel:0ec2ff0.html" title="Last updated on Mar 11, 2019, 10:27 PM UTC (0ec2ff0)">Diff</a>
> Zkp section corrections #1

- index.html
@David-Chadwick I would like your feedback on the changes I'm recommending to your PR.
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/449.html" title="Last updated on Mar 12, 2019, 5:25 PM UTC (db5d7f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/449/9a486cc...brentzundel:db5d7f5.html" title="Last updated on Mar 12, 2019, 5:25 PM UTC (db5d7f5)">Diff</a>
> removed protocol-specific conformance statements

- index.html
WIP - DO NOT MERGE YET.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/443.html" title="Last updated on Mar 14, 2019, 7:35 PM UTC (59ff3ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/443/441726a...59ff3ba.html" title="Last updated on Mar 14, 2019, 7:35 PM UTC (59ff3ba)">Diff</a>
> Conformance language changes/additions.

- index.html
PR for issue #222
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/448.html" title="Last updated on Mar 12, 2019, 8:08 PM UTC (e6f4f3a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/448/7edea6b...brentzundel:e6f4f3a.html" title="Last updated on Mar 12, 2019, 8:08 PM UTC (e6f4f3a)">Diff</a>
> addressed private browsing scenario

- common.js
- index.html
from #394
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/475.html" title="Last updated on Mar 26, 2019, 5:01 PM UTC (b74e8f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/475/4253b2f...b74e8f8.html" title="Last updated on Mar 26, 2019, 5:01 PM UTC (b74e8f8)">Diff</a>
> Misplaced normative text, and other editorial issues

- index.html
fix issue #466
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/477.html" title="Last updated on Mar 26, 2019, 8:21 PM UTC (dacbd68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/477/d2d7488...dacbd68.html" title="Last updated on Mar 26, 2019, 8:21 PM UTC (dacbd68)">Diff</a>
> Editorial fix to definitions

- index.html
Addresses the part of #495 that isn't a request for a normative protocol requirement.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/497.html" title="Last updated on Mar 27, 2019, 11:50 PM UTC (a7f451b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/497/1ad7698...a7f451b.html" title="Last updated on Mar 27, 2019, 11:50 PM UTC (a7f451b)">Diff</a>
> Update Token Binding Reference

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/503.html" title="Last updated on Mar 27, 2019, 5:49 PM UTC (fe371f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/503/1ad7698...fe371f7.html" title="Last updated on Mar 27, 2019, 5:49 PM UTC (fe371f7)">Diff</a>
> Information related to a credential (Fix for #462)

- index.html
Addresses Issue #471
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/507.html" title="Last updated on Mar 27, 2019, 9:25 PM UTC (8d87435)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/507/1ad7698...brentzundel:8d87435.html" title="Last updated on Mar 27, 2019, 9:25 PM UTC (8d87435)">Diff</a>
> Added clarifying language to requirement

- index.html
Addresses issue #492 
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/510.html" title="Last updated on Mar 28, 2019, 4:15 PM UTC (574628d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/510/1ad7698...brentzundel:574628d.html" title="Last updated on Mar 28, 2019, 4:15 PM UTC (574628d)">Diff</a>
> added clarifying language to private browsing section

- index.html
PR to address issue #485 
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/519.html" title="Last updated on Apr 2, 2019, 12:08 AM UTC (50d9142)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/519/1ad7698...brentzundel:50d9142.html" title="Last updated on Apr 2, 2019, 12:08 AM UTC (50d9142)">Diff</a>
> Add note providing an example of a JWK as an issuer.

- index.html
Linking, some grammar and punctuation, and some section elements to fix up headings.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/522.html" title="Last updated on Apr 3, 2019, 6:15 AM UTC (cc86c87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/522/1ad7698...grantnoble:cc86c87.html" title="Last updated on Apr 3, 2019, 6:15 AM UTC (cc86c87)">Diff</a>
> Editorial review of Syntaxes section

- index.html
added paragraph about encryption to PII section in privacy considerations
This is to address one point about protecting PII from issue #486 
> Add clarifying text to PII section

- index.html
This PR add clarifying text and edits to the Presentation section in response to issue #488
> PR for Issue 488

- index.html
This PR is intended to address issue #478 
> minor edit of text in Identifiers section.

- index.html
Again, mostly "verifiable" credentials, but also some grammar and punctuation, and other changes.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/528.html" title="Last updated on Apr 5, 2019, 1:26 AM UTC (fb4376d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/528/1ad7698...grantnoble:fb4376d.html" title="Last updated on Apr 5, 2019, 1:26 AM UTC (fb4376d)">Diff</a>
> Editorial review suggestions for Security Considerations section

- index.html
Some linking, and formatting suggestions
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/529.html" title="Last updated on Apr 5, 2019, 2:12 AM UTC (f5a4bc6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/529/1ad7698...grantnoble:f5a4bc6.html" title="Last updated on Apr 5, 2019, 2:12 AM UTC (f5a4bc6)">Diff</a>
> Editorial review of Accessiblity and Internationalization sections

- index.html
Again, "verifiable" credentials and presentations. Some grammar and rewording, and some linking.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/516.html" title="Last updated on Apr 2, 2019, 10:51 PM UTC (abb4436)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/516/1ad7698...grantnoble:abb4436.html" title="Last updated on Apr 2, 2019, 10:51 PM UTC (abb4436)">Diff</a>
> Editorial edit suggestions for Basic Concepts section

- index.html
More "verifiable" credentials and presentations. Linking, formatting, grammar changes too.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/517.html" title="Last updated on Apr 2, 2019, 11:13 PM UTC (a6a01c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/517/1ad7698...grantnoble:a6a01c9.html" title="Last updated on Apr 2, 2019, 11:13 PM UTC (a6a01c9)">Diff</a>
> Suggested editorial updates to Advanced Concepts section

- index.html
A lot of "verifiable" credentials, some grammar and punctuation
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/527.html" title="Last updated on Apr 4, 2019, 5:31 AM UTC (c65b357)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/527/1ad7698...grantnoble:c65b357.html" title="Last updated on Apr 4, 2019, 5:31 AM UTC (c65b357)">Diff</a>
> Editorial update suggestions for Privacy Considerations section

- index.html
fixed issue #541 - decoding rules for jti and sub are mixed up
> fixed issue 541 - decoding rules for jti and sub are mixed up

- index.html
For clarity, the "If" should be in each bullet, not a lead-in.
> (Editorial) clarify "transform the JWT specific"

- index.html
* corrected verb plurality; improved expository text
* changed random British spelling to American English per W3 style
> (editorial) improved Lifecycle note

- index.html
hopefully clearer text, definitely better punctuation
> (editorial) punctuation and a few words

- index.html
> (editorial) corrects trust model

- index.html
Related to #488.
I have tried to be very careful to not make substantive changes, but rather rephrase this section to make the normative statements in the same way that other sections of the specification make the same sort of normative statements. Please double-check my changes to make sure I'm not stating anything new (or changing the existing normative statements in a way that is substantive or would change implementations.).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/547.html" title="Last updated on Apr 24, 2019, 3:54 AM UTC (8fef5c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/547/2dde7d4...8fef5c3.html" title="Last updated on Apr 24, 2019, 3:54 AM UTC (8fef5c3)">Diff</a>
> Non-substantive refinement of Presentations section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/571.html" title="Last updated on Apr 24, 2019, 4:17 PM UTC (6b8993a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/571/420639f...6b8993a.html" title="Last updated on Apr 24, 2019, 4:17 PM UTC (6b8993a)">Diff</a>
> (editorial) plurality consistency (adds an "s")

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/573.html" title="Last updated on Apr 24, 2019, 4:39 PM UTC (576d0fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/573/420639f...576d0fc.html" title="Last updated on Apr 24, 2019, 4:39 PM UTC (576d0fc)">Diff</a>
> (editorial) minor phrasing improvement

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/574.html" title="Last updated on Apr 24, 2019, 4:53 PM UTC (c4c5bd0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/574/420639f...c4c5bd0.html" title="Last updated on Apr 24, 2019, 4:53 PM UTC (c4c5bd0)">Diff</a>
> (editorial) U.S. English "Authorizes"

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/576.html" title="Last updated on Apr 25, 2019, 1:24 AM UTC (fd3edee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/576/1e95d73...fd3edee.html" title="Last updated on Apr 25, 2019, 1:24 AM UTC (fd3edee)">Diff</a>
> (editorial) phrasing improvements

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/578.html" title="Last updated on Apr 24, 2019, 8:32 PM UTC (33837af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/578/6207410...33837af.html" title="Last updated on Apr 24, 2019, 8:32 PM UTC (33837af)">Diff</a>
> (editorial) rephrasing for "historical" clarity

- index.html
Addresses #552
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/583.html" title="Last updated on Apr 26, 2019, 4:23 PM UTC (5617e14)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/583/0626084...5617e14.html" title="Last updated on Apr 26, 2019, 4:23 PM UTC (5617e14)">Diff</a>
> rephrased to address #552

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/588.html" title="Last updated on May 6, 2019, 2:46 PM UTC (63bc986)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/588/ad2ec52...63bc986.html" title="Last updated on May 6, 2019, 2:46 PM UTC (63bc986)">Diff</a>
> clarify language around @context

- index.html
This is related to #520 and is the last PR needed to close out that issue based on the WG resolution.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/590.html" title="Last updated on May 5, 2019, 7:13 PM UTC (287e71e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/590/bb5ef42...287e71e.html" title="Last updated on May 5, 2019, 7:13 PM UTC (287e71e)">Diff</a>
> Add IANA Considerations section. Related to #520.

- common.js
- index.html
If merged, this will close #524.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/591.html" title="Last updated on May 7, 2019, 1:42 AM UTC (18d32be)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/591/bb5ef42...18d32be.html" title="Last updated on May 7, 2019, 1:42 AM UTC (18d32be)">Diff</a>
> Refer to Verifiable Credentials Extension Registry.

- index.html
Related to #525.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/592.html" title="Last updated on May 6, 2019, 2:30 AM UTC (9c43dce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/592/bb5ef42...9c43dce.html" title="Last updated on May 6, 2019, 2:30 AM UTC (9c43dce)">Diff</a>
> Explain why order is important in @context property.

- common.js
- index.html
Related to #470.
/cc @jricher
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/593.html" title="Last updated on May 7, 2019, 1:50 AM UTC (4816ada)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/593/bb5ef42...4816ada.html" title="Last updated on May 7, 2019, 1:50 AM UTC (4816ada)">Diff</a>
> Explain and link to proof specs. 

- index.html
Related to #511.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/594.html" title="Last updated on May 7, 2019, 1:56 AM UTC (22a33da)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/594/bb5ef42...22a33da.html" title="Last updated on May 7, 2019, 1:56 AM UTC (22a33da)">Diff</a>
> Add warning related to multiple subjects and JWTs.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/595.html" title="Last updated on May 8, 2019, 10:23 AM UTC (6d335c5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/595/bb5ef42...6d335c5.html" title="Last updated on May 8, 2019, 10:23 AM UTC (6d335c5)">Diff</a>
> Update @context definition

- index.html
Note that the CR comment period has ended.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/597.html" title="Last updated on May 7, 2019, 2:45 AM UTC (1d6e6d6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/597/5577f77...1d6e6d6.html" title="Last updated on May 7, 2019, 2:45 AM UTC (1d6e6d6)">Diff</a>
> Note the end of Candidate Recommendation comment period.

- index.html
Related to #474.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/598.html" title="Last updated on May 7, 2019, 3:24 AM UTC (72ddad3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/598/5577f77...72ddad3.html" title="Last updated on May 7, 2019, 3:24 AM UTC (72ddad3)">Diff</a>
> Note difference between data schemas and @context.

- index.html
Fixes issue #600.
***
<a href="https://pr-preview.s3.amazonaws.com/dmitrizagidulin/vc-data-model/pull/601.html" title="Last updated on May 7, 2019, 4:23 AM UTC (2b60231)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/601/5577f77...dmitrizagidulin:2b60231.html" title="Last updated on May 7, 2019, 4:23 AM UTC (2b60231)">Diff</a>
> Update VerifiablePresentation types in examples.

- index.html
addresses #605
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/607.html" title="Last updated on May 8, 2019, 3:51 PM UTC (4d474d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/607/5577f77...4d474d2.html" title="Last updated on May 8, 2019, 3:51 PM UTC (4d474d2)">Diff</a>
> adjust example context text

- index.html
addresses #613
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/615.html" title="Last updated on May 9, 2019, 5:26 PM UTC (5d6c4b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/615/5577f77...5d6c4b6.html" title="Last updated on May 9, 2019, 5:26 PM UTC (5d6c4b6)">Diff</a>
> clarify that expirationDate is optional

- index.html
This PR addresses Issue #606 
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/616.html" title="Last updated on May 9, 2019, 7:59 PM UTC (89d1e1f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/616/5577f77...brentzundel:89d1e1f.html" title="Last updated on May 9, 2019, 7:59 PM UTC (89d1e1f)">Diff</a>
> Made optional nature of id more explicit

- index.html
addresses #611
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/617.html" title="Last updated on May 9, 2019, 5:32 PM UTC (3a90bab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/617/5577f77...3a90bab.html" title="Last updated on May 9, 2019, 5:32 PM UTC (3a90bab)">Diff</a>
> require proof details as well as mechanism

- terms.html
> name DID document in terminology section

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/620.html" title="Last updated on May 13, 2019, 6:16 PM UTC (0ae3195)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/620/5577f77...0ae3195.html" title="Last updated on May 13, 2019, 6:16 PM UTC (0ae3195)">Diff</a>
> Update definition of issuance date

- contexts/credentials/examples/v1
Fixes issue https://github.com/w3c/vc-data-model/issues/622 and https://github.com/w3c/vc-test-suite/issues/19.
(Also adds some other missing fields required to pass the vc-test-suite).
> Fix invalid context entries, add required fields.

- index.html
Alternative replacement text for the Disputes section
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/629.html" title="Last updated on May 14, 2019, 4:17 PM UTC (422d965)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/629/d2a8a5f...422d965.html" title="Last updated on May 14, 2019, 4:17 PM UTC (422d965)">Diff</a>
> Alt Disputes

- index.html
addresses #612
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/614.html" title="Last updated on May 14, 2019, 2:23 PM UTC (0f54ac4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/614/d2a8a5f...0f54ac4.html" title="Last updated on May 14, 2019, 2:23 PM UTC (0f54ac4)">Diff</a>
> rephrasing of proof mechanism note

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/627.html" title="Last updated on May 14, 2019, 1:01 PM UTC (bc0bfa5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/627/d2a8a5f...bc0bfa5.html" title="Last updated on May 14, 2019, 1:01 PM UTC (bc0bfa5)">Diff</a>
> Addition to Presentation Proofs and JWT

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/628.html" title="Last updated on May 14, 2019, 3:11 PM UTC (8a689f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/628/66e81c7...8a689f0.html" title="Last updated on May 14, 2019, 3:11 PM UTC (8a689f0)">Diff</a>
> even less @id optionality ambiguity

- index.html
addresses issue #604 
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/630.html" title="Last updated on May 15, 2019, 9:44 PM UTC (3ae0681)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/630/66e81c7...brentzundel:3ae0681.html" title="Last updated on May 15, 2019, 9:44 PM UTC (3ae0681)">Diff</a>
> clarified @context processing

- index.html
This is the best I could do wrt. the changes that @ReiksJ requested. We elaborate a bit more and point to the Implementation Guidance document, where we can elaborate more on the use cases.
Related to #479.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/643.html" title="Last updated on May 26, 2019, 5:40 PM UTC (d8dbe62)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/643/446c421...d8dbe62.html" title="Last updated on May 26, 2019, 5:40 PM UTC (d8dbe62)">Diff</a>
> Add mentions of ToS usage based on feedback from @RieksJ.

- common.js
- index.html
This uses the latest reference to JSON Schema at IETF.
Related to #589.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/647.html" title="Last updated on Jun 8, 2019, 5:07 PM UTC (30304d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/647/446c421...30304d7.html" title="Last updated on Jun 8, 2019, 5:07 PM UTC (30304d7)">Diff</a>
> Add latest reference to JSON Schema at IETF.

- index.html
Related to #596.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/648.html" title="Last updated on May 26, 2019, 8:05 PM UTC (0ef6914)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/648/446c421...0ef6914.html" title="Last updated on May 26, 2019, 8:05 PM UTC (0ef6914)">Diff</a>
> Add holder to presentation in a non-normative way.

- index.html
Related to #602.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/649.html" title="Last updated on May 26, 2019, 8:26 PM UTC (65e5917)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/649/446c421...65e5917.html" title="Last updated on May 26, 2019, 8:26 PM UTC (65e5917)">Diff</a>
> Replace non-normative 'must' with 'is expected to'.

- index.html
Related to #605.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/650.html" title="Last updated on May 26, 2019, 8:47 PM UTC (aba0b0b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/650/d18642b...aba0b0b.html" title="Last updated on May 26, 2019, 8:47 PM UTC (aba0b0b)">Diff</a>
> Non-substantive guidance for example context URL.

- index.html
Related to #606.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/651.html" title="Last updated on May 26, 2019, 8:49 PM UTC (0a3d1b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/651/d18642b...0a3d1b3.html" title="Last updated on May 26, 2019, 8:49 PM UTC (0a3d1b3)">Diff</a>
> Highlight correlation concerns wrt. identifiers.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/656.html" title="Last updated on Jun 8, 2019, 5:39 PM UTC (904569e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/656/d18642b...904569e.html" title="Last updated on Jun 8, 2019, 5:39 PM UTC (904569e)">Diff</a>
> language massage around aggregation

- index.html
… and expected arity of other properties
This PR addresses Issue #621 
***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-data-model/pull/665.html" title="Last updated on Jun 11, 2019, 6:02 PM UTC (e6bb779)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/665/c28d535...brentzundel:e6bb779.html" title="Last updated on Jun 11, 2019, 6:02 PM UTC (e6bb779)">Diff</a>
> Added text clarifying singleton properties

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/peacekeeper/vc-data-model/pull/666.html" title="Last updated on Jun 18, 2019, 6:59 AM UTC (5a052e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/666/c28d535...peacekeeper:5a052e8.html" title="Last updated on Jun 18, 2019, 6:59 AM UTC (5a052e8)">Diff</a>
> Small typo

- index.html
fixed #669
***
<a href="https://pr-preview.s3.amazonaws.com/awoie/vc-data-model/pull/670.html" title="Last updated on Jun 25, 2019, 2:12 PM UTC (4760916)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/670/5a1f617...awoie:4760916.html" title="Last updated on Jun 25, 2019, 2:12 PM UTC (4760916)">Diff</a>
> fixed #669 -- removed redundant and misleading statement

- contexts/credentials/v1
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/673.html" title="Last updated on Jun 25, 2019, 3:02 PM UTC (e4bc021)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/673/5a1f617...e4bc021.html" title="Last updated on Jun 25, 2019, 3:02 PM UTC (e4bc021)">Diff</a>
> Update context and associated hash to latest.

- index.html
Fixes #675.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/676.html" title="Last updated on Jul 3, 2019, 1:54 AM UTC (ab9a532)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/676/cd28fa0...ab9a532.html" title="Last updated on Jul 3, 2019, 1:54 AM UTC (ab9a532)">Diff</a>
> Update Editors, Authors, contributors and acknowledgements.

- index.html
a bit of language refinement
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/678.html" title="Last updated on Jul 3, 2019, 9:17 PM UTC (0f68180)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/678/83fe6a1...0f68180.html" title="Last updated on Jul 3, 2019, 9:17 PM UTC (0f68180)">Diff</a>
> (editorial) small language adjustment

- index.html
This sleight cannot be overlooked 🕵🏻‍♀️
***
<a href="https://pr-preview.s3.amazonaws.com/kimdhamilton/vc-data-model/pull/690.html" title="Last updated on Jul 14, 2019, 12:11 AM UTC (12efbf8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/690/96dc09e...kimdhamilton:12efbf8.html" title="Last updated on Jul 14, 2019, 12:11 AM UTC (12efbf8)">Diff</a>
> Added myself to RWOT facilitators

- index.html
Mostly line lenth updates, but some linking, some formatting, and some grammar suggestions.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/679.html" title="Last updated on Jul 10, 2019, 12:01 AM UTC (49db4c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/679/96dc09e...grantnoble:49db4c8.html" title="Last updated on Jul 10, 2019, 12:01 AM UTC (49db4c8)">Diff</a>
> Suggested updates for Abstract and Intro sections

- terms.html
Mostly line length updates, but some formatting, and linking, and grammar suggestions.
> Suggested updates for Terminology section

- index.html
Linking and line length updates, along with some wording changes.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/683.html" title="Last updated on Jul 12, 2019, 2:06 AM UTC (56640f2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/683/96dc09e...grantnoble:56640f2.html" title="Last updated on Jul 12, 2019, 2:06 AM UTC (56640f2)">Diff</a>
> Suggested updates for the Core Data Model section

- index.html
Lots of linking and line length edits. Plus some formatting and grammar.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/684.html" title="Last updated on Jul 12, 2019, 2:29 AM UTC (e19629e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/684/96dc09e...grantnoble:e19629e.html" title="Last updated on Jul 12, 2019, 2:29 AM UTC (e19629e)">Diff</a>
> Suggested updates for the Basic Concepts section

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/686.html" title="Last updated on Jul 12, 2019, 8:53 PM UTC (547c4f3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/686/96dc09e...grantnoble:547c4f3.html" title="Last updated on Jul 12, 2019, 8:53 PM UTC (547c4f3)">Diff</a>
> Suggested updates for Advanced Concepts section

- index.html
Line length updates, linking, some formatting (breaking long paras into bulleted lists) and some wording changes.
> Suggested updates for Syntaxes section

- index.html
Line length edits, linking, consistent use of accronyms, general formatting and wording updates.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/688.html" title="Last updated on Jul 12, 2019, 10:21 AM UTC (b167954)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/688/96dc09e...grantnoble:b167954.html" title="Last updated on Jul 12, 2019, 10:21 AM UTC (b167954)">Diff</a>
> Suggested updates for Privacy Considerations section

- index.html
Mostly line length changes, but some wording changes and some linking.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/689.html" title="Last updated on Jul 12, 2019, 11:05 AM UTC (01cc997)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/689/96dc09e...grantnoble:01cc997.html" title="Last updated on Jul 12, 2019, 11:05 AM UTC (01cc997)">Diff</a>
> Suggested updates for Security Considerations section

- index.html
Wording changes, some grammar, some formatting changes
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/692.html" title="Last updated on Jul 15, 2019, 6:28 PM UTC (f17c59e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/692/96dc09e...grantnoble:f17c59e.html" title="Last updated on Jul 15, 2019, 6:28 PM UTC (f17c59e)">Diff</a>
> Internationalization Considerations suggested editorial updates

- index.html
The opening para was missing the p tags, I added some missing commas, reworded the last sentence, and tidied up the line lengths.
***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/vc-data-model/pull/694.html" title="Last updated on Jul 15, 2019, 10:34 PM UTC (0f9bb7a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/694/96dc09e...grantnoble:0f9bb7a.html" title="Last updated on Jul 15, 2019, 10:34 PM UTC (0f9bb7a)">Diff</a>
> Appendix B Base Context suggested editorial updates

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/697.html" title="Last updated on Jul 15, 2019, 3:14 PM UTC (b05d7c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/697/d92ceaf...b05d7c6.html" title="Last updated on Jul 15, 2019, 3:14 PM UTC (b05d7c6)">Diff</a>
> fix punctuation and minor reword

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/698.html" title="Last updated on Jul 15, 2019, 3:35 PM UTC (413500f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/698/d92ceaf...413500f.html" title="Last updated on Jul 15, 2019, 3:35 PM UTC (413500f)">Diff</a>
> small grammar and other corrections

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/700.html" title="Last updated on Jul 15, 2019, 4:07 PM UTC (fb80271)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/700/d92ceaf...fb80271.html" title="Last updated on Jul 15, 2019, 4:07 PM UTC (fb80271)">Diff</a>
> grammar fix and example clarification rewording

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/701.html" title="Last updated on Jul 16, 2019, 3:50 PM UTC (688a3a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/701/d92ceaf...688a3a6.html" title="Last updated on Jul 16, 2019, 3:50 PM UTC (688a3a6)">Diff</a>
> (editorial) change such to showing

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/699.html" title="Last updated on Jul 15, 2019, 3:44 PM UTC (52ebedb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/699/d92ceaf...52ebedb.html" title="Last updated on Jul 15, 2019, 3:44 PM UTC (52ebedb)">Diff</a>
> minor grammar and punctuation

- index.html
> Update iss of JWT

- index.html
THis is the second replacement for PR#711
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/718.html" title="Last updated on Aug 19, 2019, 2:31 PM UTC (9040106)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/718/6fc7e54...9040106.html" title="Last updated on Aug 19, 2019, 2:31 PM UTC (9040106)">Diff</a>
> JWT property to claim

- index.html
Minor change. Use the same name that is in the figure.
***
<a href="https://pr-preview.s3.amazonaws.com/ilanolkies/vc-data-model/pull/747.html" title="Last updated on Feb 5, 2021, 10:15 AM UTC (bfb5e2e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/747/0e58fb9...ilanolkies:bfb5e2e.html" title="Last updated on Feb 5, 2021, 10:15 AM UTC (bfb5e2e)">Diff</a>
> Update ref name

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/722.html" title="Last updated on Jun 14, 2021, 2:23 PM UTC (cbf425a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/722/5422780...cbf425a.html" title="Last updated on Jun 14, 2021, 2:23 PM UTC (cbf425a)">Diff</a>
> making a note, a note

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/723.html" title="Last updated on Jun 14, 2021, 2:23 PM UTC (2cb9cae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/723/5422780...2cb9cae.html" title="Last updated on Jun 14, 2021, 2:23 PM UTC (2cb9cae)">Diff</a>
> (editorial) various clarified phrasings

- index.html
Fixes https://github.com/w3c/vc-data-model/issues/772
***
<a href="https://pr-preview.s3.amazonaws.com/TobyEalden/vc-data-model/pull/773.html" title="Last updated on Aug 24, 2021, 2:54 AM UTC (68f3de4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/773/6c429cf...TobyEalden:68f3de4.html" title="Last updated on Aug 24, 2021, 2:54 AM UTC (68f3de4)">Diff</a>
> Add issuer ID to verificationMethod URI

- index.html
issuanceDate was invalid, as 73 is not a valid number of minutes
closes #736
Signed-off-by: Liam Tait <liam.tait@mattr.global>
***
<a href="https://pr-preview.s3.amazonaws.com/Liam-Tait/vc-data-model/pull/737.html" title="Last updated on Apr 6, 2020, 5:46 AM UTC (87638fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/737/0e58fb9...Liam-Tait:87638fa.html" title="Last updated on Apr 6, 2020, 5:46 AM UTC (87638fa)">Diff</a>
> Fix inconsistent issuanceDate

- index.html
This is non-substantive change.
***
<a href="https://pr-preview.s3.amazonaws.com/confiks/vc-data-model/pull/730.html" title="Last updated on Jun 14, 2021, 2:23 PM UTC (5dc1b37)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/730/46fedab...confiks:5dc1b37.html" title="Last updated on Jun 14, 2021, 2:23 PM UTC (5dc1b37)">Diff</a>
> fix: Represent "True" as JSON boolean instead

- diagrams/credential-graph.svg
- diagrams/presentation-graph.svg
- index.html
I noticed that two PRs, #808 and #786 were originally pointed at main when they should have been merged onto the V1.1 branch per our process in a transparent way. This is the first of two PRs to cherry-pick the commits from main and merge them onto V1.1 instead. The second PR will remove those PRs from the main branch as well.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/824.html" title="Last updated on Sep 30, 2021, 3:15 AM UTC (54b88c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/824/e622d89...54b88c9.html" title="Last updated on Sep 30, 2021, 3:15 AM UTC (54b88c9)">Diff</a>
> cherry-pick commits from main to V1.1

- diagrams/credential-graph.svg
- diagrams/presentation-graph.svg
- index.html
In this PR, I'm rebasing the commits that were accidently placed onto main branch and moved over to V1.1 onto V1.2 which will be the branch for handling the combination of all V1.1 and V1.2 changes.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/826.html" title="Last updated on Sep 30, 2021, 11:52 AM UTC (725dece)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/826/f2fa998...725dece.html" title="Last updated on Sep 30, 2021, 11:52 AM UTC (725dece)">Diff</a>
> rebase V1.1 updates onto V1.2

- index.html
- terms.html
Address #751. Adds text from https://github.com/w3c/vc-data-model/issues/751#issuecomment-946074037, incorporating the suggestions by @dlongley and @TallTed.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/829.html" title="Last updated on Dec 6, 2021, 1:46 PM UTC (1e114de)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/829/e77940a...1e114de.html" title="Last updated on Dec 6, 2021, 1:46 PM UTC (1e114de)">Diff</a>
> Add clarification about verifiability

- index.html
Suggested wording that is more precise
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/857.html" title="Last updated on Jan 13, 2022, 2:13 AM UTC (a3c3335)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/857/74cd6e5...a3c3335.html" title="Last updated on Jan 13, 2022, 2:13 AM UTC (a3c3335)">Diff</a>
> Edit of Proof Format section

- README.md
This PR updates the README.md to reflect the v2.0 work.
Note some of the minor tweaks to the process, which the Chairs/Staff will want to review and update as appropriate.
> Update README to reflect v2.0 work.

- .github/workflows/auto-publish.yml
Simple echidna script, no other action is used (so far?) in this repository.
~Note: if the main branch of the repository is changed from `v2.0` to `main`, the relevant reference in line 6 must be changed.~
(The repository secret for W3C_TR_TOKEN has already been created.)
> Setting-up-echidna

- index.html
added awoie to editor's list
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/911.html" title="Last updated on Aug 17, 2022, 9:16 PM UTC (19ba528)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/911/2159bb3...19ba528.html" title="Last updated on Aug 17, 2022, 9:16 PM UTC (19ba528)">Diff</a>
> added awoie to editor's list

- index.html
This PR updates all examples in the specification to use the new v2 JSON-LD Context (as well as creating a new v2 examples context). The PR partially addresses issue #810 and #1002.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1003.html" title="Last updated on Jan 15, 2023, 8:15 PM UTC (9b8c61e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1003/43cc3a6...9b8c61e.html" title="Last updated on Jan 15, 2023, 8:15 PM UTC (9b8c61e)">Diff</a>
> Update all examples to use new v2 JSON-LD Context

- vocab/credentials/v2/vocabulary.yml
Syncing with the latest change of the v2 context
> Added Presentation as a possible domain for termsOfUse to the formal vocabulary

- diagrams/ecosystemdetail.svg
- index.html
- Fixed 1, 2 and the links in CURRENT draft
- Also updated @David-Chadwick 's affiliation while I was there
- 3 was only present in drafts
Should I also fix these in the previous drafts?  If so do I have to update an errata list somewhere, or is that unnecessary for such minor typos?
Closes #1021
***
<a href="https://pr-preview.s3.amazonaws.com/bumblefudge/vc-data-model/pull/1022.html" title="Last updated on Feb 1, 2023, 9:37 AM UTC (027bf72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1022/c344fa0...bumblefudge:027bf72.html" title="Last updated on Feb 1, 2023, 9:37 AM UTC (027bf72)">Diff</a>
> Typos pointed out in issue 1021

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1079.html" title="Last updated on Apr 5, 2023, 3:09 PM UTC (53e57ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1079/0fadd6f...53e57ac.html" title="Last updated on Apr 5, 2023, 3:09 PM UTC (53e57ac)">Diff</a>
> Correct media type to be vc+ld+json

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/selfissued/vc-data-model/pull/1099.html" title="Last updated on Apr 25, 2023, 10:54 PM UTC (f4549b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1099/0abf1f2...selfissued:f4549b6.html" title="Last updated on Apr 25, 2023, 10:54 PM UTC (f4549b6)">Diff</a>
> Mike is now independent

- schema/README.md
- schema/verifiable-credential/example-1.json
- schema/verifiable-credential/example-11.json
- schema/verifiable-credential/example-12.json
- schema/verifiable-credential/example-13.json
- schema/verifiable-credential/example-18.json
- schema/verifiable-credential/example-20.json
- schema/verifiable-credential/example-21.json
- schema/verifiable-credential/example-23.json
- schema/verifiable-credential/example-4.json
- schema/verifiable-credential/verifiable-credential-schema.json
- schema/verifiable-presentation/example-2.json
- schema/verifiable-presentation/example-25.json
- schema/verifiable-presentation/example-45.json
- schema/verifiable-presentation/verifiable-presentation-schema.json
> update json schema to accurately reflect context defn

- index.html
@msporny I am trying to add the tooling that gives us the ability to pull requirements list, similar to what we did for did core.
Similar to how we code gen'ed before: https://github.com/transmute-industries/did-core/tree/main/packages/did-core-tests
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1131.html" title="Last updated on May 15, 2023, 4:56 PM UTC (819e553)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1131/a57fd93...819e553.html" title="Last updated on May 15, 2023, 4:56 PM UTC (819e553)">Diff</a>
> Attempt to add req list

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1143.html" title="Last updated on Jun 6, 2023, 10:53 PM UTC (18d454e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1143/e6e9fbf...18d454e.html" title="Last updated on Jun 6, 2023, 10:53 PM UTC (18d454e)">Diff</a>
> Remove closed issue marker

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1144.html" title="Last updated on Jun 7, 2023, 5:57 PM UTC (96af42f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1144/e6e9fbf...96af42f.html" title="Last updated on Jun 7, 2023, 5:57 PM UTC (96af42f)">Diff</a>
> Request vp media type

- diagrams/ecosystemdetail.svg
This PR fixes https://github.com/w3c/vc-data-model/issues/1148 by slightly tweaking the language.
> Updated privacy language in diagram

- index.html
- Tweak subsection titles of `Media Type Registrations`
- Make `JWT Claim Registrations` a parallel subsection
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-data-model/pull/1163.html" title="Last updated on Jul 12, 2023, 1:42 AM UTC (46743e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1163/85724de...TallTed:46743e8.html" title="Last updated on Jul 12, 2023, 1:42 AM UTC (46743e8)">Diff</a>
> Rationalize and clarify IANA Considerations

- index.html
Fix #1196 
No changes besides the move.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1207.html" title="Last updated on Jul 25, 2023, 5:51 PM UTC (8321efd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1207/d84cf2e...8321efd.html" title="Last updated on Jul 25, 2023, 5:51 PM UTC (8321efd)">Diff</a>
> Move data schemas to basic concepts section

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-data-model/pull/1208.html" title="Last updated on Jul 20, 2023, 5:09 PM UTC (abce602)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1208/7d34e45...TallTed:abce602.html" title="Last updated on Jul 20, 2023, 5:09 PM UTC (abce602)">Diff</a>
> minor language fix

- diagrams/privacy-spectrum.svg
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/fabienpe/vc-data-model/pull/1213.html" title="Last updated on Jul 27, 2023, 8:12 AM UTC (ab68453)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1213/d84cf2e...fabienpe:ab68453.html" title="Last updated on Jul 27, 2023, 8:12 AM UTC (ab68453)">Diff</a>
> Minor correction to viewBox so that all text becomes visible.

- contexts/credentials/v2
- index.html
This PR adds registered claim names used to ensure security properties to the v2 context.
```json
{
"iss": "https://example.com/issuer",
"iat": 1683000000,
"exp": 1883000000,
"@context": [
"https://www.w3.org/2018/credentials/v1",
{
"@vocab": "https://ld.off.example#", 
"cnf": {
"@id": "https://www.iana.org/assignments/jwt#cnf",
"@context": {
"@protected": true,
"kid": {
"@id": "https://www.iana.org/assignments/jwt#kid",
"@type": "@id"
},
"jwk": {
"@id": "https://www.iana.org/assignments/jwt#jwk",
"@type": "@json"
}
}
}}
],
"type": [
"VerifiableCredential",
"VaccinationCertificate"
],
"issuer": "https://example.com/issuer",
"issuanceDate": "2023-02-09T11:01:59Z",
"expirationDate": "2028-02-08T11:01:59Z",
"name": "COVID-19 Vaccination Certificate",
"description": "COVID-19 Vaccination …
```
> Add cnf registered claim to v2 context

- contexts/credentials/v2
- index.html
This PR adds `nbf` to the v2 context.
```json
{
"@context": [
"https://w3id.org/traceability/v1", {
"nbf": {
"@id": "https://www.iana.org/assignments/jwt#iat",
"@type": "https://www.w3.org/2001/XMLSchema#nonNegativeInteger"
}
}
],
"type": "Organization",
"name": "Bartell Inc 🔥",
"description": "Realigned maximized alliance",
"nbf": 123
}
```
...
```json
{
"@type": "https://schema.org/Organization",
"https://schema.org/description": "Realigned maximized alliance",
"https://schema.org/name": "Bartell Inc 🔥",
"https://www.iana.org/assignments/jwt#iat": {
"@type": "https://www.w3.org/2001/XMLSchema#nonNegativeInteger",
"@value": 123
}
}
```
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1221.html" title="Last updated on Aug 4, 2023, 1:03 PM UTC (8ddfc8d)">Preview</a> …
> Add nbf registered claim to v2 context 

- contexts/credentials/v2
- index.html
Basically same as: https://github.com/w3c/vc-data-model/pull/1221
> Add exp registered claim to v2 context 

- index.html
- vocab/credentials/v2/vocabulary.yml
Fixes #1233
***
<a href="https://pr-preview.s3.amazonaws.com/andresuribe87/vc-data-model/pull/1234.html" title="Last updated on Aug 20, 2023, 7:20 PM UTC (97bdc05)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1234/6d626f8...andresuribe87:97bdc05.html" title="Last updated on Aug 20, 2023, 7:20 PM UTC (97bdc05)">Diff</a>
> Update links from VC-JWT to VC-JOSE-COSE

- index.html
Fix #1138
Open to any/all wordsmithing.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1238.html" title="Last updated on Aug 22, 2023, 1:49 PM UTC (ecedad0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1238/b63f65b...ecedad0.html" title="Last updated on Aug 22, 2023, 1:49 PM UTC (ecedad0)">Diff</a>
> Add language on mitm, replay, spoofing attacks

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/m00sey/vc-data-model/pull/1255.html" title="Last updated on Aug 23, 2023, 3:49 PM UTC (f6557a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1255/9cfb718...m00sey:f6557a3.html" title="Last updated on Aug 23, 2023, 3:49 PM UTC (f6557a3)">Diff</a>
> Editorial - update links to non-expired versions

- index.html
- privacy.html
- Fix markup.
- Fix typos.
- Add small "PId" clarification in privacy.html.
***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/vc-data-model/pull/1277.html" title="Last updated on Sep 12, 2023, 1:21 AM UTC (b05936c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1277/d5c7a02...davidlehn:b05936c.html" title="Last updated on Sep 12, 2023, 1:21 AM UTC (b05936c)">Diff</a>
> Fix markup, typos, and a small fix.

- index.html
Fixes #1282
***
<a href="https://pr-preview.s3.amazonaws.com/andresuribe87/vc-data-model/pull/1283.html" title="Last updated on Sep 26, 2023, 9:30 PM UTC (9087738)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1283/fc5a741...andresuribe87:9087738.html" title="Last updated on Sep 26, 2023, 9:30 PM UTC (9087738)">Diff</a>
> Add normative text requiring protecting VCs and VPs

- index.html
Address #1245
In need of @TallTed 's word smithing.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1286.html" title="Last updated on Sep 29, 2023, 8:31 PM UTC (b6ef803)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1286/fc5a741...b6ef803.html" title="Last updated on Sep 29, 2023, 8:31 PM UTC (b6ef803)">Diff</a>
> Privacy considerations around issuer location

- common.js
- index.html
Mostly removing unused references, one instance of removing a vendor specific technology reference (IPFS), and one instance of removing an expired IETF I-D "HASHLINKS".
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 18, 2023, 3:04 PM UTC)_.
<details>
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvc-data-model%2F15eb092a1107dd7ed5bbc60a90c502609734d82d%2Findex.html%3FisPreview%3Dtrue)
```
😭 …
```
> Editorial cleaning

- common.js
- index.html
This PR attempts to address issue #1284 by adding a section on key management. /cc @kdenhartog
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1323.html" title="Last updated on Oct 31, 2023, 1:56 PM UTC (c764728)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1323/cc5cd92...c764728.html" title="Last updated on Oct 31, 2023, 1:56 PM UTC (c764728)">Diff</a>
> Add section on key management.

- common.js
- index.html
Give examples of ToU
This will address issue #1010 by being merged.
***
<a href="https://pr-preview.s3.amazonaws.com/David-Chadwick/vc-data-model/pull/1295.html" title="Last updated on Nov 4, 2023, 5:19 PM UTC (71f3de9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1295/77f95bc...David-Chadwick:71f3de9.html" title="Last updated on Nov 4, 2023, 5:19 PM UTC (71f3de9)">Diff</a>
> Update to Terms of Use description

- index.html
This started as manual reapplication of changes that were tagged as "done" (in PR #1295) but were not. Some additional text changes crept up on me in the process. I believe all are editorial, and none should be controversial.
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-data-model/pull/1345.html" title="Last updated on Nov 11, 2023, 4:04 PM UTC (3a17aeb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1345/998a3dc...TallTed:3a17aeb.html" title="Last updated on Nov 11, 2023, 4:04 PM UTC (3a17aeb)">Diff</a>
> catching omissions from change requests on #1295

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-data-model/pull/1350.html" title="Last updated on Nov 13, 2023, 9:36 PM UTC (0b53e7d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1350/da600f9...TallTed:0b53e7d.html" title="Last updated on Nov 13, 2023, 9:36 PM UTC (0b53e7d)">Diff</a>
> (editorial) Assorted grammar, markup, source formatting, etc.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/selfissued/vc-data-model/pull/1368.html" title="Last updated on Dec 1, 2023, 9:12 PM UTC (e972e1e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1368/1d7b554...selfissued:e972e1e.html" title="Last updated on Dec 1, 2023, 9:12 PM UTC (e972e1e)">Diff</a>
> Mike is at Self-Issued Consulting

- index.html
This PR is an attempt at addressing issue #1374 by adding normative requirements for securing mechanism specifications.
/cc @jyasskin
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1380.html" title="Last updated on Dec 15, 2023, 6:57 PM UTC (5e767d9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1380/40be9e0...5e767d9.html" title="Last updated on Dec 15, 2023, 6:57 PM UTC (5e767d9)">Diff</a>
> Add requirements for securing mechanism specifications.

- .github/workflows/echidna.yml
This PR must be merged ***after*** the CR snapshot is published in 1st of February and ***before*** any other PR is merged
> Update echidna.yml for CR

- index.html
This pulls from the text highlighted via the following link from PR #1302. It also brings in the pending suggestions made by @TallTed to that highlighted text:
https://github.com/w3c/vc-data-model/pull/1302/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R4251-R4266
***
<a href="https://pr-preview.s3.amazonaws.com/BigBlueHat/vc-data-model/pull/1413.html" title="Last updated on Feb 10, 2024, 8:30 PM UTC (34f40bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1413/2980929...BigBlueHat:34f40bc.html" title="Last updated on Feb 10, 2024, 8:30 PM UTC (34f40bc)">Diff</a>
> Add intro to Credential Type-Specific Processing.

- index.html
Improved the French texts in [Example 8](https://www.w3.org/TR/vc-data-model-2.0/#example-usage-of-the-name-and-description-property-0).
I strongly suggest we find someone speaking Arabic and who knows the Arabic terminology to review the Arabic equivalents.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1425.html" title="Last updated on Jan 30, 2024, 2:52 PM UTC (d75f786)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1425/8cc968a...d75f786.html" title="Last updated on Jan 30, 2024, 2:52 PM UTC (d75f786)">Diff</a>
> Update the French examples

- contexts/credentials/v2
- Align with changes in the vc-bitstring-status-list repository.
- https://github.com/w3c/vc-bitstring-status-list/blob/main/contexts/v1.jsonld
> Add `encodedList` type in context.

- index.html
This PR is an attempt to address issue #887 by defining the term used to instantiate a presentation: "create".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1434.html" title="Last updated on Feb 18, 2024, 6:43 PM UTC (cf86d3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1434/d42fd22...cf86d3b.html" title="Last updated on Feb 18, 2024, 6:43 PM UTC (cf86d3b)">Diff</a>
> Specify verb used to instantiate a presentation.

- index.html
fix #1309
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1439.html" title="Last updated on Feb 14, 2024, 11:08 PM UTC (225a708)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1439/d42fd22...225a708.html" title="Last updated on Feb 14, 2024, 11:08 PM UTC (225a708)">Diff</a>
> update examples to show a mix of DID and URI identifiers

- index.html
Addresses Issue #1293 using an example from OBv3 for barrista training.
***
<a href="https://pr-preview.s3.amazonaws.com/longpd/vc-data-model/pull/1444.html" title="Last updated on Feb 26, 2024, 9:35 PM UTC (8418d8c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1444/d42fd22...longpd:8418d8c.html" title="Last updated on Feb 26, 2024, 9:35 PM UTC (8418d8c)">Diff</a>
> Example of the use of evidence in OBv3 VC

- index.html
Fix #1432
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1466.html" title="Last updated on Apr 2, 2024, 1:55 PM UTC (564e3c2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1466/25c3efa...564e3c2.html" title="Last updated on Apr 2, 2024, 1:55 PM UTC (564e3c2)">Diff</a>
> add language on public ids; example of urn

- contexts/credentials/v2
This PR implements the extra changes as described in https://github.com/w3c/vc-bitstring-status-list/pull/159#issuecomment-2027965995, now that https://github.com/w3c/vc-bitstring-status-list/pull/159 has been merged.
> Update v2 context

- index.html
- terms.html
partial handling of #1475
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/vc-data-model/pull/1483.html" title="Last updated on May 2, 2024, 5:47 PM UTC (7e3c6e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1483/1153f74...TallTed:7e3c6e1.html" title="Last updated on May 2, 2024, 5:47 PM UTC (7e3c6e1)">Diff</a>
> rationalize [credential ]{repositories/|repository}

- common.js
- index.html
This PR attempts to fix all of the merge conflicts for PR #1469.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1488.html" title="Last updated on May 26, 2024, 7:56 PM UTC (d5f2157)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1488/f3700e4...d5f2157.html" title="Last updated on May 26, 2024, 7:56 PM UTC (d5f2157)">Diff</a>
> Fix merge conflicts for PR #1469

- index.html
This is an alternative to #1515, along the lines of @dlongley's comment in https://github.com/w3c/vc-data-model/pull/1515#pullrequestreview-2151735713, but also my comment in https://github.com/w3c/vc-data-model/pull/1515#issuecomment-2202687385. 
I would propose to close #1515 without merge and concentrate on this PR instead. Merging this would also take care of #1512.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1519.html" title="Last updated on Jul 9, 2024, 1:53 PM UTC (1eaa93e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1519/8e9ae4e...1eaa93e.html" title="Last updated on Jul 9, 2024, 1:53 PM UTC (1eaa93e)">Diff</a>
> Reformulating the definition of securing mechanism

- index.html
This PR is an attempt to address issue #1507 by adding a section about artificial intelligence to the Security Considerations section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1508.html" title="Last updated on Jul 17, 2024, 7:26 PM UTC (7cc406e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1508/d3b654e...7cc406e.html" title="Last updated on Jul 17, 2024, 7:26 PM UTC (7cc406e)">Diff</a>
> Add Artificial Intelligence section to Security Considerations.

- index.html
Addresses issue https://github.com/w3c/vc-data-model/issues/1479
(Thank you to Alex Higuera for your help!)
***
<a href="https://pr-preview.s3.amazonaws.com/dmitrizagidulin/vc-data-model/pull/1532.html" title="Last updated on Aug 3, 2024, 8:12 PM UTC (4fb3b4c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1532/97f7b90...dmitrizagidulin:4fb3b4c.html" title="Last updated on Aug 3, 2024, 8:12 PM UTC (4fb3b4c)">Diff</a>
> Add an example dual language VC.

- index.html
This PR is an attempt to partially address issue #1437 by updating the examples in the `termsOfUse` section to use examples from the work that EBSI has deployed.
The PR will need further refinement from @alenhorvat for some of the values in the examples. Please suggest changes to the PR with the appropriate values for the example (and any additional language you feel might be useful).
This PR is a replacement form PR #1498.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1533.html" title="Last updated on Aug 3, 2024, 8:41 PM UTC (2bfd656)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1533/ccbe460...2bfd656.html" title="Last updated on Aug 3, 2024, 8:41 PM UTC (2bfd656)">Diff</a>
> Refactor Terms of Use section to use EBSI examples.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1546.html" title="Last updated on Aug 16, 2024, 4:01 PM UTC (b0feaaf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1546/4c6005d...b0feaaf.html" title="Last updated on Aug 16, 2024, 4:01 PM UTC (b0feaaf)">Diff</a>
> Explain the use of application/vc|vp in envelopes.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1547.html" title="Last updated on Aug 15, 2024, 2:55 PM UTC (c814732)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1547/4c6005d...c814732.html" title="Last updated on Aug 15, 2024, 2:55 PM UTC (c814732)">Diff</a>
> Remove trailing commas from relatedResource JSON.

- index.html
Fixes: #1548
***
<a href="https://pr-preview.s3.amazonaws.com/laysakura/vc-data-model/pull/1550.html" title="Last updated on Aug 19, 2024, 9:00 PM UTC (e68b995)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1550/8f71b6d...laysakura:e68b995.html" title="Last updated on Aug 19, 2024, 9:00 PM UTC (e68b995)">Diff</a>
> docs: Clarify the Role of Verifiers in Preventing Replay Attacks

- index.html
Fixes #1538
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1565.html" title="Last updated on Sep 18, 2024, 7:35 PM UTC (f3751e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1565/ae63dda...f3751e5.html" title="Last updated on Sep 18, 2024, 7:35 PM UTC (f3751e5)">Diff</a>
> Update respec-vc to v3.3.5.

- index.html
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Sep 27, 2024, 3:31 PM UTC)_.
<details>
:link: [Related URL]([object Object])
```
😭  Sorry, there was an error generating the HTML. Please report this issue!
Specification: http://localhost:8082/uploads/5ne3ko/index.html?isPreview=true%3FisPreview%3Dtrue&publishDate=2024-09-27
ReSpec version: 35.1.2
File a bug: https://github.com/speced/respec/
Error: undefined
```
_If you don't have enough information above to solve the error …
> Proofreading the Security Considerations section

- index.html
replaces suggestions on #1561
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1569.html" title="Last updated on Oct 3, 2024, 7:38 PM UTC (060e45b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1569/062e4b3...060e45b.html" title="Last updated on Oct 3, 2024, 7:38 PM UTC (060e45b)">Diff</a>
> clarify language in index.html

- index.html
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Dec 2, 2024, 4:19 PM UTC)_.
<details>
:link: [Related URL]([object Object])
```
Timed out after waiting 30000ms
```
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/vc-data-model%231572.)._
</details>
> Added Added Netis Contract number in Acknowledgements

- index.html
This PR finalizes the Acknowledgements, Authors, and Editors lists based on the following data.
For the Editors, their contributions since the beginning of the v2.0 VCWG are visible here:
https://github.com/w3c/vc-data-model/graphs/contributors?from=6%2F1%2F2022
For Authors, I'm a bit on the fence -- there is an argument to add Orie, Ted, Brent, Ivan, and Joe (who are already acknowledged as going above and beyond in the Acknowledgements) if we can point to significant concepts or content in the core specification that were contributed by each of them. For example, adding Ivan made sense because he single handedly authored all of the vocabulary documents and build tool, which was a significant effort. Ted's contributions were more editorial in nature, which is where his credit went. I …
> Finalize list of Editors, Authors, and Acknowledgements.

- index.html
Reverts w3c/vc-data-model#1579
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1584.html" title="Last updated on Jan 18, 2025, 7:51 PM UTC (4d9823a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1584/cc659aa...4d9823a.html" title="Last updated on Jan 18, 2025, 7:51 PM UTC (4d9823a)">Diff</a>
> Revert "Finalize list of Editors, Authors, and Acknowledgements."

- index.html
Update for #1594.
***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/vc-data-model/pull/1595.html" title="Last updated on Apr 23, 2025, 9:23 AM UTC (2890b1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1595/db8fa5b...shigeya:2890b1d.html" title="Last updated on Apr 23, 2025, 9:23 AM UTC (2890b1d)">Diff</a>
> Update Acknowledgements in the RWoT part
